### ISSUE TITLE
Hackerrank problems

### ISSUE THREAD

**Issue by Nivedita967** [Nivedita967/Data-Structure-and-Algorithms#1]
Add Hackerrank problems with the solution code in respective languages.

**Comment by kmryashasvi** [comment]
Can I add general problems which are of beginner levels (not on data-structures and algorithms)

**Comment by Nivedita967** [comment]
Hey @kmryashasvi , Which type of questions you want add?

**Comment by kmryashasvi** [comment]
Easy  level questions of individual "practice" sections of different languages.
message me on instagram @sqlyash to know more.

@Nivedita967

**Comment by Nivedita967** [comment]
@kmryashasvi Sure, go for it.

**Comment by Nivedita967** [comment]
@kmryashasvi Are you still working on it?

**Comment by kmryashasvi** [comment]
@Nivedita967 
I am in btech 1st year
I have my exams on 27th to 30th january
I will surely try to add something after that

**Comment by Nivedita967** [comment]
No Problem @kmryashasvi
