### ISSUE TITLE
Removing duplicates from an array 

### ISSUE THREAD

**Issue by Sloth-Panda** [Nivedita967/Data-Structure-and-Algorithms#100]
Would like to implement this using java .

**Comment by gopichandpuli9** [comment]
I would like to implement this in python and C++.

**Comment by Nivedita967** [comment]
@Sloth-Panda Please provide problem link.

**Comment by deeqakkk** [comment]
i can code it  in c++ as well as c.

**Comment by Sloth-Panda** [comment]
https://leetcode.com/problems/remove-duplicates-from-sorted-array/ 

Above is the link, can I do it in c/java @Nivedita967 ?

**Comment by Nivedita967** [comment]
@Sloth-Panda -> C, java
@gopichandpuli9 -> python
@deeqakkk -> C++

**Comment by Nivedita967** [comment]
@Sloth-Panda Are you working on this ?

**Comment by Sloth-Panda** [comment]
@Nivedita967 hey sorry  I just forgot sending the pr super soon
