### ISSUE TITLE
Counting valleys on hackerrank

### ISSUE THREAD

**Issue by stlyash** [Nivedita967/Data-Structure-and-Algorithms#1012]
### Problem Link 
https://www.hackerrank.com/challenges/counting-valleys/problem

### Coding platform
Hackerrank

### Programming language 

- [x] C
- [x] C++
- [x] Java
- [x] Python

**Comment by kmryashasvi** [comment]
I will provide solution in C++

**Comment by Akash20x** [comment]
I would like to solve this issue in python

**Comment by abhinav5481** [comment]
Hi @Nivedita967 
I would like to solve it in Java. Please assign it to me.

**Comment by kanak22** [comment]
I would like to do this in C.

**Comment by Akash20x** [comment]
@Nivedita967 Please check my pull request
