### ISSUE TITLE
Electronics shop on hackerrank

### ISSUE THREAD

**Issue by stlyash** [Nivedita967/Data-Structure-and-Algorithms#1013]
### Problem Link 
https://www.hackerrank.com/challenges/electronics-shop/problem?h_r=next-challenge&h_v=zen

### Coding platform
Hackerrank

### Programming language

- [x] C
- [x] C++
- [x] Java
- [ ] Python

**Comment by kmryashasvi** [comment]
I will do it in C++

**Comment by Akash20x** [comment]
I want to solve it in python

**Comment by abhinav5481** [comment]
Hi @Nivedita967 
I would like to solve it in Java. Please assign it to me.

**Comment by kanak22** [comment]
I would like to do this in C.

**Comment by pri1311** [comment]
can I do it in Python or Java?

**Comment by Nivedita967** [comment]
> can I do it in Python or Java?

Not open

**Comment by Nivedita967** [comment]
@Akash20x Are you working on this?

**Comment by Akash20x** [comment]
> @Akash20x Are you working on this?

Yes, send PR soon
