### ISSUE TITLE
Reversing a linkedlist without recursion

### ISSUE THREAD

**Issue by Sloth-Panda** [Nivedita967/Data-Structure-and-Algorithms#102]
would like to implement this using java

**Comment by sujal111** [comment]
Allow me to solve this

**Comment by Sloth-Panda** [comment]
@sujal111 bro you can make another issue for a different type of problem and go on with the same . Let me solve this if not happens you will do

**Comment by Nivedita967** [comment]
@Sloth-Panda Please Provide problem link and platform name in all your issues.
And here different languages are allowed, so every can solve one issue at the same time in different languages.

**Comment by Sloth-Panda** [comment]
@Nivedita967 I was practicing this randomly so is there any need for the problem link? I mean I will be explaining it in the pr only
Let me know

**Comment by Nivedita967** [comment]
Yes, Problem link is needed. Kindly search this problem on coding platform, this is famous one.

**Comment by Nivedita967** [comment]
@Sloth-Panda Should I close this issue ?

**Comment by Sloth-Panda** [comment]
@Nivedita967 No I will be just putting the link from any coding platform keep it open . I mean its ur choice whatever u do

**Comment by Nivedita967** [comment]
Okay no problem.

**Comment by Nivedita967** [comment]
@Sloth-Panda ???

**Comment by Sloth-Panda** [comment]
https://leetcode.com/problems/reverse-linked-list/  here @Nivedita967  will be sending pr sooner

**Comment by Nivedita967** [comment]
@sujal111 Tell me your language in which you want to code.

**Comment by ishikabansal04** [comment]
Is this problem open for C++? If yes, please assign me @Nivedita967

**Comment by Nivedita967** [comment]
@ishikabansal04 Go for it :)
