### ISSUE TITLE
 Perfect Squares

### ISSUE THREAD

**Issue by ishikabansal04** [Nivedita967/Data-Structure-and-Algorithms#1029]
### Problem Link 
https://leetcode.com/problems/perfect-squares/

### Coding platform
Leetcode

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [x] Python

**Comment by ishikabansal04** [comment]
Please assign me in Java.

**Comment by weirdrag08** [comment]
I want to do this in C++ :)

**Comment by abhinav5481** [comment]
Hi @Nivedita967 
I would like to solve it in Python. Please assign it to me.

**Comment by Akash20x** [comment]
@Nivedita967 I want to solve it in C
Please assign it to me

**Comment by Akash20x** [comment]
@Nivedita967 Please check my pull request
