### ISSUE TITLE
Longest Common Subsequence

### ISSUE THREAD

**Issue by ishikabansal04** [Nivedita967/Data-Structure-and-Algorithms#1030]
### Problem Link 
https://practice.geeksforgeeks.org/problems/longest-common-subsequence-1587115620/1

### Coding platform
GeeksforGeeks

### Programming language

- [x] C
- [ ] C++
- [x] Java
- [x] Python

**Comment by ishikabansal04** [comment]
Please assign me in Java.

**Comment by weirdrag08** [comment]
I want to do in C++:)

**Comment by abhinav5481** [comment]
Hi @Nivedita967 
I would like to solve it in Python. Please assign it to me.

**Comment by kanak22** [comment]
I would like to do this in C.
