### ISSUE TITLE
Longest Palindromic Subsequence

### ISSUE THREAD

**Issue by weirdrag08** [Nivedita967/Data-Structure-and-Algorithms#1031]
### Problem Link 
https://www.geeksforgeeks.org/longest-palindromic-subsequence-dp-12/

### Coding platform
GeeksforGeeks

### Programming language

- [x] C
- [ ] C++
- [x] Java
- [x] Python

**Comment by weirdrag08** [comment]
Please review and assign me in C++ :)

**Comment by ishikabansal04** [comment]
I want to do this in Java.

**Comment by abhinav5481** [comment]
Hi @Nivedita967 
I would like to solve it in Python. Please assign it to me.

**Comment by kanak22** [comment]
I would like to do this in C.
