### ISSUE TITLE
Longest Palindromic Substring

### ISSUE THREAD

**Issue by weirdrag08** [Nivedita967/Data-Structure-and-Algorithms#1032]
### Problem Link 
https://leetcode.com/problems/longest-palindromic-substring/

### Coding platform
Leetcode

### Programming language

- [ ] C
- [ ] C++
- [x] Java
- [x] Python

**Comment by weirdrag08** [comment]
Please review and assign me in C++ :)

**Comment by ishikabansal04** [comment]
Please assign me in Java.

**Comment by abhinav5481** [comment]
Hi @Nivedita967 
I would like to solve it in Python. Please assign it to me.

**Comment by Akash20x** [comment]
@Nivedita967  I want to solve it in C
Please assign it to me

**Comment by Akash20x** [comment]
@Nivedita967 Please check my pull request
