### ISSUE TITLE
Count Palindromic Subsequences

### ISSUE THREAD

**Issue by ishikabansal04** [Nivedita967/Data-Structure-and-Algorithms#1033]
### Problem Link 
https://practice.geeksforgeeks.org/problems/count-palindromic-subsequences/1

### Coding platform
GeeksforGeeks

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [x] Python

**Comment by ishikabansal04** [comment]
Please assign me in Java.

**Comment by weirdrag08** [comment]
Please assign me in C++ :)

**Comment by abhinav5481** [comment]
Hi @Nivedita967 
I would like to solve it in Python. Please assign it to me.

**Comment by kanak22** [comment]
I would like to do this in C.

**Comment by Nivedita967** [comment]
@kanak22 Are you working on this?

**Comment by kanak22** [comment]
@Nivedita967 its not for C :(

**Comment by kanak22** [comment]
@Nivedita967 Kindly check the PR :)
