### ISSUE TITLE
Count Palindrome Sub-Strings of a String

### ISSUE THREAD

**Issue by ishikabansal04** [Nivedita967/Data-Structure-and-Algorithms#1034]
### Problem Link 
https://practice.geeksforgeeks.org/problems/count-palindrome-sub-strings-of-a-string/0

### Coding platform
GeeksforGeeks

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [x] Python

**Comment by ishikabansal04** [comment]
Please assign me in Java.

**Comment by weirdrag08** [comment]
I want to work on this in C++ :)

**Comment by abhinav5481** [comment]
Hi @Nivedita967 
I would like to solve it in Python. Please assign it to me.

**Comment by kanak22** [comment]
I would like to do this in C.

**Comment by Nivedita967** [comment]
@kanak22 Are you working on this?

**Comment by kanak22** [comment]
> @kanak22 Are you working on this?

As I opened it I found out its not for C. :)

**Comment by kanak22** [comment]
> @kanak22 Are you working on this?

I m trying :)

**Comment by kanak22** [comment]
@Nivedita967 Kindly check the PR :)
