### ISSUE TITLE
Distinct Subsequences II

### ISSUE THREAD

**Issue by weirdrag08** [Nivedita967/Data-Structure-and-Algorithms#1035]
### Problem Link 
https://leetcode.com/problems/distinct-subsequences-ii/

### Coding platform
Leetcode

### Programming language

- [x] C
- [ ] C++
- [x] Java
- [x] Python

**Comment by weirdrag08** [comment]
Please review and assign me in C++

**Comment by ishikabansal04** [comment]
I want this for Java.

**Comment by abhinav5481** [comment]
Hi @Nivedita967 
I would like to solve it in Python. Please assign it to me.

**Comment by Akash20x** [comment]
@Nivedita967 I want to solve it in C
Please assign it to me
