### ISSUE TITLE
Count Different Palindromic Subsequences

### ISSUE THREAD

**Issue by weirdrag08** [Nivedita967/Data-Structure-and-Algorithms#1036]
### Problem Link 
https://leetcode.com/problems/count-different-palindromic-subsequences/

### Coding platform
Leetcode

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [x] Python

**Comment by weirdrag08** [comment]
Please review & assign me in C++ :)

**Comment by ishikabansal04** [comment]
Please assign me in Java.

**Comment by abhinav5481** [comment]
Hi @Nivedita967 
I would like to solve it in Python. Please assign it to me.

**Comment by Akash20x** [comment]
I want to solve it in C
Please assign it to me

**Comment by Akash20x** [comment]
@Nivedita967 Please check my pull request

**Comment by Nivedita967** [comment]
@Akash20x I have requested you changes in your PR. Check it ASAP.

**Comment by Akash20x** [comment]
> @Akash20x I have requested you changes in your PR. Check it ASAP.

Done
