### ISSUE TITLE
Common Child

### ISSUE THREAD

**Issue by weirdrag08** [Nivedita967/Data-Structure-and-Algorithms#1037]
### Problem Link 
https://www.hackerrank.com/challenges/common-child/problem

### Coding platform
Hackerrank

### Programming language

- [x] C
- [x] C++
- [x] Java
- [x] Python

**Comment by weirdrag08** [comment]
Please review and assign me in C++ :)

**Comment by ishikabansal04** [comment]
Please assign me in Java.

**Comment by abhinav5481** [comment]
Hi @Nivedita967 
I would like to solve it in Python. Please assign it to me.

**Comment by kanak22** [comment]
I would like to do this in C.
