### ISSUE TITLE
Max Array Sum

### ISSUE THREAD

**Issue by ishikabansal04** [Nivedita967/Data-Structure-and-Algorithms#1038]
### Problem Link 
https://www.hackerrank.com/challenges/max-array-sum/problem?h_l=interview&playlist_slugs%5B%5D=interview-preparation-kit&playlist_slugs%5B%5D=dynamic-programming

### Coding platform
Hackerrank 

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [x] Python

**Comment by ishikabansal04** [comment]
I want to work on this issue in Java.

**Comment by weirdrag08** [comment]
Please assign me in C++ :)

**Comment by abhinav5481** [comment]
Hi @Nivedita967 
I would like to solve it in Python. Please assign it to me.

**Comment by kanak22** [comment]
I would like to do this in C.

**Comment by JASKAMAL22** [comment]
Hello @Nivedita967 , I would like to do it in python. Kindly assign it to me! :)

**Comment by Nivedita967** [comment]
> Hello @Nivedita967 , I would like to do it in python. Kindly assign it to me! :)

Not open.

**Comment by Amit366** [comment]
@Nivedita967 is it open??

**Comment by Nivedita967** [comment]
> @Nivedita967 is it open??

NO.

**Comment by Nivedita967** [comment]
@kanak22 Are you working on this?

**Comment by kanak22** [comment]
> @kanak22 Are you working on this?

yes just give me half an hour :)

**Comment by kanak22** [comment]
@Nivedita967  I made the PR. Kindly check :)
