### ISSUE TITLE
K-th Smallest Prime Fraction

### ISSUE THREAD

**Issue by Akash20x** [Nivedita967/Data-Structure-and-Algorithms#1039]
### Problem Link 
https://leetcode.com/problems/k-th-smallest-prime-fraction/description/

### Coding platform
Leetcode 

### Programming language

- [x] C
- [ ] C++
- [x] Java
- [x] Python

### Additional context (OPTIONAL)
This is leetcode hard problem 
I want to solve it in python, please assign me this issue

**Comment by Akash20x** [comment]
@Nivedita967 I want to solve it in python. Please assign me this issue as a part of Cross Woc

**Comment by Amit366** [comment]
@Nivedita967 can I work in Java??

**Comment by jayantjethi** [comment]
I would Like to solve this problem in c++. kindly assign me

**Comment by abhinav5481** [comment]
Hi @Nivedita967 
I would like to solve it in c. Please assign it to me.

**Comment by Akash20x** [comment]
@Nivedita967 Please check my pull request
