### ISSUE TITLE
Point of Impact

### ISSUE THREAD

**Issue by kavania2002** [Nivedita967/Data-Structure-and-Algorithms#104]
Point of Impact : Codechef : https://www.codechef.com/problems/BILLRD

I will do it in Python

**Comment by Nivedita967** [comment]
Kindly solve previous assigned issues first.

**Comment by kavania2002** [comment]
Now can I start working on this and the #105 one.

**Comment by Nivedita967** [comment]
Sure Go for it :)

**Comment by Nivedita967** [comment]
Open for C, C++, Java.

**Comment by Nivedita967** [comment]
@weirdrag08
