### ISSUE TITLE
First Missing Positive

### ISSUE THREAD

**Issue by kanak22** [Nivedita967/Data-Structure-and-Algorithms#1044]
### Problem Link 
https://leetcode.com/problems/first-missing-positive/

### Coding platform
Leetcode

### Programming language

- [x] C
- [ ] C++
- [x] Java
- [x] Python

### Additional context (OPTIONAL)
I would like to work on this in C++

**Comment by Akash20x** [comment]
I want to solve it in python

**Comment by abhinav5481** [comment]
Hi @Nivedita967 
I would like to solve it in Java. Please assign it to me.

**Comment by pri1311** [comment]
Can I do it in C?

**Comment by JASKAMAL22** [comment]
I would like to do it in python. Can you please assign it to me!

**Comment by Nivedita967** [comment]
> Hi @Nivedita967
> I would like to solve it in Java. Please assign it to me.

Java solution of this problem is already present in this project.

**Comment by Nivedita967** [comment]
> I would like to do it in python. Can you please assign it to me!

Python is not open.

**Comment by KaranBhut44** [comment]
I would like to do it in C++. Please assign it to me

**Comment by abhinav5481** [comment]
> > Hi @Nivedita967
> > I would like to solve it in Java. Please assign it to me.
> 
> Java solution of this problem is already present in this project.

Okay then. Can I do it in C?

**Comment by Akash20x** [comment]
@Nivedita967 Please check my pull request

**Comment by Nivedita967** [comment]
> > > Hi @Nivedita967
> > > I would like to solve it in Java. Please assign it to me.
> > 
> > 
> > Java solution of this problem is already present in this project.
> 
> Okay then. Can I do it in C?

C is not open.
