### ISSUE TITLE
Wildcard Matching

### ISSUE THREAD

**Issue by kanak22** [Nivedita967/Data-Structure-and-Algorithms#1046]
### Problem Link 
https://leetcode.com/problems/wildcard-matching/

### Coding platform
Leetcode

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [x] Python

### Additional context (OPTIONAL)
I would like to do this in C++.

**Comment by Akash20x** [comment]
I want to solve it in python

**Comment by abhinav5481** [comment]
Hi @Nivedita967 
I would like to solve it in Java. Please assign it to me.

**Comment by Amit366** [comment]
@Nivedita967 can I solve in c++?

**Comment by pri1311** [comment]
can I do it in C?

**Comment by Akash20x** [comment]
@Nivedita967 Please check my pull request
