### ISSUE TITLE
Sail

### ISSUE THREAD

**Issue by kanak22** [Nivedita967/Data-Structure-and-Algorithms#1047]
### Problem Link 
https://codeforces.com/problemset/problem/298/B

### Coding platform
Codeforces

### Programming language

- [x] C
- [x] C++
- [x] Java
- [x] Python

### Additional context (OPTIONAL)
I would like to do this in C++.

**Comment by Akash20x** [comment]
I want to solve it in python

**Comment by abhinav5481** [comment]
Hi @Nivedita967 
I would like to solve it in Java. Please assign it to me.

**Comment by pri1311** [comment]
will do it in C

**Comment by Akash20x** [comment]
@Nivedita967 Please check my pull request
