### ISSUE TITLE
Prime Tuples

### ISSUE THREAD

**Issue by kavania2002** [Nivedita967/Data-Structure-and-Algorithms#105]
Prime Tuples : CodeChef : https://www.codechef.com/problems/PTUPLES

I will do it in C++

**Comment by simonnepinto** [comment]
Can I implement it in Java?

**Comment by Nivedita967** [comment]
@simonnepinto Sure, Go for it. 
Also join Gitter channel- https://gitter.im/Data-Structure-and-Algorithms-Nivedita/community

**Comment by Nivedita967** [comment]
@Abhichal18 This issue is also open for Python.

**Comment by Abhichal18** [comment]
> @Abhichal18 This issue is also open for Python.
I would like to contribute this also.

**Comment by Nivedita967** [comment]
@Abhichal18 Are you working on this ?

**Comment by Abhichal18** [comment]
> @Abhichal18 Are you working on this ?

yes
