### ISSUE TITLE
Flatten Binary Tree to Linked List

### ISSUE THREAD

**Issue by rahil-1407** [Nivedita967/Data-Structure-and-Algorithms#1050]
### Problem Link 
https://leetcode.com/problems/flatten-binary-tree-to-linked-list/

### Coding platform
LeetCode

### Programming language

- [x] C
- [x] C++
- [x] Java
- [x] Python

**Comment by pri1311** [comment]
can do it in C++ or python

**Comment by Amit366** [comment]
@Nivedita967 can I work in Java?

**Comment by Akash20x** [comment]
I want to solve it in python

**Comment by rahil-1407** [comment]
Assign me in C++.

**Comment by abhinav5481** [comment]
Hi @Nivedita967 
I would like to solve it in C. Please assign it to me.

**Comment by Nivedita967** [comment]
@rahil-1407 ->C++
@pri1311 ->python
@Amit366 ->Java
@abhinav5481 ->C

**Comment by Nivedita967** [comment]
@rahil-1407 Are you working on this?
