### ISSUE TITLE
Odd Even Linked List

### ISSUE THREAD

**Issue by jasmine1601** [Nivedita967/Data-Structure-and-Algorithms#1088]
### Problem Link 
https://leetcode.com/problems/odd-even-linked-list/

### Coding platform
Leetcode

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [x] Python

### Additional context (OPTIONAL)
I want to solve this in Java.

**Comment by abhinav5481** [comment]
Hi @Nivedita967 
I would like to solve it in Python. Please assign it to me

**Comment by JASKAMAL22** [comment]
I want to do it in C++. Kindly assign it to me! :)

**Comment by Akash20x** [comment]
I want to solve it in C. Please assign me this issue as a part of Cross Woc

**Comment by Akash20x** [comment]
@Nivedita967 Please check my pull request
