### ISSUE TITLE
Jumping on the Clouds

### ISSUE THREAD

**Issue by jasmine1601** [Nivedita967/Data-Structure-and-Algorithms#109]
Problem link: https://www.hackerrank.com/challenges/jumping-on-the-clouds/problem.
I will solve it in Java.

**Comment by Nivedita967** [comment]
@jasmine1601 Go for it :)

**Comment by TechSpiritSS** [comment]
Can I do this in C?

**Comment by Abhichal18** [comment]
can i do it in python?

**Comment by Nivedita967** [comment]
@Abhichal18 Go for it .

**Comment by Nivedita967** [comment]
Open for C++

**Comment by Nivedita967** [comment]
@weirdrag08

**Comment by deepesh101** [comment]
Hi @Nivedita967,
Can I do it in C++?

**Comment by Nivedita967** [comment]
Sure @deepesh101 Go for it :)
