### ISSUE TITLE
Odd Divisor

### ISSUE THREAD

**Issue by Kpraful** [Nivedita967/Data-Structure-and-Algorithms#1096]
### Problem Link 
https://codeforces.com/problemset/problem/1475/A

### Coding platform
Codeforces

### Programming language

- [x] C
- [x] C++
- [x] Java
- [ ] Python

### Additional context (OPTIONAL)
I would like to solve this in c++

**Comment by JASKAMAL22** [comment]
I would like to solve in python.  Kindly assign me:)

**Comment by Akash20x** [comment]
I want to solve it in C

**Comment by abhinav5481** [comment]
Hi @Nivedita967 
I would like to solve it Java. Please assign it to me

**Comment by Akash20x** [comment]
@Nivedita967 Please check my pull request
