### ISSUE TITLE
kth-smallest-number-in-multiplication-table

### ISSUE THREAD

**Issue by Amit366** [Nivedita967/Data-Structure-and-Algorithms#1101]
### Problem Link 
https://leetcode.com/problems/kth-smallest-number-in-multiplication-table/

### Coding platform
Leetcode

### Programming language

- [x] C
- [x] C++ 
- [x] Java
- [x] Python

### Additional context (OPTIONAL)
I want to work in Java and python

**Comment by JASKAMAL22** [comment]
Hey @Nivedita967 I would like to do it in python. Can you please assign it to me! :)

**Comment by Akash20x** [comment]
I want to solve it in C++

**Comment by abhinav5481** [comment]
Hi @Nivedita967
I would like to solve it in C. Please assign it to me.

**Comment by pri1311** [comment]
If it is open can do it in C++ or python

**Comment by Nivedita967** [comment]
@Amit366 Go for Java only.

**Comment by Nivedita967** [comment]
> If it is open can do it in C++ or python

Not open.

**Comment by Akash20x** [comment]
@Nivedita967 Please check my pull request
