### ISSUE TITLE
Subarrays with K Different Integers

### ISSUE THREAD

**Issue by greenblade29** [Nivedita967/Data-Structure-and-Algorithms#1104]
### Problem Link 
https://leetcode.com/problems/subarrays-with-k-different-integers/

### Coding platform
Leetcode

### Programming language

- [x] C
- [ ] C++
- [x] Java
- [x] Python

### Additional context (OPTIONAL)
I want to solve it in Java

**Comment by Akash20x** [comment]
I want to solve it in python

**Comment by pri1311** [comment]
I can solve it in C++

**Comment by abhinav5481** [comment]
Hi @Nivedita967 
I would like to solve it in C. Please assign it to me

**Comment by Akash20x** [comment]
@Nivedita967 Please check my pull request
