### ISSUE TITLE
Count All Valid Pickup and Delivery Options

### ISSUE THREAD

**Issue by greenblade29** [Nivedita967/Data-Structure-and-Algorithms#1105]
### Problem Link 
https://leetcode.com/problems/count-all-valid-pickup-and-delivery-options/

### Coding platform
Leetcode

### Programming language

- [x] C
- [ ] C++
- [ ] Java
- [x] Python

### Additional context (OPTIONAL)
I want to solve it in Java

**Comment by Akash20x** [comment]
I want to solve it in python

**Comment by pri1311** [comment]
I can solve it in C++

**Comment by Amit366** [comment]
@Nivedita967 can I work in C??

**Comment by abhinav5481** [comment]
Hi @Nivedita967 
I would like to solve it in c++. Please assign it to me

**Comment by Nivedita967** [comment]
> Hi @Nivedita967
> I would like to solve it in c++. Please assign it to me

Not open.

**Comment by abhinav5481** [comment]
> > Hi @Nivedita967
> > I would like to solve it in c++. Please assign it to me
> 
> Not open.

Which language is open?

**Comment by Akash20x** [comment]
@Nivedita967 Please check my pull request
