### ISSUE TITLE
Target Sum 

### ISSUE THREAD

**Issue by greenblade29** [Nivedita967/Data-Structure-and-Algorithms#112]
Problem Link: https://leetcode.com/problems/target-sum/ on Leetcode using dynamic programming

Programming Languages:
- [ ] C
- [x] C++
- [x] Java
- [x] Python

**Comment by greenblade29** [comment]
@Nivedita967 Please verify the question and assign it to me

**Comment by deephunt3r** [comment]
@Nivedita967 can you please assign it to me 
I will solve this in python

**Comment by Nivedita967** [comment]
Open for C.

**Comment by weirdrag08** [comment]
I want to solve this issue in C++. @Nivedita967 can i be assigned this task please.

**Comment by greenblade29** [comment]
> I want to solve this issue in C++. @Nivedita967 can i be assigned this task please.

Its already done in C++.. you can try in C

**Comment by weirdrag08** [comment]
> > I want to solve this issue in C++. @Nivedita967 can i be assigned this task please.
> 
> Its already done in C++.. you can try in C

Sure, @Nivedita967 please assign me this in C then.

**Comment by Nivedita967** [comment]
@weirdrag08 Sure, go for it.

**Comment by Nivedita967** [comment]
@weirdrag08 Are you working on this ?

**Comment by weirdrag08** [comment]
> @weirdrag08 Are you working on this ?

I am facing issues on this one, you can unassign me :-\
