### ISSUE TITLE
Stone Game IV

### ISSUE THREAD

**Issue by abhinav5481** [Nivedita967/Data-Structure-and-Algorithms#1127]
### Problem Link 
https://leetcode.com/problems/stone-game-iv/

### Coding platform
Leetcode

### Programming language

- [x] C
- [x] C++
- [x] Java
- [x] Python

I would like to solve it in Java. Please assign it to me.

**Comment by abhinav5481** [comment]
Hi @Nivedita967 
I would like to solve it in Java. Please assign it to me

**Comment by Amit366** [comment]
@Nivedita967 can I do in python??

**Comment by Akash20x** [comment]
I want to solve it in C++

**Comment by abhinav5481** [comment]
Hi @Nivedita967 
If it's possible, Can you assign it to me in C?

**Comment by Akash20x** [comment]
@Nivedita967 Please check my pull request

**Comment by Amit366** [comment]
@Nivedita967 please review my PR

**Comment by Nivedita967** [comment]
> Hi @Nivedita967
> If it's possible, Can you assign it to me in C?

Sure Go for  C also.
