### ISSUE TITLE
Rank Transform of an Array

### ISSUE THREAD

**Issue by Akash20x** [Nivedita967/Data-Structure-and-Algorithms#113]
Problem Link:
https://leetcode.com/problems/rank-transform-of-an-array/description/
Please verify this problem and assign it to me

**Comment by Nivedita967** [comment]
@Akash20x Please mention the language in which you want to code and Join Gitter channel :)

**Comment by Akash20x** [comment]
I will solve it in java language and thanks for
assigning me.

**Comment by Akash20x** [comment]
I will solve it in java language and thanks for
assigning me

**Comment by Nivedita967** [comment]
@Abhichal18 This issue is open for python.

**Comment by Nivedita967** [comment]
@TechSpiritSS Open for C and C++ also.

**Comment by Abhichal18** [comment]
> @TechSpiritSS Open for C and C++ also.



> @Abhichal18 This issue is open for python.



> @Abhichal18 This issue is open for python.

I would like to contribute

**Comment by Nivedita967** [comment]
@Akash20x C++ is not yet contributed in this. How you can close this ?
