### ISSUE TITLE
Couples Holding Hands

### ISSUE THREAD

**Issue by abhinav5481** [Nivedita967/Data-Structure-and-Algorithms#1130]
### Problem Link 
https://leetcode.com/problems/couples-holding-hands/

### Coding platform
Leetcode

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [x] Python

I would like to solve it in Java. Please assign it to me.

**Comment by abhinav5481** [comment]
Hi
I would like to solve it in Java

**Comment by Akash20x** [comment]
I want to solve it in python

**Comment by Amit366** [comment]
@Nivedita967 can I do in c++??

**Comment by Amit366** [comment]
@Nivedita967 can I solve in C??

**Comment by Akash20x** [comment]
@Nivedita967 Please check my pull request

**Comment by Kpraful** [comment]
In which language is it open?

**Comment by Nivedita967** [comment]
> In which language is it open?

Open for C

**Comment by Amit366** [comment]
> @Nivedita967 can I do in c++??

@Nivedita967 please assign this to me

**Comment by Nivedita967** [comment]
> > @Nivedita967 can I do in c++??
> 
> @Nivedita967 please assign this to me

Have you completed all issues assigned to you?

**Comment by Amit366** [comment]
@Nivedita967 yes

**Comment by Amit366** [comment]
In fact I don't have any assigned issues

**Comment by Nivedita967** [comment]
> In fact I don't have any assigned issues

Okay @Amit366 Go for C.

**Comment by Amit366** [comment]
@Nivedita967 please merge the PR
