### ISSUE TITLE
Shortest Path In Binary Matrix 

### ISSUE THREAD

**Issue by Akash20x** [Nivedita967/Data-Structure-and-Algorithms#114]
Problem Link:
https://leetcode.com/problems/shortest-path-in-binary-matrix/description/
Please verify this problem and assign it to me

**Comment by Nivedita967** [comment]
@Akash20x Language ?

**Comment by Akash20x** [comment]
In java language

**Comment by Nivedita967** [comment]
@Abhichal18 This issue is open for python.

**Comment by Nivedita967** [comment]
@TechSpiritSS Open for C and C++ also.

**Comment by gopichandpuli9** [comment]
I'll work in python

**Comment by Nivedita967** [comment]
@gopichandpuli9 Go for it.

**Comment by TechSpiritSS** [comment]
> @TechSpiritSS Open for C and C++ also.

this question is out of my reach :/

**Comment by Nivedita967** [comment]
@Akash20x Why have you closed this issue ?
