### ISSUE TITLE
Count Primes

### ISSUE THREAD

**Issue by gopichandpuli9** [Nivedita967/Data-Structure-and-Algorithms#115]
I would like to implement this in python,C++

**Comment by Nivedita967** [comment]
Please provide problem link.

**Comment by gopichandpuli9** [comment]
https://leetcode.com/problems/count-primes/

**Comment by Nivedita967** [comment]
@gopichandpuli9 go for it.

**Comment by Nivedita967** [comment]
Open for Java and C.

**Comment by TechSpiritSS** [comment]
May I submit for C?

**Comment by saksham-s1ngh** [comment]
May I be assigned to solve this in Java?

**Comment by Nivedita967** [comment]
@gopichandpuli9 you are going to implement it in C++ also ?

**Comment by TechSpiritSS** [comment]
I can do this in C++ too if required

**Comment by Nivedita967** [comment]
> I can do this in C++ too if required

Go for it.

**Comment by saksham-s1ngh** [comment]
@Nivedita967 Hi, so I'm new to the OSS sphere, and the thing is my forked repo is 80 commits behind, and I did solve this, but I cannot ask to merge that, since it's also 80 commits behind. What to do?

**Comment by Nivedita967** [comment]
No problem @saksham-s1ngh , Just add your code to respective folder and try to create pull request.

**Comment by saksham-s1ngh** [comment]
#298 Fixed problem in Java

**Comment by Nivedita967** [comment]
@saksham-s1ngh ???

**Comment by saksham-s1ngh** [comment]
@Nivedita967 I'm sorry, I messaged on twitter. My computer broke, and I don't have a system right now. If anyone wants to solve, you can assign it to them. ;-;

**Comment by saksham-s1ngh** [comment]
> @saksham-s1ngh ???

Do I have to add comments? Don't have a computer right now, sorry. :(
