### ISSUE TITLE
Maximise Function

### ISSUE THREAD

**Issue by gh4abhi** [Nivedita967/Data-Structure-and-Algorithms#117]
Problem Link - https://www.codechef.com/FEB21B/problems/MAXFUN

**Comment by gh4abhi** [comment]
Please verify this problem and assign this to me.

**Comment by Nivedita967** [comment]
Kindly join Gitter channel and do mention the language in which you want to code :)

**Comment by TechSpiritSS** [comment]
Can I do this Que in C or C++?

**Comment by gh4abhi** [comment]
@Nivedita967  Sure! I will do it in C++.

**Comment by Nivedita967** [comment]
Okay, @TechSpiritSS Go for C.

**Comment by Abhichal18** [comment]
@Nivedita967 i would like to contribute in python.

**Comment by Nivedita967** [comment]
Open for Java.

**Comment by zenilharia26** [comment]
I would like to contribute to the solution in Java.
