### ISSUE TITLE
Apple and Orange

### ISSUE THREAD

**Issue by stlyash** [Nivedita967/Data-Structure-and-Algorithms#1235]
### Problem Link 
https://www.hackerrank.com/challenges/apple-and-orange/problem

### Coding platform
Hackerrank

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by stlyash** [comment]
I will provide solution in c++

**Comment by Nivedita967** [comment]
@stlyash You may directly open PR.
