### ISSUE TITLE
Can I add diagonal difference in c language(Hackerrank Question)

### ISSUE THREAD

**Issue by UG-SEP** [Nivedita967/Data-Structure-and-Algorithms#1239]
### Coding platform
I am picking this Question from Hackerrank
### Programming language

- [x] C

**Comment by Nivedita967** [comment]
Sure @UG-SEP Go for it.

**Comment by UG-SEP** [comment]
@Nivedita967  i can't add this because someone had added this question in c language but  created other repository 
![1](https://user-images.githubusercontent.com/75884061/113755973-89231680-972e-11eb-9596-0dc4d56876c9.jpg)
So can I merge the both repo in a repo

**Comment by UG-SEP** [comment]
can i create a new issue and add another question

**Comment by Nivedita967** [comment]
> can i create a new issue and add another question

Yah Sure Go ahead.
