### ISSUE TITLE
Update Contribution.md and Code of Conduct

### ISSUE THREAD

**Issue by muthuannamalai12** [Nivedita967/Data-Structure-and-Algorithms#124]
In Contribution.md file We can add the following 
1.We can add Github documentation links for
i). Getting started with Git and GitHub
ii). Forking a Repo
iiI). Cloning a Repo
iv). How to create a Pull Request
2.Also, we can give the links for git installation
3.We can also add Style Guides for Git Commit Messages
These things will help people new to opensource understand clearly on how to create an issue and how to create a PR.
Also, Code of Conduct is present in the same folder as Contributing.md we can place it in a Folder named as Code of Conduct.

**Comment by muthuannamalai12** [comment]
I would love to work on the issue as a part of Cross Woc. Kindly assign it to me.

**Comment by Nivedita967** [comment]
@muthuannamalai12 Yes, this will be helpful :)
