### ISSUE TITLE
Wanted to add encryption program(Hackerrank)

### ISSUE THREAD

**Issue by UG-SEP** [Nivedita967/Data-Structure-and-Algorithms#1249]
### Problem Link 
[Problem Link](https://www.hackerrank.com/challenges/encryption/problem)
### Coding platform
This program has been coded in Hackerrank
### Programming language

- [x] C
- [ ] C++
- [ ] Java
- [ ] Python

### Additional context (OPTIONAL)
Example:
`Input:`  feedthedog
> Procedure:
1: Read the String size here string length is 10 suppose 10 as square root of 10
2: Now find the number between 10 square come as here 10 square root comes between 3 square and 4 square
3:  Now take the 3 as rows  and 4 as column 
5: make a grid like this feed
                                     thed
                                    og
6: Now divide it like fto ehg ee dd

`Output:` fto ehg ee dd

**Comment by UG-SEP** [comment]
Please assign me

**Comment by Nivedita967** [comment]
> Please assign me

Sure @UG-SEP, Go for it.
