### ISSUE TITLE
cout>> error

### ISSUE THREAD

**Issue by kavania2002** [Nivedita967/Data-Structure-and-Algorithms#126]
Someone made error in the code.

This the link: https://github.com/Nivedita967/Data-Structure-and-Algorithms/blob/main/Codechef/Number%20Mirror/Number%20Mirror.cpp

This is the image
![errorcout](https://user-images.githubusercontent.com/72624080/107871021-f4d1cb80-6ec3-11eb-82d6-b0bfc9cf334d.PNG)

**Comment by kavania2002** [comment]
I want to correct it.

**Comment by Nivedita967** [comment]
@kavania2002 Sure.
