### ISSUE TITLE
Fair Elections Codechef

### ISSUE THREAD

**Issue by gh4abhi** [Nivedita967/Data-Structure-and-Algorithms#141]
Please verify the problem and assign it to me.

**Comment by gh4abhi** [comment]
Problem Link - https://www.codechef.com/JAN21B/problems/FAIRELCT

**Comment by gh4abhi** [comment]
I will do it in c++.

**Comment by Abhichal18** [comment]
@Nivedita967 i would like to contribute in python

**Comment by Nivedita967** [comment]
Open for C and Java
