### ISSUE TITLE
Balanced Brackets

### ISSUE THREAD

**Issue by Archna29** [Nivedita967/Data-Structure-and-Algorithms#143]
https://www.hackerrank.com/challenges/balanced-brackets/problem

**Comment by Archna29** [comment]
I would like to work on this issue using java

**Comment by Abhichal18** [comment]
@Nivedita967 I would like to contribute in python

**Comment by Nivedita967** [comment]
Open for C and C++.

**Comment by greenblade29** [comment]
@Nivedita967 I will do it in C++

**Comment by ishikabansal04** [comment]
@Nivedita967  I want to do this issue in C++.

**Comment by weirdrag08** [comment]
I wish to solve this task in C++. Please assign me this task.

**Comment by Nivedita967** [comment]
@greenblade29 Let the new contributors work on this :)
