### ISSUE TITLE
Partition Equal Subset Sum

### ISSUE THREAD

**Issue by greenblade29** [Nivedita967/Data-Structure-and-Algorithms#146]
Problem Link: https://leetcode.com/problems/partition-equal-subset-sum/ from leetcode using dynamic programming

Programming Languages:
- [ ] C
- [x] C++
- [x] Java
- [ ] Python

**Comment by greenblade29** [comment]
@Nivedita967 Please verify the question and assign it to me. I will be using Java and C++

**Comment by Nivedita967** [comment]
Open for C and Python.
