### ISSUE TITLE
Add code to ATM problem on codechef

### ISSUE THREAD

**Issue by kmryashasvi** [Nivedita967/Data-Structure-and-Algorithms#147]
I will working on the solution in C /C++ of  [ATM](https://www.codechef.com/problems/HS08TEST)

**Comment by Abhichal18** [comment]
@Nivedita967  i would like to contribute in python

**Comment by Nivedita967** [comment]
Java is done.

**Comment by kmryashasvi** [comment]
I think this issue can be closed after merging
