### ISSUE TITLE
Hail XOR 

### ISSUE THREAD

**Issue by gh4abhi** [Nivedita967/Data-Structure-and-Algorithms#151]
Problem Link - https://www.codechef.com/DEC20B/problems/HXOR

**Comment by gh4abhi** [comment]
Please verify the problem and assign it to me. I will do it in c++.

**Comment by Abhichal18** [comment]
@Nivedita967 i would like to contribute in python

**Comment by Nivedita967** [comment]
Open for C and Java

**Comment by Amit366** [comment]
@Nivedita967 can I implement it using java??

**Comment by Nivedita967** [comment]
@Amit366 Sure go for it.

**Comment by Nivedita967** [comment]
@Abhichal18 Are you working on this ?
