### ISSUE TITLE
Positive Prefixes 

### ISSUE THREAD

**Issue by gh4abhi** [Nivedita967/Data-Structure-and-Algorithms#153]
Problem Link - https://www.codechef.com/DEC20B/problems/POSPREFS

**Comment by gh4abhi** [comment]
Please verify the problem and assign this to me. I will do it in c++.

**Comment by Abhichal18** [comment]
@Nivedita967 I would like to contribute in python

**Comment by Nivedita967** [comment]
Open for C and Java.

**Comment by gh4abhi** [comment]
Please assign this task to me I have not yet added the code of this problem.
