### ISSUE TITLE
Chef and Division 3

### ISSUE THREAD

**Issue by kavania2002** [Nivedita967/Data-Structure-and-Algorithms#156]
Codechef : https://www.codechef.com/problems/DIVTHREE

I would like to do in Python and C++.

**Comment by vivek286** [comment]
please assign it to me i would like to do in java and C++

**Comment by TechSpiritSS** [comment]
I can do this in C

**Comment by TechSpiritSS** [comment]
and C++ too

**Comment by Nivedita967** [comment]
@kavania2002 ->Python
@vivek286 -> java
@TechSpiritSS -> C
and open for C++
lol.

**Comment by kavania2002** [comment]
Very nice 😂

**Comment by TechSpiritSS** [comment]
All three of us can do it in C++ and C++ solution is pending 😂😂

**Comment by kanak22** [comment]
Can I contribute in c++?

**Comment by kanak22** [comment]
U closed this issue so when I will pull a request for my c++ code regarding
this issue what should I mention in the #issue number? Kindly tell me this
😊

**Comment by Nivedita967** [comment]
Sorry for this. This is by mistake :)

**Comment by kanak22** [comment]
Thanks 😊

**Comment by kanak22** [comment]
@Nivedita967  it is again closed 😐

**Comment by kanak22** [comment]
@Nivedita967  kindly check it 😊

**Comment by Nivedita967** [comment]
@vivek286 Are you working on this ?

**Comment by kmryashasvi** [comment]
I can do it in java today itself

**Comment by kmryashasvi** [comment]
If it is pending for Java
