### ISSUE TITLE
Encoded String

### ISSUE THREAD

**Issue by kavania2002** [Nivedita967/Data-Structure-and-Algorithms#158]
Link: https://www.codechef.com/problems/DECODEIT

I would like to do it in Python

**Comment by TechSpiritSS** [comment]
I can do this in C++

**Comment by Nivedita967** [comment]
Open for C and Java.

**Comment by TechSpiritSS** [comment]
I can submit for C too

**Comment by 96RadhikaJadhav** [comment]
@Nivedita967 Can I add the program in Java?

**Comment by Nivedita967** [comment]
@96RadhikaJadhav ???

**Comment by 96RadhikaJadhav** [comment]
> @96RadhikaJadhav ???

@Nivedita967 Sorry for the delay. I have added comments now. Please check.
