### ISSUE TITLE
Vaccine Distribution

### ISSUE THREAD

**Issue by gh4abhi** [Nivedita967/Data-Structure-and-Algorithms#159]
Problem Link - https://www.codechef.com/DEC20B/problems/VACCINE2

**Comment by gh4abhi** [comment]
Please Verify the problem and assign it to me.

**Comment by gh4abhi** [comment]
I will do it in c++.

**Comment by TechSpiritSS** [comment]
I can do this in C

**Comment by Abhichal18** [comment]
@Nivedita967 I would like to contribute in python

**Comment by gh4abhi** [comment]
Please assign this task to me I have not yet added the code of this problem.

**Comment by Nivedita967** [comment]
Open for Java

**Comment by jasmine1601** [comment]
@Nivedita967 I want to try this in Java

**Comment by Nivedita967** [comment]
Sure @jasmine1601 Go for it :)
