### ISSUE TITLE
Gasoline Introduction

### ISSUE THREAD

**Issue by gh4abhi** [Nivedita967/Data-Structure-and-Algorithms#160]
Problem Link - https://www.codechef.com/LTIME90B/problems/BEGGASOL

**Comment by gh4abhi** [comment]
Please verify the problem and assign it to me. I will do it in c++.

**Comment by TechSpiritSS** [comment]
I can do this in C

**Comment by Abhichal18** [comment]
@Nivedita967  i would to contribute in python

**Comment by gh4abhi** [comment]
Please assign this task to me I have not yet added the code of this problem.

**Comment by Nivedita967** [comment]
Open for Java.

**Comment by Nivedita967** [comment]
@Abhichal18 Are you working on this ?
