### ISSUE TITLE
Watermelon

### ISSUE THREAD

**Issue by gh4abhi** [Nivedita967/Data-Structure-and-Algorithms#161]
Problem Link - https://www.codechef.com/problems/WATMELON

**Comment by gh4abhi** [comment]
Please verify the problem and assign it to me. I will do it in c++.

**Comment by TechSpiritSS** [comment]
I can do this in C

**Comment by Nivedita967** [comment]
@gh4abhi Complete your all previous tasks.

**Comment by TechSpiritSS** [comment]
I first write the code and after that ask for contribution. I'm only required to make PR for these issue.

**Comment by Abhichal18** [comment]
@Nivedita967 i would like to contribute in python

**Comment by gh4abhi** [comment]
@Nivedita967 I have completed my previous tasks now please assign this task to me.

**Comment by Nivedita967** [comment]
Open for Java.

**Comment by Nivedita967** [comment]
@Abhichal18 Are you working on this ?

**Comment by Abhichal18** [comment]
> @Abhichal18 Are you working on this ?

yeah i am
