### ISSUE TITLE
Sherlock and His Device

### ISSUE THREAD

**Issue by vivek286** [Nivedita967/Data-Structure-and-Algorithms#165]
https://www.codechef.com/problems/MISSME
please assign it to  me  would like to  do it in C++

**Comment by Nivedita967** [comment]
@vivek286 Do join the Gitter Channel :)

**Comment by Abhichal18** [comment]
@Nivedita967 i would like to contribute in python

**Comment by Nivedita967** [comment]
@Abhichal18 Clear all previous works, then comment.

**Comment by Nivedita967** [comment]
@vivek286 Are you working on this ?
