### ISSUE TITLE
Birthday Cake Candles

### ISSUE THREAD

**Issue by jasmine1601** [Nivedita967/Data-Structure-and-Algorithms#168]
Problem link : https://www.hackerrank.com/challenges/birthday-cake-candles/problem
I will solve it in Java.

**Comment by TechSpiritSS** [comment]
I can do this in C

**Comment by Abhichal18** [comment]
@Nivedita967 i would like to contribute in python

**Comment by Nivedita967** [comment]
Open for C++

**Comment by Nivedita967** [comment]
@weirdrag08

**Comment by weirdrag08** [comment]
> Open for C++

Please assign me this question in C++

**Comment by Nivedita967** [comment]
@Abhichal18 Are you working on this ?
