### ISSUE TITLE
Playing With Characters

### ISSUE THREAD

**Issue by gh4abhi** [Nivedita967/Data-Structure-and-Algorithms#170]
Problem Link - https://www.hackerrank.com/challenges/playing-with-characters/problem

**Comment by gh4abhi** [comment]
Please verify the problem and assign it to me. I will do it in C.

**Comment by Nivedita967** [comment]
Open for C++ ,Python and Java

**Comment by ishikabansal04** [comment]
> Open for C++ ,Python and Java

I can do this in C++. Please assign me

**Comment by Nivedita967** [comment]
Sure @ishikabansal04 Go for it :)
