### ISSUE TITLE
Sum and Difference of Two Numbers

### ISSUE THREAD

**Issue by gh4abhi** [Nivedita967/Data-Structure-and-Algorithms#171]
Problem Link - https://www.hackerrank.com/challenges/sum-numbers-c/problem

**Comment by gh4abhi** [comment]
Please verify the problem and assign it to me. I will do it in C.

**Comment by ItsmeSauravSonu** [comment]
I will do it in java

**Comment by Abhichal18** [comment]
@Nivedita967 i would like to contribute in python

**Comment by Nivedita967** [comment]
@Abhichal18 Are you working?

**Comment by jayantjethi** [comment]
I would like to code on this issue in C++.Kindly Assign me

**Comment by Jindalh2** [comment]
I can code it in C++

**Comment by Nivedita967** [comment]
@jayantjethi Go for it :)

**Comment by deephunt3r** [comment]
@Nivedita967 can I solve in python?
no one has done using py
