### ISSUE TITLE
Symmetric tree

### ISSUE THREAD

**Issue by ItsmeSauravSonu** [Nivedita967/Data-Structure-and-Algorithms#177]
https://leetcode.com/problems/symmetric-tree/ 
please verify the question

I can do it without recursion in iterative way.

**Comment by Nivedita967** [comment]
In which language you want to code ?

**Comment by ItsmeSauravSonu** [comment]
Java

**Comment by Nivedita967** [comment]
Okay, Go for it. You can add or replace the code in the folder.

**Comment by Nivedita967** [comment]
Open for C, C++, Python.
@weirdrag08
