### ISSUE TITLE
Chef and division 

### ISSUE THREAD

**Issue by kanak22** [Nivedita967/Data-Structure-and-Algorithms#178]
problem : https://www.codechef.com/JAN21C/problems/DIVTHREE

I can do this in C++ kindly assign it to me .

**Comment by TechSpiritSS** [comment]
I can do this in C

**Comment by Nivedita967** [comment]
@TechSpiritSS Complete all previous works :)

**Comment by Abhichal18** [comment]
@Nivedita967  i would like to contribute in python

**Comment by ItsmeSauravSonu** [comment]
@Nivedita967 I would like to contribute in java

**Comment by TechSpiritSS** [comment]
> @TechSpiritSS Complete all previous works :)

Done ; )

**Comment by kavania2002** [comment]
isn't this same as #156 ?

**Comment by TechSpiritSS** [comment]
Yes, this is the same question but from different link

**Comment by Nivedita967** [comment]
Yes, you are right. This issue is already open and happily @kanak22 wants to contribute in C++ and that issue is also open for C++ :)
@kanak22 please comment on the issue #156

**Comment by kanak22** [comment]
I commented 😊
