### ISSUE TITLE
Team Name

### ISSUE THREAD

**Issue by gh4abhi** [Nivedita967/Data-Structure-and-Algorithms#184]
Problem Link  - https://www.codechef.com/FEB21B/problems/TEAMNAME
Please verify the problem and assign it to me. I will do it in C++.

**Comment by gh4abhi** [comment]
Please assign this to me.

**Comment by Amit366** [comment]
@Nivedita967 can I implement using Java??

**Comment by Nivedita967** [comment]
Sure @Amit366 Go for it.

**Comment by Amit366** [comment]
@Nivedita967 when I am cloning this repo it is showing an error

error: invalid path 'Hackerrank/Snakes And Ladders /Snakes_and_ladders.java'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

**Comment by Nivedita967** [comment]
> @Nivedita967 when I am cloning this repo it is showing an error
> 
> error: invalid path 'Hackerrank/Snakes And Ladders /Snakes_and_ladders.java'
> fatal: unable to checkout working tree
> warning: Clone succeeded, but checkout failed.
> You can inspect what was checked out with 'git status'
> and retry with 'git restore --source=HEAD :/'

Is it okay now ?

**Comment by Amit366** [comment]
Yes

**Comment by Jatin2020-24** [comment]
@Nivedita967  can I code it using python.

**Comment by Nivedita967** [comment]
Sure @Jatin2020-24 Go for it.

**Comment by Nivedita967** [comment]
@Jatin2020-24 Are you working on this ?
