### ISSUE TITLE
Reverse Integer

### ISSUE THREAD

**Issue by muthuannamalai12** [Nivedita967/Data-Structure-and-Algorithms#197]
Problem Link : https://leetcode.com/problems/reverse-integer/ I would like to solve it in java as a part of Cross-Woc. Kindly assign it to me

**Comment by TechSpiritSS** [comment]
I can do this in C and C++

**Comment by Nivedita967** [comment]
Open for Python.

**Comment by muthuannamalai12** [comment]
> Open for Python.

@Nivedita967 Can I do it as a part of Cross-Woc

**Comment by Nivedita967** [comment]
Sure @muthuannamalai12 .
