### ISSUE TITLE
Valid Perfect Square

### ISSUE THREAD

**Issue by muthuannamalai12** [Nivedita967/Data-Structure-and-Algorithms#200]
Problem Link: https://leetcode.com/problems/valid-perfect-square/. I would love to work on this problem as a part of Cross-Woc in the python language. Kindly assign me this issue.

**Comment by ItsmeSauravSonu** [comment]
I would like to contribute in java

**Comment by TechSpiritSS** [comment]
I can do this in C and C++

**Comment by muthuannamalai12** [comment]
@Nivedita967 I have to do it in python can you reopen the issue.
