### ISSUE TITLE
Enormous Input test on codechef

### ISSUE THREAD

**Issue by kmryashasvi** [Nivedita967/Data-Structure-and-Algorithms#206]
i will be working on the c and c++ code of [this](https://www.codechef.com/problems/INTEST) Problem

**Comment by Nivedita967** [comment]
Java is done.

**Comment by Jatin2020-24** [comment]
I can do it for python, please assign it to me.

**Comment by Nivedita967** [comment]
Sure @Jatin2020-24 Go for it :)

**Comment by Jatin2020-24** [comment]
#https://github.com/Nivedita967/Data-Structure-and-Algorithms/issues/206#issuecomment-780656440
Create Enormous Input Test.py https://github.com/Nivedita967/Data-Structure-and-Algorithms/pull/279/commits/3b29995f9af6e0b3170044138d644e9a81f57a37
