### ISSUE TITLE
Maximum Number of Achievable Transfer Requests-Leetcode 

### ISSUE THREAD

**Issue by Akash20x** [Nivedita967/Data-Structure-and-Algorithms#210]
Problem Link:
https://leetcode.com/problems/maximum-number-of-achievable-transfer-requests/description/
Please verify this problem and assign it to me

I will solve this problem in python

**Comment by Nivedita967** [comment]
Open for C, C++ and Java

**Comment by kanak22** [comment]
I would like to do this in c++
