### ISSUE TITLE
Merge k Sorted Lists on Leetcode 

### ISSUE THREAD

**Issue by Akash20x** [Nivedita967/Data-Structure-and-Algorithms#213]
Problem Link:
https://leetcode.com/problems/merge-k-sorted-lists/description/

Please verify this problem and assign it to me and I solve it in python

Problem Number 23 on Leetcode

**Comment by ItsmeSauravSonu** [comment]
I will solve it in java

**Comment by ishikabansal04** [comment]
Please assign me this task. I want to do in C++.

**Comment by weirdrag08** [comment]
My preferred language is C++. Please assign me the task so that I can solve using C++.

**Comment by Nivedita967** [comment]
@Akash20x You have given the link of solution lol.

**Comment by Akash20x** [comment]
So sorry, I will correct the link

**Comment by Akash20x** [comment]
Please review this pull request
