### ISSUE TITLE
2D Array - DS

### ISSUE THREAD

**Issue by Nivedita967** [Nivedita967/Data-Structure-and-Algorithms#22]
Problem Link- https://www.hackerrank.com/challenges/2d-array/problem from HackerRank.
Add code in different languages.

**Comment by Mahindra-7** [comment]
@Nivedita967 as i am participant of crossWoc please assign it to me

**Comment by Nivedita967** [comment]
@Mahindra-7 in which language you want to code?

**Comment by Archna29** [comment]
@Nivedita967 I am a participant of crosswoc i want to do this issue in java language

**Comment by Nivedita967** [comment]
@Archna29 Sure, Go for it. Join the Gitter channel :)

**Comment by Mahindra-7** [comment]
@Nivedita967  i can solve using c++ as well as java

**Comment by Nivedita967** [comment]
@Mahindra-7 Please add code in C++.

**Comment by JASKAMAL22** [comment]
I would like to work on it using python. Can you please assign it to me!!

**Comment by Abhichal18** [comment]
I am a Crosswoc participant, i would like to add code in python. Can you please assign it to me?

**Comment by Nivedita967** [comment]
@JASKAMAL22 Go for it.

**Comment by Nivedita967** [comment]
@Abhichal18 Look for another issue and Join Gitter channel -https://gitter.im/Data-Structure-and-Algorithms-Nivedita/community

**Comment by Nivedita967** [comment]
@TechSpiritSS add code in C.

**Comment by TechSpiritSS** [comment]
Sure, I'm ready to code it in C : )

**Comment by Nivedita967** [comment]
@Mahindra-7 and @JASKAMAL22 Are you working on this ?

**Comment by Mahindra-7** [comment]
@Nivedita967  i m working on it

**Comment by Mahindra-7** [comment]
@Nivedita967 in which language do you want me to do ?

**Comment by Nivedita967** [comment]
> @Nivedita967 in which language do you want me to do ?

Java

**Comment by JASKAMAL22** [comment]
Yes @Nivedita967. Sorry, it's my first contribution

**Comment by JASKAMAL22** [comment]
I have to code in python!!?

**Comment by Nivedita967** [comment]
> I have to code in python!!?

Yes :)

**Comment by JASKAMAL22** [comment]
But @Mahindra-7 upload .py file
