### ISSUE TITLE
Conditional Statements in C

### ISSUE THREAD

**Issue by gh4abhi** [Nivedita967/Data-Structure-and-Algorithms#229]
Problem Link - https://www.hackerrank.com/challenges/conditional-statements-in-c/problem

**Comment by gh4abhi** [comment]
Please verify the problem and assign it to me. I will do it in C.

**Comment by deeqakkk** [comment]
do assign this to me, i can solve this.

**Comment by Nivedita967** [comment]
@gh4abhi Are you working on this and others issues?
