### ISSUE TITLE
Sum of Digits of a Five Digit Number

### ISSUE THREAD

**Issue by gh4abhi** [Nivedita967/Data-Structure-and-Algorithms#231]
### Problem Link 
https://www.hackerrank.com/challenges/sum-of-digits-of-a-five-digit-number/problem

### Coding platform
Hackerrank

### Programming language

- [x] C
- [x] C++
- [ ] Java
- [x] Python

**Comment by gh4abhi** [comment]
Please verify the problem and assign it to me I will do it in C.

**Comment by kmryashasvi** [comment]
I will do it in C++

**Comment by stlyash** [comment]
I would like to do it in C and Python. 
Please assign me.
