### ISSUE TITLE
Chef Likes Good Sequences

### ISSUE THREAD

**Issue by gh4abhi** [Nivedita967/Data-Structure-and-Algorithms#232]
Problem Link - https://www.codechef.com/problems/GSUB

**Comment by gh4abhi** [comment]
Please verify the problem and assign it to me I will do it in C++.

**Comment by TechSpiritSS** [comment]
I am partially able to do this getting TLE of 0.01 seconds in some test cases. C language

**Comment by Nivedita967** [comment]
Try to optimize your code :)
