### ISSUE TITLE
Issue Template

### ISSUE THREAD

**Issue by Nivedita967** [Nivedita967/Data-Structure-and-Algorithms#24]
Issue Template should contain Problem link along with Coding Platform name.

**Comment by Sloth-Panda** [comment]
plz assign to me

**Comment by 96RadhikaJadhav** [comment]
@Nivedita967 I'm a crossWoc participant and would like to work on this issue.

**Comment by Nivedita967** [comment]
@96RadhikaJadhav Go for it.
