### ISSUE TITLE
Is Subsequence

### ISSUE THREAD

**Issue by greenblade29** [Nivedita967/Data-Structure-and-Algorithms#241]
Is your feature request related to a problem? Please describe.
It is a problem on Leetcode which can be solved using dynamic programming.

Describe the solution you'd like
I would like to solve it in Java

Additional context
Problem Link: https://leetcode.com/problems/is-subsequence/

Programming Language:
- [ ] C
- [x] C++
- [x] Java
- [ ] Python

**Comment by ishikabansal04** [comment]
I want to do this question in C++ if available.
