### ISSUE TITLE
Helping chef on codechef

### ISSUE THREAD

**Issue by kmryashasvi** [Nivedita967/Data-Structure-and-Algorithms#248]
### Problem Link 
https://www.codechef.com/problems/FLOW008

### Coding platform
Codechef

### Programming language

- [x] C
- [x] C++
- [x] Java
- [x] Python

**Comment by kanak22** [comment]
can I contribute its solution in c++?

**Comment by Nivedita967** [comment]
@kmryashasvi Do not check checkboxes. I will check them when completed.

**Comment by kmryashasvi** [comment]
> @kmryashasvi Do not check checkboxes. I will check them when completed.
> In which language you want to code?

I have unchecked all checkboxes,
Please assign me for C and C++

**Comment by TechSpiritSS** [comment]
Let me do this in C and @kmryashasvi in C++

**Comment by kmryashasvi** [comment]
I have a question.
When more than one person are working an issue, Will the scores be divided, or they will be same?

**Comment by TechSpiritSS** [comment]
We are working on different languages so I think that is divided accordingly

**Comment by kmryashasvi** [comment]
let @Nivedita967  answer @TechSpiritSS

**Comment by Nivedita967** [comment]
> I have a question.
> When more than one person are working an issue, Will the scores be divided, or they will be same?

will remain same as far I know.

**Comment by Nivedita967** [comment]
@kmryashasvi -> C
@kanak22 -> C++
@TechSpiritSS You are late

**Comment by Nivedita967** [comment]
Open for Java and Python

**Comment by TechSpiritSS** [comment]
> @kmryashasvi -> C
> @kanak22 -> C++
> @TechSpiritSS You are late

Well I asked first here but it's okay I am doing nptel assignment today 😂😂

**Comment by kmryashasvi** [comment]
> @kmryashasvi -> C
> @kanak22 -> C++
> @TechSpiritSS You are late

Sorry to say,
not we, You are late,
you have not assigned us,
what should have we done?

**Comment by ishikabansal04** [comment]
> Open for Java and Python

Hi @Nivedita967  Is it still open in Java? I would like to solve this .

**Comment by Nivedita967** [comment]
Sure @ishikabansal04 go for it.

**Comment by Akash20x** [comment]
Please assign me this issue, I will solve it in python

**Comment by Nivedita967** [comment]
@Akash20x go for it.
