### ISSUE TITLE
XOR Operation in an Array

### ISSUE THREAD

**Issue by Nivedita967** [Nivedita967/Data-Structure-and-Algorithms#25]
Problem Link- https://leetcode.com/problems/xor-operation-in-an-array from Leetcode.

**Comment by Mahindra-7** [comment]
@Nivedita967 as i am participant of crossWoc please assign it to me

**Comment by hardikchitkara** [comment]
@Nivedita967 i can provide you solution in c++ or java for sure.

**Comment by TechSpiritSS** [comment]
I am new to coding and I feel confident to be able to solve this issue. I am also in DS disocrd group of CrossWoC

**Comment by TechSpiritSS** [comment]
@Nivedita967  I can code in C and C++

**Comment by Nivedita967** [comment]
@TechSpiritSS Please join Gitter channel- https://gitter.im/Data-Structure-and-Algorithms-Nivedita/community
And C++ is already taken. You can go with C :)

**Comment by Nivedita967** [comment]
@Mahindra-7 -> Java
@hardikchitkara -> C++
@TechSpiritSS -> C
Open for Python.

**Comment by JASKAMAL22** [comment]
hello @Nivedita967 , I would be happy to work on it using python. Can you please assign it to me!!

**Comment by Nivedita967** [comment]
@JASKAMAL22 Sure, Go for it.

**Comment by Nivedita967** [comment]
@JASKAMAL22 Are you working in this ?

**Comment by JASKAMAL22** [comment]
Yes @Nivedita967. It's my first contribution so little challenging tasks like commit and PR. :)

**Comment by Nivedita967** [comment]
> Yes @Nivedita967. It's my first contribution so little challenging tasks like commit and PR. :)

Give it a try. I will help you further :)
