### ISSUE TITLE
Maximum Subarray sum problem 

### ISSUE THREAD

**Issue by kanak22** [Nivedita967/Data-Structure-and-Algorithms#250]
### Problem Link 
https://www.hackerrank.com/challenges/maximum-subarray-sum/problem

### Coding platform
hackerrank

### Programming language: 

- [ ] C
- [x ] C++
- [x] Java
- [ ] Python

**Comment by kanak22** [comment]
@Nivedita967  I would like to work on this in c++. kindly assign it to me

**Comment by Abhinav0909** [comment]
Hi, @Nivedita967  I would like to work on this issue in java.

**Comment by Nivedita967** [comment]
Sure @Abhinav0909 Go for it :)

**Comment by Abhichal18** [comment]
@Nivedita967 i would like to contribute in python

**Comment by Nivedita967** [comment]
@Abhichal18 Go for it :)

**Comment by Nivedita967** [comment]
@Abhichal18 @Abhinav0909 Are you working on this ?

**Comment by kiruba-r11** [comment]
@Nivedita967 can I work on this for C and Python

**Comment by Nivedita967** [comment]
@kiruba-r11 Sure go for it :)

**Comment by Nivedita967** [comment]
@kiruba-r11 Are you working on this?

**Comment by kiruba-r11** [comment]
@Nivedita967 yes

**Comment by Kpraful** [comment]
@Nivedita967 It is good question, may I give it a try in python ?

**Comment by Amit366** [comment]
@Nivedita967 can I implement using Java?

**Comment by Nivedita967** [comment]
Sure @Kpraful @Amit366 Go for it.

**Comment by Amit366** [comment]
@Nivedita967  I am getting this error:

fatal: will not add file alias 'Leetcode/Minimum Cost For Tickets/Minimum_cost_for_tickets.cpp' ('Leetcode/Minimum cost for tickets/Minimum_cost_for_tickets.cpp' already exists in index)

**Comment by Nivedita967** [comment]
> @Nivedita967 I am getting this error:
> 
> fatal: will not add file alias 'Leetcode/Minimum Cost For Tickets/Minimum_cost_for_tickets.cpp' ('Leetcode/Minimum cost for tickets/Minimum_cost_for_tickets.cpp' already exists in index)

Is this resolved or you are still stuck?

**Comment by Amit366** [comment]
Resolved and I have sent the PR

**Comment by Amit366** [comment]
@Nivedita967 is this issue open??

**Comment by Nivedita967** [comment]
> @Nivedita967 is this issue open??

Yes

**Comment by Nivedita967** [comment]
> @Nivedita967 It is good question, may I give it a try in python ?

@Kpraful Are you working?

**Comment by Amit366** [comment]
Which language is open??

**Comment by Amit366** [comment]
@Nivedita967 i will work using python

**Comment by Kpraful** [comment]
> > @Nivedita967 It is good question, may I give it a try in python ?
> 
> @Kpraful Are you working?

Yes I am, Sorry It is taking long. I was busy with some personal issue. I will try to finish it ASAP.

**Comment by pri1311** [comment]
is this still open for any language?

**Comment by Nivedita967** [comment]
> is this still open for any language?

Yes for C only

**Comment by Kpraful** [comment]
@Nivedita967 There are 2 folder in this repo for the same name, I have added in the folder which have max file, please let me know if I have to change it.
