### ISSUE TITLE
Roads And Libraries

### ISSUE THREAD

**Issue by weirdrag08** [Nivedita967/Data-Structure-and-Algorithms#254]
### Problem Link 
https://www.hackerrank.com/challenges/torque-and-development/problem

### Coding platform
Hackerrank

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by weirdrag08** [comment]
Please review this problem and assign me this issue in C++.

**Comment by Nivedita967** [comment]
@weirdrag08 Go for it :)
