### ISSUE TITLE
Subsets

### ISSUE THREAD

**Issue by Nivedita967** [Nivedita967/Data-Structure-and-Algorithms#26]
Problem link- https://leetcode.com/problems/subsets/ from Leetcode

**Comment by Mahindra-7** [comment]
@Nivedita967 as i am participant of crossWoc please assign it to me

**Comment by hardikchitkara** [comment]
i am participant of crossWoc. I will provide the solution for the same in java or c++.

**Comment by greenblade29** [comment]
Can I work on this issue? I am a participant of CrossWoc

**Comment by Nivedita967** [comment]
@greenblade29 Go for it. Please join Gitter Channel.

**Comment by saksham-s1ngh** [comment]
Can I work on this issue in Python, for participation in CrossWoc?

**Comment by Nivedita967** [comment]
Java is done.

**Comment by Nivedita967** [comment]
@saksham-s1ngh Sure, go for it.
@hardikchitkara -> C++
Open for C.

**Comment by Nivedita967** [comment]
@TechSpiritSS This issue is also open for C.

**Comment by TechSpiritSS** [comment]
I am unable to solve this code, probably someone else will be able to do this

**Comment by Nivedita967** [comment]
> I am unable to solve this code, probably someone else will be able to do this

Okay, No problem.

**Comment by Nivedita967** [comment]
@hardikchitkara Are you working on this ?
