### ISSUE TITLE
Search Insert Position

### ISSUE THREAD

**Issue by muthuannamalai12** [Nivedita967/Data-Structure-and-Algorithms#266]
### Problem Link 
Mention the problem on which you want to work on
https://leetcode.com/problems/search-insert-position/
### Coding platform
Mention the coding platform from where you have picked the problem
LeetCode
### Programming language

- [x] C
- [x] C++
- [x] Java
- [ ] Python

**Comment by muthuannamalai12** [comment]
I would love to work on this issue as a part of Cross-Woc in java

**Comment by kanak22** [comment]
can I do it in c++?

**Comment by TechSpiritSS** [comment]
I can do this in C
