### ISSUE TITLE
Climbing Stairs

### ISSUE THREAD

**Issue by greenblade29** [Nivedita967/Data-Structure-and-Algorithms#268]
Problem Link 
https://leetcode.com/problems/climbing-stairs/

Coding platform
Leetcode

Programming language

- [x] C
- [x] C++
- [x] Java
- [ ] Python

I want to solve this problem in C++ and Java

**Comment by Abhinav0909** [comment]
Hi, @greenblade29  I would like to solve this issue in java.

**Comment by greenblade29** [comment]
> Hi, @greenblade29 I would like to solve this issue in java.

OK then, you can get it assigned and use Java. I will code in C++ then

**Comment by weirdrag08** [comment]
Please assign me this problem in C++

**Comment by Nivedita967** [comment]
@weirdrag08 Try to add new issues

**Comment by TechSpiritSS** [comment]
I can do this in C , I got 100% faster for this code

**Comment by Nivedita967** [comment]
@Abhinav0909 Check your PR.

**Comment by Abhinav0909** [comment]
@Nivedita967 I have updated it. Please do have a check.
