### ISSUE TITLE
Long Factorial

### ISSUE THREAD

**Issue by deephunt3r** [Nivedita967/Data-Structure-and-Algorithms#27]
Problem link  https://www.hackerrank.com/challenges/extra-long-factorials/problem from Hackerrank using Arrays.

**Comment by deephunt3r** [comment]
@Nivedita967 can you please verify and assign it to me under CrossWoc

**Comment by Nivedita967** [comment]
@deephunt3r Go for it.

**Comment by deephunt3r** [comment]
> @deephunt3r Go for it. Please join Gitter channel.

sure @Nivedita967

**Comment by hardikchitkara** [comment]
i can provide solution of this in all three languages. Please give me a chance.

**Comment by deephunt3r** [comment]
@hardikchitkara if @Nivedita967 accepted your request you can contribute in java and python. I have no issues.

**Comment by Nivedita967** [comment]
@hardikchitkara Java and Python.

**Comment by Manikant25** [comment]
Can I contribute in C++?

**Comment by Nivedita967** [comment]
@deephunt3r In which language are you working ?

**Comment by deephunt3r** [comment]
@Nivedita967 I will contribute in C. you can assign @Manikant25 in CPP.
open source is for everyone

**Comment by Nivedita967** [comment]
> @Nivedita967 I will contribute in C. you can assign @Manikant25 in CPP.
> open source is for everyone

Sure.

**Comment by Nivedita967** [comment]
@Manikant25 Go for it.

**Comment by Archna29** [comment]
Can i work on this issue in java language

**Comment by Nivedita967** [comment]
@Archna29 Java is taken.

**Comment by Nivedita967** [comment]
@Manikant25 Are you working on this? 
@hardikchitkara Are you going to add code for python also?

**Comment by Manikant25** [comment]
@Nivedita967  Yes I am working. I will send PR tonight.
