### ISSUE TITLE
Dijkstra : Shortest Reach 2

### ISSUE THREAD

**Issue by ishikabansal04** [Nivedita967/Data-Structure-and-Algorithms#280]
### Problem Link 
https://www.hackerrank.com/challenges/dijkstrashortreach/problem

### Coding platform
Hackerrank

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [ ] Python

**Comment by ishikabansal04** [comment]
Please review this problem and assign me in C++.

**Comment by gopichandpuli9** [comment]
I'll implement this in python. Assign it to me.

**Comment by Nivedita967** [comment]
@gopichandpuli9 Are you working on this ?

**Comment by arbazalam01** [comment]
can i do it in python

**Comment by Nivedita967** [comment]
Sure @arbazalam01 Go for it :)

**Comment by Amit366** [comment]
@Nivedita967 can I do in Java??

**Comment by Nivedita967** [comment]
Sure @Amit366 Go for it.
