### ISSUE TITLE
Journey To The Moon

### ISSUE THREAD

**Issue by weirdrag08** [Nivedita967/Data-Structure-and-Algorithms#281]
### Problem Link 
https://www.hackerrank.com/challenges/journey-to-the-moon/problem

### Coding platform
Hackerrank

### Programming language

- [x] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by weirdrag08** [comment]
@Nivedita967 Please check this issue and assign me in C++.

**Comment by kanak22** [comment]
I would like to do this in C.
