### ISSUE TITLE
Adding Sparse matrix problem solution from leetcode

### ISSUE THREAD

**Issue by Spidy-Coder** [Nivedita967/Data-Structure-and-Algorithms#286]
Adding a new file of sparse matrix in c++ language

**Comment by Spidy-Coder** [comment]
Is it ok nivedita? Please reply for the same

**Comment by deeqakkk** [comment]
> Adding a new file of sparse matrix in c++ language

also provide link to that particular problem.

**Comment by Nivedita967** [comment]
Please give the link of the problem.
