### ISSUE TITLE
Count Sorted Vowel Strings

### ISSUE THREAD

**Issue by greenblade29** [Nivedita967/Data-Structure-and-Algorithms#289]
Problem Link 
https://leetcode.com/problems/count-sorted-vowel-strings/

Coding platform
Leetcode

Programming language

- [ ] C
- [x] C++
- [x] Java
- [ ] Python

Additional context (OPTIONAL)
I want to solve it in C++ and Java

**Comment by Nivedita967** [comment]
Work on one language first.

**Comment by Mahindra-7** [comment]
@Nivedita967  can you please assign this problem

**Comment by kanak22** [comment]
I would like to work on this in c++

**Comment by Nivedita967** [comment]
> @Nivedita967 can you please assign this problem

Do mention language in which you want to code in the comment.

**Comment by Mahindra-7** [comment]
@Nivedita967 i would like to do in java

**Comment by Nivedita967** [comment]
> @Nivedita967 i would like to do in java

@Mahindra-7 Java is already done.
