### ISSUE TITLE
Matrix Block Sum

### ISSUE THREAD

**Issue by greenblade29** [Nivedita967/Data-Structure-and-Algorithms#290]
Problem Link 
https://leetcode.com/problems/matrix-block-sum/

Coding platform
Leetcode

Programming language

- [ ] C
- [x] C++
- [x] Java
- [ ] Python

Additional context (OPTIONAL)
I want to solve it in C++ and Java

**Comment by Nivedita967** [comment]
Work on one language at a time for any issue.
You can work on other after completing one.

**Comment by kanak22** [comment]
can I do this in c++?

**Comment by Nivedita967** [comment]
Sure @kanak22 go for it :)
