### ISSUE TITLE
Length of Last Word

### ISSUE THREAD

**Issue by muthuannamalai12** [Nivedita967/Data-Structure-and-Algorithms#292]
### Problem Link 
Mention the problem on which you want to work on
https://leetcode.com/problems/length-of-last-word/
### Coding platform
Mention the coding platform from where you have picked the problem
LeetCode
### Programming language

- [ ] C
- [x] C++
- [x] Java
- [ ] Python

**Comment by muthuannamalai12** [comment]
I would love to work on this in java. Kindly assign me as a part of Cross-Woc.

**Comment by weirdrag08** [comment]
Please assign me this problem in C++

**Comment by kiruba-r11** [comment]
@Nivedita967 Can I work on this issue in Python and C

**Comment by Nivedita967** [comment]
Sure @kiruba-r11 Go for it :)
