### ISSUE TITLE
Valid Anagram

### ISSUE THREAD

**Issue by muthuannamalai12** [Nivedita967/Data-Structure-and-Algorithms#293]
### Problem Link 
Mention the problem on which you want to work on
https://leetcode.com/problems/valid-anagram/
### Coding platform
Mention the coding platform from where you have picked the problem
LeetCode
### Programming language

- [x] C
- [x] C++
- [x] Java
- [ ] Python

**Comment by weirdrag08** [comment]
Please assign me this problem in C++

**Comment by muthuannamalai12** [comment]
I would love to work on it java as a part of Cross-Woc

**Comment by TechSpiritSS** [comment]
I can do this in C

**Comment by sameeksha1317** [comment]
hey @Nivedita967! i would like to code it in java.Can I?

**Comment by Nivedita967** [comment]
@sameeksha1317 Look the checkboxes in each issues. If checkbox is checked for particular language which means that language is already contributed for this issue.

**Comment by sameeksha1317** [comment]
@Nivedita967 okay,
