### ISSUE TITLE
finding all substrings of a string

### ISSUE THREAD

**Issue by Sloth-Panda** [Nivedita967/Data-Structure-and-Algorithms#302]
### Problem Link 
Mention the problem on which you want to work on
https://www.geeksforgeeks.org/program-print-substrings-given-string/
### Coding platform
Mention the coding platform from where you have picked the problem
GFG
### Programming language

- [ ] C
- [x] C++
- [x] Java
- [ ] Python

**Comment by Sloth-Panda** [comment]
@Nivedita967 would like to work on this under cwoc. Please assign me

**Comment by Nivedita967** [comment]
@Sloth-Panda You have some incomplete works. I have tagged you and asked about it but you didn't answered.
So, first of all, clear all the works assigned to you.
Also try to add the problem from the existing coding platform in the project.

**Comment by Sloth-Panda** [comment]
@Nivedita967 I actually I am feeling a litlle bit uncomfortable with that issue you can unassign me or close that one as per ur choice. And assign me others issue that I have raised will like to do that and I have updated the link too

**Comment by Nivedita967** [comment]
@Sloth-Panda Add an additional folder for GFG the add your code the respective folder.

**Comment by Sloth-Panda** [comment]
@Nivedita967 yes will be making the folder and the prs soon

**Comment by jayantjethi** [comment]
I would like to code on this issue in C++.Kindly Assign me

**Comment by Nivedita967** [comment]
Sure @jayantjethi Go for it :)

**Comment by jayantjethi** [comment]
Mam Please check my this file as well I have them All in the same PR
