### ISSUE TITLE
Finding the number occuring odd number of times in an array

### ISSUE THREAD

**Issue by Sloth-Panda** [Nivedita967/Data-Structure-and-Algorithms#303]
### Problem Link 
Mention the problem on which you want to work on
https://www.geeksforgeeks.org/find-the-number-occurring-odd-number-of-times/
### Coding platform
Mention the coding platform from where you have picked the problem
GFG
### Programming language

- [ ] C
- [x] C++
- [x] Java
- [x] Python

**Comment by Sloth-Panda** [comment]
@Nivedita967 would like to work on it using java

**Comment by JASKAMAL22** [comment]
Kindly, Please assign it to me . I would like to work in python!!

**Comment by kanak22** [comment]
I would like to work on this in C++

**Comment by Nivedita967** [comment]
@JASKAMAL22 @kanak22 Go for it :)
