### ISSUE TITLE
Finding the local minima in an array

### ISSUE THREAD

**Issue by Sloth-Panda** [Nivedita967/Data-Structure-and-Algorithms#304]
### Problem Link 
Mention the problem on which you want to work on
https://www.geeksforgeeks.org/find-local-minima-array/
### Coding platform
Mention the coding platform from where you have picked the problem
GFG
### Programming language

- [x] C
- [x] C++
- [x] Java
- [ ] Python

**Comment by Sloth-Panda** [comment]
@Nivedita967 would like to work this using Java

**Comment by kanak22** [comment]
I would like to work on this in c++

**Comment by Nivedita967** [comment]
@Sloth-Panda @kanak22 Add your code by creating an additional folder for GFG.

**Comment by ItsmeSauravSonu** [comment]
I want to contribute in java

**Comment by Nivedita967** [comment]
@ItsmeSauravSonu Java is not open for this issue.

**Comment by ishikabansal04** [comment]
Is this available in C? Please assign me if open.

**Comment by Nivedita967** [comment]
Sure @ishikabansal04
