### ISSUE TITLE
Find leaders in an array

### ISSUE THREAD

**Issue by Sloth-Panda** [Nivedita967/Data-Structure-and-Algorithms#305]
### Problem Link 
Mention the problem on which you want to work on
https://www.geeksforgeeks.org/leaders-in-an-array/
### Coding platform
Mention the coding platform from where you have picked the problem

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [x] Python

**Comment by Sloth-Panda** [comment]
Would like to work on this using java

**Comment by kanak22** [comment]
I would like to work on this in c++

**Comment by JASKAMAL22** [comment]
Hey @Nivedita967 ,I would like to work in python. :)

**Comment by Nivedita967** [comment]
@JASKAMAL22 Go for it :)

**Comment by sameeksha1317** [comment]
hey @Nivedita967! I would like to code it in java, can I?

**Comment by Nivedita967** [comment]
@sameeksha1317 Java is already done for this issue, please look for other issues.

**Comment by sameeksha1317** [comment]
@Nivedita967 okay
