### ISSUE TITLE
Minimum Path Sum

### ISSUE THREAD

**Issue by ishikabansal04** [Nivedita967/Data-Structure-and-Algorithms#308]
### Problem Link 
https://leetcode.com/problems/minimum-path-sum/

### Coding platform
Leetcode

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [ ] Python

**Comment by ishikabansal04** [comment]
Please review this problem issue and assign me in C++.

**Comment by ItsmeSauravSonu** [comment]
I want to contribute using Java

**Comment by jayantjethi** [comment]
I would like to code on this issue in C++.Kindly Assign me

**Comment by Nivedita967** [comment]
Sure @jayantjethi Go for it :)

**Comment by jayantjethi** [comment]
Mam I Have Solved This Issue in the same PR with Airplane Seat Assignment Probability.
