### ISSUE TITLE
Path with Maximum Gold

### ISSUE THREAD

**Issue by weirdrag08** [Nivedita967/Data-Structure-and-Algorithms#309]
### Problem Link 
https://leetcode.com/problems/path-with-maximum-gold/

### Coding platform
Leetcode

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [x] Python

**Comment by weirdrag08** [comment]
Please review this problem and assign me this in C++

**Comment by ItsmeSauravSonu** [comment]
I want to contribute in java language, please assign to me

**Comment by Nivedita967** [comment]
@weirdrag08 @ItsmeSauravSonu Working on this ?

**Comment by ItsmeSauravSonu** [comment]
Yes

**Comment by weirdrag08** [comment]
> @weirdrag08 @ItsmeSauravSonu Working on this ?

Yeah, I am working on it. Please give me some time :-)

**Comment by Nivedita967** [comment]
@ItsmeSauravSonu @weirdrag08 ??

**Comment by weirdrag08** [comment]
> @ItsmeSauravSonu @weirdrag08 ??

Just give me 2 more days, I will solve it for sure :-)

**Comment by weirdrag08** [comment]
> @ItsmeSauravSonu @weirdrag08 ??

Please give me one more day, I will solve it for sure :-)

**Comment by ItsmeSauravSonu** [comment]
I will do today, please give me some time

**Comment by Nivedita967** [comment]
It's almost 20 days.

**Comment by abhinav5481** [comment]
Hi @Nivedita967 
I would like to solve this problem in Python. Could you please assign it to me?

**Comment by Nivedita967** [comment]
Sure @abhinav5481 Go for it.
