### ISSUE TITLE
I want to add comments to all the files

### ISSUE THREAD

**Issue by kmryashasvi** [Nivedita967/Data-Structure-and-Algorithms#31]
comments are very necessary
the make us understand the codes easily
there are very less fines in your repo which have comments in them, 
comments have too much importance in coding tests of many companies,
thats why I have choosen this issue.

**Comment by kmryashasvi** [comment]
This is under crosswoc
i dont know how to add labels on issues

**Comment by Nivedita967** [comment]
@kmryashasvi Add comments to existing code in this repository .

**Comment by hardikchitkara** [comment]
i can add comments in any language, please assign this task to me

**Comment by kmryashasvi** [comment]
My comments are also for any of the languages
 i am adding comments to all the files irrespective to any language or platform

**Comment by Nivedita967** [comment]
@kmryashasvi Have you commented all the code ?

**Comment by kmryashasvi** [comment]
Yes,
but if you agree,
I want to let this issue open so that, i can add comments to all future submissions,
even after the announcement of results of crosswoc

**Comment by kmryashasvi** [comment]
yes,
I have added comments to all the present files,
you can close this issue if you want

**Comment by Nivedita967** [comment]
> Yes,
> but if you agree,
> I want to let this issue open so that, i can add comments to all future submissions,
> even after the announcement of results of crosswoc

You will later open this.
