### ISSUE TITLE
Find the Running Median

### ISSUE THREAD

**Issue by weirdrag08** [Nivedita967/Data-Structure-and-Algorithms#311]
### Problem Link 
https://www.hackerrank.com/challenges/find-the-running-median/problem

### Coding platform
HackerRank

### Programming language

- [x] C
- [x] C++
- [x] Java
- [x] Python

**Comment by weirdrag08** [comment]
Please review this problem and assign me this in C++

**Comment by gopichandpuli9** [comment]
Assign this to me in python

**Comment by ItsmeSauravSonu** [comment]
I wanna contribute in java

**Comment by kmryashasvi** [comment]
I will do it in C

**Comment by Nivedita967** [comment]
@ItsmeSauravSonu Are you working?

**Comment by ItsmeSauravSonu** [comment]
Yes
