### ISSUE TITLE
Kruskal MST

### ISSUE THREAD

**Issue by ishikabansal04** [Nivedita967/Data-Structure-and-Algorithms#312]
### Problem Link 
https://www.hackerrank.com/challenges/kruskalmstrsub/problem

### Coding platform
Hackerrank

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [x] Python

**Comment by ishikabansal04** [comment]
Please review this problem issue and assign me in C++.

**Comment by ItsmeSauravSonu** [comment]
I want to contribute in java

**Comment by Nivedita967** [comment]
@ItsmeSauravSonu Are you working??

**Comment by Nivedita967** [comment]
> @ItsmeSauravSonu Are you working??

@ItsmeSauravSonu ??

**Comment by kmryashasvi** [comment]
I will do it in python

**Comment by Nivedita967** [comment]
@kmryashasvi Go for it.
