### ISSUE TITLE
Prim's (MST) : Special Subtree

### ISSUE THREAD

**Issue by weirdrag08** [Nivedita967/Data-Structure-and-Algorithms#313]
### Problem Link 
https://www.hackerrank.com/challenges/primsmstsub/problem

### Coding platform
HackerRank

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [x] Python

**Comment by weirdrag08** [comment]
Please review this problem and assign me this in C++

**Comment by Abhinav0909** [comment]
Hi, @Nivedita967 I want to work on this issue in java

**Comment by Nivedita967** [comment]
Sure @Abhinav0909 Go for it.

**Comment by Nivedita967** [comment]
@Abhinav0909 Are you working ??

**Comment by Abhinav0909** [comment]
@Nivedita967  I am working

**Comment by kmryashasvi** [comment]
I will do it in python

**Comment by Nivedita967** [comment]
Sure @kmryashasvi Go for it.
