### ISSUE TITLE
Power of Three

### ISSUE THREAD

**Issue by muthuannamalai12** [Nivedita967/Data-Structure-and-Algorithms#322]
### Problem Link 
Mention the problem on which you want to work on
https://leetcode.com/problems/power-of-three/
### Coding platform
Mention the coding platform from where you have picked the problem
LeetCode
### Programming language

- [ ] C
- [x] C++
- [x] Java
- [x] Python

**Comment by muthuannamalai12** [comment]
I would like to work on this issue in java as a part of Cross-Woc. Kindly assign it to me.

**Comment by JASKAMAL22** [comment]
I would like to work it using python. Can you please assign it to?

**Comment by kanak22** [comment]
I would like to work on this in C++
