### ISSUE TITLE
Two Sum

### ISSUE THREAD

**Issue by muthuannamalai12** [Nivedita967/Data-Structure-and-Algorithms#323]
### Problem Link 
Mention the problem on which you want to work on
https://leetcode.com/problems/two-sum/
### Coding platform
Mention the coding platform from where you have picked the problem
LeetCode
### Programming language

- [ ] C
- [x] C++
- [x] Java
- [x] Python

**Comment by muthuannamalai12** [comment]
I would love to work on this issue in python as a part of Cross-Woc.

**Comment by muthuannamalai12** [comment]
I would love to work on this issue in python as a part of Cross-Woc. Kindly assign it to me.

**Comment by kanak22** [comment]
I would like to work on this in C++

**Comment by Nivedita967** [comment]
@kanak22 @muthuannamalai12 Java code is already present in this repo so add your code to that folder itself.

**Comment by muthuannamalai12** [comment]
> @kanak22 @muthuannamalai12 Java code is already present in this repo so add your code to that folder itself.

Ok @Nivedita967

**Comment by kanak22** [comment]
okay @Nivedita967
