### ISSUE TITLE
Count Square Submatrices with All Ones

### ISSUE THREAD

**Issue by greenblade29** [Nivedita967/Data-Structure-and-Algorithms#326]
### Problem Link 
https://leetcode.com/problems/count-square-submatrices-with-all-ones/

### Coding platform
Leetcode

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [x] Python

### Additional context (OPTIONAL)
I want to solve it in Java

**Comment by Akash20x** [comment]
Please assign me, I want to solve it in python

**Comment by muthuannamalai12** [comment]
@Nivedita967 I would love to work on this issue in C++. Kindly assign it to me

**Comment by Nivedita967** [comment]
> @Nivedita967 I would love to work on this issue in C++. Kindly assign it to me

@muthuannamalai12 Let the beginners try :)

**Comment by Nivedita967** [comment]
@jayantjethi This issue is open for C++.

**Comment by muthuannamalai12** [comment]
> > @Nivedita967 I would love to work on this issue in C++. Kindly assign it to me
> 
> @muthuannamalai12 Let the beginners try :)

Ok. Thank you

**Comment by jayantjethi** [comment]
I would like to code on this issue in C++.Kindly Assign me

**Comment by Sloth-Panda** [comment]
@Nivedita967 can I try it in C?
