### ISSUE TITLE
Counting Bits

### ISSUE THREAD

**Issue by greenblade29** [Nivedita967/Data-Structure-and-Algorithms#327]
Problem Link 
https://leetcode.com/problems/counting-bits/

### Coding platform
Leetcode

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [x] Python

### Additional context (OPTIONAL)
I want to solve it in Java

**Comment by kanak22** [comment]
I would like to do it in C++

**Comment by muthuannamalai12** [comment]
@Nivedita967 I would love to solve this problem in python as a part of Cross-Woc. Kindly assign it to me

**Comment by Nivedita967** [comment]
@muthuannamalai12 Go for it.
