### ISSUE TITLE
Minimum Cost Tree from Leaf Values

### ISSUE THREAD

**Issue by greenblade29** [Nivedita967/Data-Structure-and-Algorithms#341]
### Problem Link 
https://leetcode.com/problems/minimum-cost-tree-from-leaf-values/

### Coding platform
Leetcode

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [ ] Python

### Additional context (OPTIONAL)
I want to solve it in Java

**Comment by Nivedita967** [comment]
@Jindalh2 This issue is open for C++

**Comment by Jindalh2** [comment]
Assign me in c++

**Comment by jayantjethi** [comment]
I would like to code on this issue in C++.Kindly Assign me

**Comment by Sloth-Panda** [comment]
@Nivedita967 can you assign me this for c?

**Comment by Nivedita967** [comment]
@jayantjethi Check for the issue #326. I have tagged you there.

**Comment by Nivedita967** [comment]
@jayantjethi @Jindalh2 There are some issue open for C++. Check issues of some days ago.

**Comment by jayantjethi** [comment]
> @jayantjethi @Jindalh2 There are some issue open for C++. Check issues of some days ago.

ok
