### ISSUE TITLE
Finding Highest Divisor

### ISSUE THREAD

**Issue by kmryashasvi** [Nivedita967/Data-Structure-and-Algorithms#350]
### Problem Link 
https://www.codechef.com/FEB21C/problems/HDIVISR

### Coding platform
Codechef

### Programming language

- [x] C
- [x] C++
- [x] Java
- [x] Python 3

**Comment by kmryashasvi** [comment]
I want to work on C on it

**Comment by jayantjethi** [comment]
I would like to code on this issue in C++.Kindly Assign me

**Comment by Jindalh2** [comment]
I would like to code on this issue in C++.Kindly Assign me

**Comment by jasmine1601** [comment]
@Nivedita967 I want to solve this in Java :)

**Comment by Nivedita967** [comment]
@jayantjethi Go for it :)

**Comment by kmryashasvi** [comment]
I will add my code(in C) after the above files are merged.

**Comment by kmryashasvi** [comment]
If you allow I can also provide python code for it

**Comment by Nivedita967** [comment]
> If you allow I can also provide python code for it

Sure go for it.

**Comment by kmryashasvi** [comment]
After merging above pull request, this issue can be closed
