### ISSUE TITLE
Fibonacci Number

### ISSUE THREAD

**Issue by muthuannamalai12** [Nivedita967/Data-Structure-and-Algorithms#353]
### Problem Link 
Mention the problem on which you want to work on
https://leetcode.com/problems/fibonacci-number/
### Coding platform
Mention the coding platform from where you have picked the problem
Leetcode
### Programming language

- [ ] C
- [x] C++
- [x] Java
- [x] Python

**Comment by muthuannamalai12** [comment]
I would love to work on this issue in python as a part of Cross-Woc. Kindly assign it to me

**Comment by weirdrag08** [comment]
Please assign me this in C++

**Comment by Jindalh2** [comment]
Assign me in C++

**Comment by jayantjethi** [comment]
I would like to code on this issue in C++.Kindly Assign me

**Comment by AbhipsaGuru1012** [comment]
@Nivedita967 I would like to work on this in java. Please assign it to me.

**Comment by Nivedita967** [comment]
Yeah Sure @AbhipsaGuru1012 Go for it :)

**Comment by AbhipsaGuru1012** [comment]
@Nivedita967 I made the PR. Please review.
