### ISSUE TITLE
Square Root(x)

### ISSUE THREAD

**Issue by muthuannamalai12** [Nivedita967/Data-Structure-and-Algorithms#354]
### Problem Link 
Mention the problem on which you want to work on
https://leetcode.com/problems/sqrtx/
### Coding platform
Mention the coding platform from where you have picked the problem
Leetcode
### Programming language

- [ ] C
- [x] C++
- [x] Java
- [x] Python

**Comment by muthuannamalai12** [comment]
I would love to work on this issue in python as a part of Cross-Woc. Kindly assign it to me

**Comment by JASKAMAL22** [comment]
Hey @Nivedita967 ,I would like to work in python. Kindly assign me also!!

**Comment by Jindalh2** [comment]
i would like to work in C++

**Comment by jayantjethi** [comment]
I would like to code on this issue in C++.Kindly Assign me

**Comment by ItsmeSauravSonu** [comment]
I would like to code in java, please assign to me

**Comment by Nivedita967** [comment]
@Jindalh2 @jayantjethi C++ is not open for this issue.

**Comment by AbhipsaGuru1012** [comment]
@Nivedita967 can I work on this in java?

**Comment by Nivedita967** [comment]
@AbhipsaGuru1012 Java is not open for this issue, please look for other issue.
