### ISSUE TITLE
Partition Array for Maximum Sum

### ISSUE THREAD

**Issue by greenblade29** [Nivedita967/Data-Structure-and-Algorithms#361]
### Problem Link 
https://leetcode.com/problems/partition-array-for-maximum-sum/

### Coding platform
Leetcode

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [ ] Python

### Additional context (OPTIONAL)
I want to solve it in Java

**Comment by Jindalh2** [comment]
I want to solve in C++

**Comment by Jindalh2** [comment]
Assign me

**Comment by jayantjethi** [comment]
I would like to code on this issue in C++.Kindly Assign me

**Comment by muthuannamalai12** [comment]
I would like to solve this in java as a part of Cross-Woc. Kindly assign it to me

**Comment by Nivedita967** [comment]
> I would like to code on this issue in C++.Kindly Assign me

@jayantjethi Look for other issues

**Comment by Nivedita967** [comment]
> I would like to solve this in java as a part of Cross-Woc. Kindly assign it to me

Java is not open.

**Comment by muthuannamalai12** [comment]
> > I would like to solve this in java as a part of Cross-Woc. Kindly assign it to me
> 
> Java is not open for this issue

Ok

**Comment by Sloth-Panda** [comment]
@Nivedita967 can I try this using c?

**Comment by Sloth-Panda** [comment]
@Nivedita967 are you accepting prs in python as well?

**Comment by Nivedita967** [comment]
> @Nivedita967 are you accepting prs in python as well?

Yes
