### ISSUE TITLE
BFS: (Shortest Reach In A Graph)

### ISSUE THREAD

**Issue by weirdrag08** [Nivedita967/Data-Structure-and-Algorithms#364]
### Problem Link 
https://www.hackerrank.com/challenges/ctci-bfs-shortest-reach/problem?h_l=interview&playlist_slugs%5B%5D=interview-preparation-kit&playlist_slugs%5B%5D=graphs

### Coding platform
Hackerrank

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [x] Python

**Comment by weirdrag08** [comment]
Please review this issue . I wish to do this in C++.

**Comment by ishikabansal04** [comment]
I want to solve this in Java.

**Comment by Sloth-Panda** [comment]
@Nivedita967 can I work on this using java?

**Comment by Akash20x** [comment]
Please assign me this issue
I will solve it in python

**Comment by Akash20x** [comment]
Please check my pull request
