### ISSUE TITLE
DFS: (Connected Cell in a Grid)

### ISSUE THREAD

**Issue by weirdrag08** [Nivedita967/Data-Structure-and-Algorithms#365]
### Problem Link 
https://www.hackerrank.com/challenges/ctci-connected-cell-in-a-grid/problem?h_l=interview&playlist_slugs%5B%5D=interview-preparation-kit&playlist_slugs%5B%5D=graphs

### Coding platform
Hackerrank

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [ ] Python

**Comment by weirdrag08** [comment]
Please review this issue. I would like to solve this in C++ :)

**Comment by ishikabansal04** [comment]
Hey @Nivedita967 , Please assign me in Java .

**Comment by Sloth-Panda** [comment]
@Nivedita967 Please assign it to me in C.

**Comment by Nivedita967** [comment]
@Sloth-Panda Are you working?
