### ISSUE TITLE
Mark And Toys

### ISSUE THREAD

**Issue by ishikabansal04** [Nivedita967/Data-Structure-and-Algorithms#366]
### Problem Link 
https://www.hackerrank.com/challenges/mark-and-toys/problem

### Coding platform
Hackerrank

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [x] Python

**Comment by ishikabansal04** [comment]
Please review this problem and assign me in Java.

**Comment by weirdrag08** [comment]
I want to solve this question in C++ ;-)

**Comment by muthuannamalai12** [comment]
I would like to solve this in python as a part of Cross-Woc
