### ISSUE TITLE
Smallest Number of notes on Codechef

### ISSUE THREAD

**Issue by kmryashasvi** [Nivedita967/Data-Structure-and-Algorithms#388]
### Problem Link 
https://www.codechef.com/problems/FLOW005

### Coding platform
Codechef

### Programming language

- [x] C
- [x] C++
- [x] Java
- [x] Python

**Comment by kmryashasvi** [comment]
I want to work for c and c++ on this solution,
since it is very easy and can be done simultaneously,
I want to do both the languages, c and c++

**Comment by Nivedita967** [comment]
Work on one at a time.

**Comment by kmryashasvi** [comment]
> Work on one at a time.

They were easy, that's why I tried to do simultaneously
😊

**Comment by kanak22** [comment]
I would like to do this in C++ if @kmryashasvi would do this in only one language

**Comment by kmryashasvi** [comment]
> I would like to do this in C++ if @kmryashasvi would do this in only one language

oh, I pulled for c++,
you can do in C after getting assigned if you want
@kanak22

**Comment by kanak22** [comment]
Sure @kmryashasvi 😊

**Comment by Nivedita967** [comment]
Sure @kanak22 .

**Comment by subhamagrawal7** [comment]
I would like to do this in Python

**Comment by Nivedita967** [comment]
Sure @subhamagrawal7 Go for it :)

**Comment by subhamagrawal7** [comment]
Please do review @Nivedita967 I have made the PR

**Comment by kmryashasvi** [comment]
If no one shows interest in java, I can provide solution of java also....

**Comment by Nivedita967** [comment]
> If no one shows interest in java, I can provide solution of java also....

Sure @kmryashasvi Go for it.

**Comment by kmryashasvi** [comment]
This issue can be closed after merging the above PR
