### ISSUE TITLE
The Coin Change Problem

### ISSUE THREAD

**Issue by ishikabansal04** [Nivedita967/Data-Structure-and-Algorithms#392]
### Problem Link 
https://www.hackerrank.com/challenges/coin-change/problem

### Coding platform
Hackerrank

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [x] Python

**Comment by ishikabansal04** [comment]
Please review this problem and assign me in Java.

**Comment by weirdrag08** [comment]
I would like to solve this in C++.

**Comment by muthuannamalai12** [comment]
@Nivedita967 I would like to solve this problem in python. Kindly assign me.

**Comment by ishikabansal04** [comment]
Hey @Nivedita967. If possible , could you please check community channel once. I am facing an issue and wanted to discuss.
Thankyou.
