### ISSUE TITLE
Knapsack

### ISSUE THREAD

**Issue by weirdrag08** [Nivedita967/Data-Structure-and-Algorithms#393]
### Problem Link 
https://www.hackerrank.com/challenges/unbounded-knapsack/problem

### Coding platform
Hackerrank

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [ ] Python

**Comment by weirdrag08** [comment]
I would like to solve this issue in C++.

**Comment by ishikabansal04** [comment]
Please assign me this in Java.

**Comment by swetakb15** [comment]
I would like to solve this issue in Python.

**Comment by Nivedita967** [comment]
Sure @swetakb15 Go for it :)

**Comment by Nivedita967** [comment]
@swetakb15 Are you working on this ?

**Comment by kmryashasvi** [comment]
> @swetakb15 Are you working on this ?

If she fails, I can do it in python

**Comment by Nivedita967** [comment]
> > @swetakb15 Are you working on this ?
> 
> If she fails, I can do it in python

@kmryashasvi Go for it.
