### ISSUE TITLE
Pairs

### ISSUE THREAD

**Issue by ishikabansal04** [Nivedita967/Data-Structure-and-Algorithms#394]
### Problem Link 
https://www.hackerrank.com/challenges/pairs/problem

### Coding platform
Hackerrank

### Programming language

- [x] C
- [x] C++
- [x] Java
- [x] Python

**Comment by ishikabansal04** [comment]
Please review this problem and assign me in Java.

**Comment by weirdrag08** [comment]
I would like to solve this in C++.

**Comment by kmryashasvi** [comment]
I can do it in c

**Comment by pri1311** [comment]
I would like to do this one in python

**Comment by Nivedita967** [comment]
Sure @pri1311 Go for it :)
