### ISSUE TITLE
Stone Game

### ISSUE THREAD

**Issue by greenblade29** [Nivedita967/Data-Structure-and-Algorithms#395]
### Problem Link 
https://leetcode.com/problems/stone-game/

### Coding platform
Leetcode

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [x] Python

### Additional context (OPTIONAL)
I want to solve it in Java

**Comment by kanak22** [comment]
I would like to do this in C++.

**Comment by muthuannamalai12** [comment]
@Nivedita967 I would like to solve this in python. Kindly assign it to me.
