### ISSUE TITLE
Number of Islands

### ISSUE THREAD

**Issue by jasmine1601** [Nivedita967/Data-Structure-and-Algorithms#411]
### Problem Link 
https://leetcode.com/problems/number-of-islands/

### Coding platform
LeetCode

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [x] Python

### Additional context (OPTIONAL)
I want to solve this in Java.

**Comment by kanak22** [comment]
I would like to do this in C++

**Comment by muthuannamalai12** [comment]
@Nivedita967 I would love to solve this in problem in python. Kindly assign me
