### ISSUE TITLE
Minimum Falling Path Sum

### ISSUE THREAD

**Issue by greenblade29** [Nivedita967/Data-Structure-and-Algorithms#415]
### Problem Link 
https://leetcode.com/problems/minimum-falling-path-sum/

### Coding platform
Leetcode

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [x] Python

### Additional context (OPTIONAL)
I want to solve it in Java

**Comment by kanak22** [comment]
I would like to do this in c++

**Comment by muthuannamalai12** [comment]
@Nivedita967 I would love to solve this problem in python. Kindly assign me
