### ISSUE TITLE
Minimum Cost For Tickets

### ISSUE THREAD

**Issue by greenblade29** [Nivedita967/Data-Structure-and-Algorithms#420]
### Problem Link 
https://leetcode.com/problems/minimum-cost-for-tickets/

### Coding platform
Leetcode

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [x] Python

### Additional context (OPTIONAL)
I want to solve it in Java

**Comment by kanak22** [comment]
I would like to do this in C++

**Comment by muthuannamalai12** [comment]
@Nivedita967 I would like to solve this in python. Kindly assign me.
