### ISSUE TITLE
hey,..! @Nivedita967,.. I know this issue will be different from all other issues. but ,.. I would like to add one folder for ..all the major algorithms like sorting, searching etc.+ some complex math problems in only PYTHON. so that it can be easily available under one roof. so.. can you please assign this issue to me??for contribution in crosswoc 

### ISSUE THREAD

**Issue by Mansi3546** [Nivedita967/Data-Structure-and-Algorithms#421]
### Problem Link 
Mention the problem on which you want to work on

### Coding platform
Mention the coding platform from where you have picked the problem

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by weirdrag08** [comment]
I guess it is not allowed. The repository's "About" clearly mentions that the questions will be platform specific and not topic specific :-)

**Comment by kmryashasvi** [comment]
I will be contributing in C++ for this issue, if assigned

**Comment by Nivedita967** [comment]
Yes, You are right @weirdrag08. 
@Mansi3546 This project is to provide coding platform specific problems under one roof and this project supports many different languages not only python. So, I can't assign you :(
