### ISSUE TITLE
Longest Valid Parenthesis

### ISSUE THREAD

**Issue by Riddhima-jain** [Nivedita967/Data-Structure-and-Algorithms#424]
### Problem Link 
https://leetcode.com/problems/longest-valid-parentheses/

### Coding platform
Leetcode

### Programming language

- [x] C
- [x] C++
- [x] Java
- [x] Python

### Additional context (OPTIONAL)
I would like to solve this in C++

**Comment by kmryashasvi** [comment]
I will work on c for this issue, if assigned

**Comment by Nivedita967** [comment]
@kmryashasvi @Riddhima-jain Go for it :)

**Comment by Amit366** [comment]
@Nivedita967 can I work on this issue using Java??

**Comment by Nivedita967** [comment]
Sure @Amit366 Go for it.

**Comment by Mansi3546** [comment]
@Nivedita967 hey..!! Can I work on this issue ,..using Python??

**Comment by Nivedita967** [comment]
Sure @Mansi3546 Go for it :)

**Comment by Nivedita967** [comment]
@Mansi3546 Are you working?

**Comment by Mansi3546** [comment]
@Nivedita967 ya ya mentor..! I will make the PR by tomorrow..is that okay??
