### ISSUE TITLE
N-Queens Problem

### ISSUE THREAD

**Issue by urvashiramdasani** [Nivedita967/Data-Structure-and-Algorithms#426]
### Problem Link 
https://leetcode.com/problems/n-queens/

### Coding platform
LeetCode

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [x] Python

### Additional context (OPTIONAL)
I want to solve this problem in C++ as a part of CrossWoC.

**Comment by Nivedita967** [comment]
@urvashiramdasani Go for it :)

**Comment by jasmine1601** [comment]
@Nivedita967 I want to try this in Java.

**Comment by Akash20x** [comment]
Please assign me, I have to solve this in python
