### ISSUE TITLE
Printing Pattern Using Loops

### ISSUE THREAD

**Issue by saimanoharhm** [Nivedita967/Data-Structure-and-Algorithms#428]
### Problem Link 
https://www.hackerrank.com/challenges/printing-pattern-2/problem

### Coding platform
Hackerrank

### Programming language

- [x] C
- [x] C++
- [x] Python

### Additional context (OPTIONAL)
I would like work on c,c++ and java

**Comment by saimanoharhm** [comment]
I would like to work on c

**Comment by saimanoharhm** [comment]
@Nivedita967 Could you pls assign this for me

**Comment by Nivedita967** [comment]
@saimanoharhm You can work on one language at a time.

**Comment by saimanoharhm** [comment]
@Nivedita967 ok. I will work on c

**Comment by Nivedita967** [comment]
Sure go for it :)

**Comment by Riddhima-jain** [comment]
I'd like to solve this in C++
Can you assign me this?

**Comment by Nivedita967** [comment]
Sure @Riddhima-jain Go for it :)

**Comment by kiruba-r11** [comment]
@Nivedita967 Can I work on it in Python? Please assign it to me
