### ISSUE TITLE
Airplane Seat Assignment Probability

### ISSUE THREAD

**Issue by greenblade29** [Nivedita967/Data-Structure-and-Algorithms#433]
### Problem Link 
https://leetcode.com/problems/airplane-seat-assignment-probability/

### Coding platform
Leetcode

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [x] Python

### Additional context (OPTIONAL)
I want to solve it in Java

**Comment by jayantjethi** [comment]
I would like to code on this issue in C++.Kindly Assign me

**Comment by Akash20x** [comment]
I want to solve it in python,
Kindly assign me

**Comment by Akash20x** [comment]
Please merge this pull request 

BFS: (Shortest Reach In A Graph) #449

**Comment by Akash20x** [comment]
Please merge pending pull request
BFS: (Shortest Reach In A Graph) #449

**Comment by jayantjethi** [comment]
Mam Should i try this Issue in c++
