### ISSUE TITLE
Palindromic Substrings

### ISSUE THREAD

**Issue by greenblade29** [Nivedita967/Data-Structure-and-Algorithms#434]
### Problem Link 
https://leetcode.com/problems/palindromic-substrings/

### Coding platform
Leetcode

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [x] Python

### Additional context (OPTIONAL)
I want to solve it in Java

**Comment by Riddhima-jain** [comment]
I'd like to solve this in C++ and Python

**Comment by dcs-soni** [comment]
Hi. If not assigned to anyone I would like to solve this problem in C++.
