### ISSUE TITLE
Chef and Meetings

### ISSUE THREAD

**Issue by jayantjethi** [Nivedita967/Data-Structure-and-Algorithms#443]
### Problem Link 
https://www.codechef.com/FEB21C/problems/MEET/

### Coding platform
Codechef

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by jayantjethi** [comment]
I would like to code on this issue in C++.Kindly Assign me

**Comment by Jatin2020-24** [comment]
I can do this issue in python. Kindly assign me.

**Comment by Nivedita967** [comment]
@jayantjethi @Jatin2020-24 Go for it.

**Comment by Nivedita967** [comment]
@Jatin2020-24 Are you working on this ?
