### ISSUE TITLE
Add a readme file for explaining every question 

### ISSUE THREAD

**Issue by kmryashasvi** [Nivedita967/Data-Structure-and-Algorithms#461]
### Problem Link 
NA

### Coding platform
All platforms

### Programming language

- [x] C
- [x] C++
- [x] Java
- [x] Python

**Comment by Nivedita967** [comment]
@kmryashasvi I don't think that this is required. There will be so many questions from different platform and every time adding readme for added problem, this will not be covered.

**Comment by kmryashasvi** [comment]
Ok I got it.
