### ISSUE TITLE
Ways to Make a Fair Array

### ISSUE THREAD

**Issue by greenblade29** [Nivedita967/Data-Structure-and-Algorithms#463]
### Problem Link 
https://leetcode.com/problems/ways-to-make-a-fair-array/

### Coding platform
Leetcode

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [ ] Python

### Additional context (OPTIONAL)
I want to solve it in Java

**Comment by kanak22** [comment]
I would like to do this in c++
