### ISSUE TITLE
Count Submatrices With All Ones

### ISSUE THREAD

**Issue by greenblade29** [Nivedita967/Data-Structure-and-Algorithms#464]
### Problem Link 
https://leetcode.com/problems/count-submatrices-with-all-ones/

### Coding platform
Leetcode

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [ ] Python

### Additional context (OPTIONAL)
I want to solve it in Java

**Comment by kanak22** [comment]
I would like to do this in  C++
