### ISSUE TITLE
Permutations of Strings

### ISSUE THREAD

**Issue by saimanoharhm** [Nivedita967/Data-Structure-and-Algorithms#466]
### Problem Link 
https://www.hackerrank.com/challenges/permutations-of-strings/problem

### Coding platform
Hacker Rank

### Programming language

- [x] C
- [ ] C++
- [x] Java
- [x] Python

**Comment by saimanoharhm** [comment]
@Nivedita967 Could you assign this for me. I would like contribute on c

**Comment by pri1311** [comment]
I would like to do this in c++

**Comment by Nivedita967** [comment]
Sure @pri1311 Go for it :)

**Comment by abhinav5481** [comment]
Hi @Nivedita967 
I would like to work on this in Java. Please assign it to me.

**Comment by Nivedita967** [comment]
Sure @abhinav5481 Go for it.

**Comment by Nivedita967** [comment]
@pri1311 Are you working on this?

**Comment by pri1311** [comment]
Hey yes, when my current pull requests are merged I will Create one for this. Sorry for the delay

**Comment by Amit366** [comment]
@Nivedita967 can I solve using python??

**Comment by Nivedita967** [comment]
> @Nivedita967 can I solve using python??

Sure @Amit366 Go for it.

**Comment by kanak22** [comment]
is it open for C++?

**Comment by Nivedita967** [comment]
@pri1311 Are you on this?
