### ISSUE TITLE
Variadic functions in C

### ISSUE THREAD

**Issue by saimanoharhm** [Nivedita967/Data-Structure-and-Algorithms#467]
### Problem Link 
https://www.hackerrank.com/challenges/variadic-functions-in-c/problem

### Coding platform
Hacker rank

### Programming language

- [x] C

**Comment by saimanoharhm** [comment]
@Nivedita967 Could you pls assign this for me. I would like to work on c

**Comment by Nivedita967** [comment]
@saimanoharhm Are you working on this?

**Comment by saimanoharhm** [comment]
@Nivedita967 Yes
