### ISSUE TITLE
Array Manipulation

### ISSUE THREAD

**Issue by Ayush7614** [Nivedita967/Data-Structure-and-Algorithms#473]
### Problem Link 
https://www.hackerrank.com/challenges/crush/problem

### Coding platform
Hackerank

### Programming language

- [x] C
- [x] C++
- [x] Java
- [x] Python

**Comment by Ayush7614** [comment]
@Nivedita967 plss assign me this issue

**Comment by Nivedita967** [comment]
@Ayush7614 Work on one language at a time.

**Comment by weirdrag08** [comment]
@Nivedita967 , Can I do in c++ , if @Ayush7614 can work in python.

**Comment by ishikabansal04** [comment]
I want to work on this issue in Java.

**Comment by Ayush7614** [comment]
> @Ayush7614 Work on one language at a time.

Okk so i work in python

**Comment by Amit366** [comment]
@Nivedita967 can i implement in C ?

**Comment by Nivedita967** [comment]
@ishikabansal04 @weirdrag08 Are you working on this ?

**Comment by ishikabansal04** [comment]
> @ishikabansal04 @weirdrag08 Are you working on this ?

Yes. Sorry for a little delay.
