### ISSUE TITLE
Sparse Arrays

### ISSUE THREAD

**Issue by Ayush7614** [Nivedita967/Data-Structure-and-Algorithms#474]
### Problem Link 
https://www.hackerrank.com/challenges/sparse-arrays/problem

### Coding platform
Hackerank

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [x] Python

**Comment by Ayush7614** [comment]
@Nivedita967 plss assign me this issue under Crosswoc

**Comment by Nivedita967** [comment]
@Ayush7614 Work on one language at a time.

**Comment by Ayush7614** [comment]
okk @Nivedita967 i have to work on c++ plss level it assign me

**Comment by Sriram-bb63** [comment]
@Nivedita967 I would like to solve this in python

**Comment by Nivedita967** [comment]
Sure @Sriram-bb63 Go for it.
