### ISSUE TITLE
Dynamic Array

### ISSUE THREAD

**Issue by Ayush7614** [Nivedita967/Data-Structure-and-Algorithms#475]
### Problem Link 
https://www.hackerrank.com/challenges/dynamic-array/problem

### Coding platform
Hackerank

### Programming language

- [x] C
- [x] C++
- [ ] Java
- [x] Python

**Comment by Ayush7614** [comment]
@Nivedita967 plss assign me this issue under Crosswoc

**Comment by Ayush7614** [comment]
okk @Nivedita967 i have to work in c++ for this issue plss assign me

**Comment by Sriram-bb63** [comment]
I would like to work on this in python

**Comment by Nivedita967** [comment]
@Ayush7614 Are you working??

**Comment by Abhinav0909** [comment]
Hi, @Nivedita967 I want to work on this issue in java

**Comment by pri1311** [comment]
will do it in C

**Comment by Ayush7614** [comment]
> @Ayush7614 Are you working??

@Nivedita967 i work in c++

**Comment by Nivedita967** [comment]
> Hi, @Nivedita967 I want to work on this issue in java

Sure @Abhinav0909 Go for it.

**Comment by Nivedita967** [comment]
> will do it in C

Sure @pri1311 Go for it.

**Comment by Nivedita967** [comment]
> > @Ayush7614 Are you working??
> 
> @Nivedita967 i work in c++

Then do it ASAP because it's almost 24 days.

**Comment by Nivedita967** [comment]
@Abhinav0909 Are you working??

**Comment by Abhinav0909** [comment]
@Nivedita967 , I am working

**Comment by Nivedita967** [comment]
> @Nivedita967 , I am working

@Abhinav0909 Today is the last day of contribution under CrossWoC. Complete it ASAP.

**Comment by Abhinav0909** [comment]
@Nivedita967 , I have removed unwanted files
