### ISSUE TITLE
Print the Elements of a Linked List

### ISSUE THREAD

**Issue by Ayush7614** [Nivedita967/Data-Structure-and-Algorithms#476]
### Problem Link 
https://www.hackerrank.com/challenges/print-the-elements-of-a-linked-list/problem

### Coding platform
Hackerank

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by Ayush7614** [comment]
Assign me under Crosswoc

**Comment by Ayush7614** [comment]
work in c++ plss assign me

**Comment by jayantjethi** [comment]
I would like to work on this issue in C++.Kindly Assign Me.

**Comment by Nivedita967** [comment]
@Ayush7614 Clear all the previous assigned issues.

**Comment by JASKAMAL22** [comment]
I would like to work on this issue in python. Kindly assign it to me.

**Comment by Nivedita967** [comment]
@JASKAMAL22 ??

**Comment by bhardwaj2000** [comment]
I would like to work on this issue in C++. Kindly Assign Me.

**Comment by Nivedita967** [comment]
@bhardwaj2000 C++ is done for this.
