### ISSUE TITLE
Insert a Node at the Tail of a Linked List

### ISSUE THREAD

**Issue by Ayush7614** [Nivedita967/Data-Structure-and-Algorithms#477]
### Problem Link 
https://www.hackerrank.com/challenges/insert-a-node-at-the-tail-of-a-linked-list/problem

### Coding platform
Hackerank

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by Ayush7614** [comment]
@Nivedita967 plss assign me under crosswoc

**Comment by Ayush7614** [comment]
working in c++ plss assign me

**Comment by jayantjethi** [comment]
I would like to work on this issue in C++.Kindly Assign Me.

**Comment by Nivedita967** [comment]
@Ayush7614 Clear all the previous assigned issues.

**Comment by JASKAMAL22** [comment]
please assign it to me. Want to work using python.. :)

**Comment by Nivedita967** [comment]
@JASKAMAL22 Are you working?

**Comment by Abhinav0909** [comment]
Hi,@Nivedita967 I want to work on this issue in java

**Comment by Nivedita967** [comment]
> Hi,@Nivedita967 I want to work on this issue in java

Sure @Abhinav0909 Go for it.
