### ISSUE TITLE
Prime Game 

### ISSUE THREAD

**Issue by Ayush7614** [Nivedita967/Data-Structure-and-Algorithms#478]
### Problem Link 
https://www.codechef.com/FEB21C/problems/PRIGAME

### Coding platform
Codechef

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by Ayush7614** [comment]
assign me under crosswoc @Nivedita967

**Comment by arbazalam01** [comment]
Can i do it in C++

**Comment by Ayush7614** [comment]
@arbazalam01 bro I have already this question in c++ you can solve any other language
