### ISSUE TITLE
Chef and Meetings

### ISSUE THREAD

**Issue by Ayush7614** [Nivedita967/Data-Structure-and-Algorithms#479]
### Problem Link 
https://www.codechef.com/FEB21C/problems/MEET

### Coding platform
Codechef

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by Ayush7614** [comment]
@Nivedita967 plss assign me under crosswoc

**Comment by Nivedita967** [comment]
@Ayush7614 Check all previous issues before creating new. This issue is already open.
