### ISSUE TITLE
I want to add some solutions of hackerrank and codechef

### ISSUE THREAD

**Issue by kmryashasvi** [Nivedita967/Data-Structure-and-Algorithms#48]

**Comment by Nivedita967** [comment]
Give the link of Problem you want to work on, after completing one you can work on another.

**Comment by kmryashasvi** [comment]
I have to add solutions of approximately 10 problems
their java solution are already present in your repo
i will just add C and C++ version of the solution
it will be messy if i provide link of all the problems and then work on it,
they are large in number

**Comment by Nivedita967** [comment]
Join the Gitter channel- https://gitter.im/Data-Structure-and-Algorithms-Nivedita/community
You can't work on all the problems. Everyone will work on particular problem on particular language.
