### ISSUE TITLE
Vaccine Production

### ISSUE THREAD

**Issue by Ayush7614** [Nivedita967/Data-Structure-and-Algorithms#480]
### Problem Link 
https://www.codechef.com/problems/VACCINE1

### Coding platform
Codechef

### Programming language

- [x] C
- [x] C++
- [ ] Java
- [x] Python

**Comment by Ayush7614** [comment]
@Nivedita967 plss assign me under Crosswoc

**Comment by kmryashasvi** [comment]
I want to work on C for this issue

**Comment by jayantjethi** [comment]
I would Like to Work On this Issue In C++.Kindly Assign Me.

**Comment by Nivedita967** [comment]
@jayantjethi C++ is not open for this issue

**Comment by Nivedita967** [comment]
@Ayush7614 This is not good, you changed the language.

**Comment by Nivedita967** [comment]
@jayantjethi Do you want to do it in C++ ?

**Comment by jayantjethi** [comment]
Sure mam I will do it in C++

**Comment by Ayush7614** [comment]
> I would Like to Work On this Issue In C++.Kindly Assign Me.

@jayantjethi said that he will do in C++ thats why i do in python what i am doing wrong thing @Nivedita967

**Comment by kmryashasvi** [comment]
But he was not assigned to do anything,
In any issue,
The first one to claim the language gets the opportunity to work on it

**Comment by Nivedita967** [comment]
> But he was not assigned to do anything,
> In any issue,
> The first one to claim the language gets the opportunity to work on it

Exactly, @Ayush7614 You were working on C++ that's why I denied @jayantjethi.

**Comment by Nivedita967** [comment]
Sure @jayantjethi Go for it.

**Comment by Abhinav0909** [comment]
Hi, @Nivedita967 I want to work on this issue in java

**Comment by Nivedita967** [comment]
> Hi, @Nivedita967 I want to work on this issue in java

Go for it @Abhinav0909 .

**Comment by Nivedita967** [comment]
@Abhinav0909 Are you working?

**Comment by Abhinav0909** [comment]
@Nivedita967, yes I am working
