### ISSUE TITLE
Goldmine Problem

### ISSUE THREAD

**Issue by ishikabansal04** [Nivedita967/Data-Structure-and-Algorithms#487]
### Problem Link 
https://www.geeksforgeeks.org/gold-mine-problem/

### Coding platform
GeeksforGeeks

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [x] Python

**Comment by ishikabansal04** [comment]
Please review this problem and assign me in Java.

**Comment by weirdrag08** [comment]
I would like to work on this issue in C++.

**Comment by kmryashasvi** [comment]
I will do it in python.
