### ISSUE TITLE
Maximum sum such that no two elements are adjacent

### ISSUE THREAD

**Issue by weirdrag08** [Nivedita967/Data-Structure-and-Algorithms#488]
### Problem Link 
https://www.geeksforgeeks.org/maximum-sum-such-that-no-two-elements-are-adjacent/

### Coding platform
GeeksforGeeks

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [x] Python

**Comment by weirdrag08** [comment]
I would like to work on this in C++.

**Comment by ishikabansal04** [comment]
Please assign me in Java.

**Comment by kmryashasvi** [comment]
I will do it in Python

**Comment by kmryashasvi** [comment]
@Nivedita967  
Go to the provided link of this problem and scroll down,
Solution of The problem is available and geeks for geeks is not a competitive programming platform Is it right to merge files like that in this repo??

**Comment by weirdrag08** [comment]
> @Nivedita967
> Go to the provided link of this problem and scroll down,
> Solution of The problem is available and geeks for geeks is not a competitive programming platform Is it right to merge files like that in this repo??

Bro, I get it what you are trying to say, even I thought the same thing when a contributor added this folder. But after that I realised that at the end it's up to the person that if he or she wants to cheat or not. The overall motive of this event is that we can learn new things, concepts and new questions and not just to score points to top some kind of leaderboard. If someone wants to just cheat then it is his/her loss . I guess the community or the event will not be harmed by his actions. Also if someone is unable to solve some problem, but were able to code it up after seeing some algorithm or an approach and not just doing "Ctrl C" + "Ctrl V" the editorials, then I think it is fine. Also every coding platform does have an editorial for every problem and people can also view them without solving it. Nonetheless this is my way of seeing this issue, rest is up to @Nivedita967 ;-)

**Comment by kiruba-r11** [comment]
@Nivedita967 Please assign me for C

**Comment by Nivedita967** [comment]
@kiruba-r11 Are you working ?
