### ISSUE TITLE
Decode Ways

### ISSUE THREAD

**Issue by ishikabansal04** [Nivedita967/Data-Structure-and-Algorithms#491]
### Problem Link 
https://leetcode.com/problems/decode-ways/

### Coding platform
Leetcode

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [x] Python

**Comment by ishikabansal04** [comment]
Please review this issue and assign me in Java.

**Comment by weirdrag08** [comment]
I want to do this in C++.

**Comment by Akash20x** [comment]
I want to solve it in python 
Kindly assign me
