### ISSUE TITLE
Stuck Keyboard

### ISSUE THREAD

**Issue by kiruba-r11** [Nivedita967/Data-Structure-and-Algorithms#496]
### Problem Link 
[Problem Link](https://binarysearch.com/problems/Stuck-Keyboard)

### Coding platform

[Binary Search](https://binarysearch.com)

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by kiruba-r11** [comment]
Please review this issue and assign me in C++. Binary Search is also one of the popular coding and problem-solving platform.

**Comment by Nivedita967** [comment]
Hey @kiruba-r11 Please select one existing coding platform because this platform is not used by maximum.

**Comment by kiruba-r11** [comment]
@Nivedita967 Shall I close these issues?
