### ISSUE TITLE
Palindromic Anagram

### ISSUE THREAD

**Issue by kiruba-r11** [Nivedita967/Data-Structure-and-Algorithms#498]
### Problem Link 
[Problem Link](https://binarysearch.com/problems/Palindromic-Anagram)

### Coding platform
[Binary Search](https://binarysearch.com)

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by kiruba-r11** [comment]
Please review this issue and assign me in C++.

**Comment by Nivedita967** [comment]
@kiruba-r11 Please change the problem link to familiar platform problem link so that every one can participate.
