### ISSUE TITLE
Left Rotation

### ISSUE THREAD

**Issue by Nivedita967** [Nivedita967/Data-Structure-and-Algorithms#50]
Problem link- https://www.hackerrank.com/challenges/array-left-rotation/problem from HackerRank.

**Comment by kmryashasvi** [comment]
I will provide its solution in c++

**Comment by Nivedita967** [comment]
@kmryashasvi Sure, go for it.

**Comment by hardikchitkara** [comment]
i will provide you solution in java.

**Comment by Nivedita967** [comment]
@hardikchitkara Go for it.

**Comment by Amit366** [comment]
@Nivedita967  can i work on this issue??

**Comment by Nivedita967** [comment]
@Amit366 Sure, In which language you want to work ?

**Comment by Archna29** [comment]
@Nivedita967 can i work on this issue in java language

**Comment by Nivedita967** [comment]
@Archna29 Java is already taken.

**Comment by saksham-s1ngh** [comment]
Can I work on this issue in Python?

**Comment by Amit366** [comment]
I can work on C++.

**Comment by Nivedita967** [comment]
@saksham-s1ngh Go for it.

**Comment by Nivedita967** [comment]
@Amit366 C++ is already done. You can do it in C.

**Comment by Amit366** [comment]
Ok

**Comment by Amit366** [comment]
Should I create a separate function or can I do it in Main itself?

**Comment by TechSpiritSS** [comment]
Is this issue still open for C or C++

**Comment by Nivedita967** [comment]
> Should I create a separate function or can I do it in Main itself?

Anything you want.

**Comment by Nivedita967** [comment]
> Is this issue still open for C or C++

No.
