### ISSUE TITLE
Chef and Trump Cards 

### ISSUE THREAD

**Issue by kiruba-r11** [Nivedita967/Data-Structure-and-Algorithms#502]
### Problem Link 
[Problem Link](https://www.codechef.com/SEPT20B/problems/CRDGAME2)

### Coding platform
[CodeChef](https://www.codechef.com)

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by kiruba-r11** [comment]
@Nivedita967 Please assign this issue to me

**Comment by kanak22** [comment]
I would like to o this in C++

**Comment by Nivedita967** [comment]
@kiruba-r11 Go for it.
@kanak22 C++ is not open for this.

**Comment by kanak22** [comment]
Okay 😊
