### ISSUE TITLE
Diagonal difference on Hackerrank

### ISSUE THREAD

**Issue by kmryashasvi** [Nivedita967/Data-Structure-and-Algorithms#506]
### Problem Link 
https://www.hackerrank.com/challenges/diagonal-difference/problem

### Coding platform
Hackerrank

### Programming language

- [x] C
- [x] C++
- [x] Java
- [x] Python

![image](https://user-images.githubusercontent.com/66861659/109374101-e4185100-78d8-11eb-93ae-a5169f65136e.png)

**Comment by kmryashasvi** [comment]
I want to do the above problem in C++

**Comment by jasmine1601** [comment]
@Nivedita967 I want to solve this in Java.

**Comment by Sriram-bb63** [comment]
@Nivedita967 I would like to solve this in python

**Comment by Kpraful** [comment]
@Nivedita967 I want to solve this in c++

**Comment by Nivedita967** [comment]
@Kpraful C++ is not open for this issue.

**Comment by kmryashasvi** [comment]
@Kpraful I am doing it in c++, you can do it in C

**Comment by Kpraful** [comment]
I want to solve this in c.
