### ISSUE TITLE
Arithmetic Slices

### ISSUE THREAD

**Issue by greenblade29** [Nivedita967/Data-Structure-and-Algorithms#509]
### Problem Link 
https://leetcode.com/problems/arithmetic-slices/

### Coding platform
Leetcode

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [ ] Python

### Additional context (OPTIONAL)
I want to solve it in Java

**Comment by Riddhima-jain** [comment]
I'd like to solve this in C++

**Comment by JASKAMAL22** [comment]
I would like to work in Python. Please assign it to me! :)
