### ISSUE TITLE
Reducing Dishes

### ISSUE THREAD

**Issue by greenblade29** [Nivedita967/Data-Structure-and-Algorithms#510]
### Problem Link 
https://leetcode.com/problems/reducing-dishes/

### Coding platform
Leetcode

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [x] Python

### Additional context (OPTIONAL)
I want to solve it in Java

**Comment by Kpraful** [comment]
I want to solve this in c++

**Comment by Akash20x** [comment]
I want to solve it in python
Please assign me this issue
