### ISSUE TITLE
Total Score

### ISSUE THREAD

**Issue by Kpraful** [Nivedita967/Data-Structure-and-Algorithms#511]
### Problem Link 
https://www.codechef.com/CCRC21C/problems/TOTSCR

### Coding platform
CodeChef

### Programming language

- [x] C
- [x] C++
- [ ] Java
- [x] Python

**Comment by Kpraful** [comment]
@Nivedita967  I want to do this in C++

**Comment by Riddhima-jain** [comment]
I'd like to solve this in C++

**Comment by Nivedita967** [comment]
@Kpraful @Riddhima-jain Go for it :)

**Comment by Kpraful** [comment]
@Nivedita967 Thank you for this opportunity, I have created  pull request, please let me know if I have to modify something or somethings is wrong with it. As I am fairly new, so any suggestion is appreciated.

**Comment by kiruba-r11** [comment]
@Nivedita967 Shall I solve it in C

**Comment by AbhipsaGuru1012** [comment]
@Nivedita967 I would like to solve this in java. Please assign it to me.

**Comment by Nivedita967** [comment]
@AbhipsaGuru1012 Are you working on this ?

**Comment by AbhipsaGuru1012** [comment]
> @AbhipsaGuru1012 Are you working on this ?
@Nivedita967 Sorry, I won't be able to work on this as my exams are going on. Apologies for any inconvenience caused.

**Comment by Nivedita967** [comment]
> > @AbhipsaGuru1012 Are you working on this ?
> > @Nivedita967 Sorry, I won't be able to work on this as my exams are going on. Apologies for any inconvenience caused.

No problem @AbhipsaGuru1012 , try to complete it after exam.

**Comment by pri1311** [comment]
Can I do this in Java?

**Comment by Nivedita967** [comment]
@AbhipsaGuru1012 Are your exams over?

**Comment by abhinav5481** [comment]
Hi @Nivedita967
Is this issue still open? Can I solve it in Java?

**Comment by abhinav5481** [comment]
Hi @Nivedita967
Is this issue still open? Can I solve it in Java?

**Comment by Nivedita967** [comment]
> Hi @Nivedita967
> Is this issue still open? Can I solve it in Java?

Go for it @abhinav5481
