### ISSUE TITLE
Trapping Rain Water (LeetCode Hard)

### ISSUE THREAD

**Issue by rahil-1407** [Nivedita967/Data-Structure-and-Algorithms#514]
Problem Link 
https://leetcode.com/problems/trapping-rain-water/

Coding platform
LeetCode

Programming language

- [x] C
- [x] C++
- [x] Java
- [x] Python

Additional context (OPTIONAL)
This is  nice problem often asked in Coding Interviews.

**Comment by rahil-1407** [comment]
Please see the problem and assign me for C++ language.

**Comment by Nivedita967** [comment]
@rahil-1407 Go for it :)

**Comment by Akash20x** [comment]
Can you please assign me this issue, I want to solve it in python

**Comment by kiruba-r11** [comment]
@Nivedita967 Please assign it to me, I want to solve it in C

**Comment by rahil-1407** [comment]
@Nivedita967 I have created pull request. Please let me know if there is any anamoly.

**Comment by Akash20x** [comment]
Please check my pull request

**Comment by Amit366** [comment]
@Nivedita967 can I solve this using Java??

**Comment by Nivedita967** [comment]
Sure @Amit366 .
