### ISSUE TITLE
Magical Candy Store

### ISSUE THREAD

**Issue by kiruba-r11** [Nivedita967/Data-Structure-and-Algorithms#518]
### Problem Link 
[Problem Link](https://www.codechef.com/NOV20A/problems/CNDYGAME)

### Coding platform
[CodeChef](https://www.codechef.com)

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by kiruba-r11** [comment]
@Nivedita967 Please assign it to me

**Comment by Nivedita967** [comment]
@kiruba-r11 Are you working?
