### ISSUE TITLE
Find XOR (Interactive Problem)

### ISSUE THREAD

**Issue by kiruba-r11** [Nivedita967/Data-Structure-and-Algorithms#519]
### Problem Link 
[Problem Link](https://www.codechef.com/SEPT20B/problems/FINXOR)

### Coding platform
[CodeChef](https://www.codechef.com)

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by kiruba-r11** [comment]
@Nivedita967 Please have a look at it and assign it to me. It is an interactive problem.

**Comment by kiruba-r11** [comment]
@Nivedita967 Can you please make it a hard problem, because it is an Interactive Problem

**Comment by Nivedita967** [comment]
> @Nivedita967 Can you please make it a hard problem, because it is an Interactive Problem

This is a medium level problem.

**Comment by arbazalam01** [comment]
can i work on it

**Comment by Nivedita967** [comment]
@arbazalam01 in which language you want to work ?

**Comment by arbazalam01** [comment]
In c++

**Comment by Nivedita967** [comment]
@arbazalam01 C++ is done.
