### ISSUE TITLE
Best Time to Buy and Sell Stock with Transaction Fee

### ISSUE THREAD

**Issue by rahil-1407** [Nivedita967/Data-Structure-and-Algorithms#530]
### Coding platform
LeetCode

### Programming language

- [x] C
- [x] C++
- [x] Java
- [ ] Python

### Additional context (OPTIONAL)
A nice DP problem of medium difficulty to learn from.

**Comment by rahil-1407** [comment]
@Nivedita967 Please assign me this problem in C++.

**Comment by ishikabansal04** [comment]
I would like to do this in Java.

**Comment by weirdrag08** [comment]
Please assign me this problem in C

**Comment by Nivedita967** [comment]
@weirdrag08 Are you working?

**Comment by pri1311** [comment]
will do it in python

**Comment by Nivedita967** [comment]
> will do it in python

Go for it.
