### ISSUE TITLE
Where Will the Ball Fall

### ISSUE THREAD

**Issue by greenblade29** [Nivedita967/Data-Structure-and-Algorithms#534]
### Problem Link 
https://leetcode.com/problems/where-will-the-ball-fall/

### Coding platform
Leetcode

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [ ] Python

### Additional context (OPTIONAL)
I want to solve it in Java

**Comment by kanak22** [comment]
I would like to solve this in C++

**Comment by abhinav5481** [comment]
Hi @Nivedita967 
I would like to solve this issue in Java Or Python. Could you please assign it to me?

**Comment by Nivedita967** [comment]
Sure @abhinav5481 Go for Python.
