### ISSUE TITLE
Build Array Where You Can Find The Maximum Exactly K Comparisons

### ISSUE THREAD

**Issue by greenblade29** [Nivedita967/Data-Structure-and-Algorithms#535]
### Problem Link 
https://leetcode.com/problems/build-array-where-you-can-find-the-maximum-exactly-k-comparisons/

### Coding platform
Leetcode

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [x] Python

### Additional context (OPTIONAL)
I want to solve it in Java

**Comment by kanak22** [comment]
I would like to solve this in C++

**Comment by Kpraful** [comment]
I would like to solve this in Python

**Comment by Nivedita967** [comment]
Sure @Kpraful Go for it.

**Comment by Amit366** [comment]
Can I work on this issue in Python??

**Comment by Nivedita967** [comment]
@Amit366 Python is not open for this.
