### ISSUE TITLE
Longest Substring Without Repeating Characters

### ISSUE THREAD

**Issue by urvashiramdasani** [Nivedita967/Data-Structure-and-Algorithms#537]
### Problem Link 
https://leetcode.com/problems/longest-substring-without-repeating-characters/

### Coding platform
LeetCode

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [x] Python

### Additional context (OPTIONAL)
I want to solve this problem in C++ as a part of crossWoC.

**Comment by JASKAMAL22** [comment]
hello @Nivedita967 ,I would like to work this problem in python. Please assign it to me!!

**Comment by Nivedita967** [comment]
Sure @JASKAMAL22.

**Comment by abhinav5481** [comment]
Hi @Nivedita967 
I would like to work on this in Java. Please assign it to me.

**Comment by Nivedita967** [comment]
> Hi @Nivedita967
> I would like to work on this in Java. Please assign it to me.

Sure @abhinav5481 Go for it.

**Comment by pri1311** [comment]
will do it in C

**Comment by Nivedita967** [comment]
> will do it in C

Go for it.
