### ISSUE TITLE
Chef and Coupon

### ISSUE THREAD

**Issue by kanak22** [Nivedita967/Data-Structure-and-Algorithms#538]
### Problem Link 
https://www.codechef.com/START1C/problems/COUPON2

### Coding platform
Codechef

### Programming language

- [x] C
- [x] C++
- [x] Java
- [ ] Python

### Additional context (OPTIONAL)
I want to solve this in C++

**Comment by jasmine1601** [comment]
@Nivedita967 I want to solve this in Java.

**Comment by TechSpiritSS** [comment]
I can do this in C

**Comment by kanak22** [comment]
@Nivedita967 kindly close the issue if anyone isnt there for python.
