### ISSUE TITLE
Plus Minus On Hackerrank

### ISSUE THREAD

**Issue by kmryashasvi** [Nivedita967/Data-Structure-and-Algorithms#542]
### Problem Link 
https://www.hackerrank.com/challenges/plus-minus/problem

### Coding platform
Hackerrak

### Programming language

- [x] C
- [x] C++
- [ ] Java
- [x] Python

### Additional context (OPTIONAL)
![image](https://user-images.githubusercontent.com/66861659/109454261-d1894d80-7a79-11eb-9f60-c597e199f8d6.png)

**Comment by kmryashasvi** [comment]
I will solve this in C++

**Comment by TechSpiritSS** [comment]
I can do this in C

**Comment by JASKAMAL22** [comment]
Hey @Nivedita967, I would like to work in Python. Kindly assign it to me.

**Comment by bhardwaj2000** [comment]
I would like to work on this issue in python. Kindly Assign Me.

**Comment by bhardwaj2000** [comment]
I would like to work on this issue in python. Kindly Assign Me.

**Comment by Nivedita967** [comment]
@bhardwaj2000 C++ is done in this issue.

**Comment by kmryashasvi** [comment]
I can also work in java

**Comment by Nivedita967** [comment]
> I can also work in java

Sure Go for it.
