### ISSUE TITLE
Staircase on hackerrank

### ISSUE THREAD

**Issue by kmryashasvi** [Nivedita967/Data-Structure-and-Algorithms#543]
### Problem Link 
https://www.hackerrank.com/challenges/staircase/problem

### Coding platform
Hackerrank

### Programming language

- [x] C
- [x] C++
- [x] Java
- [ ] Python

**Comment by kmryashasvi** [comment]
I want to do it in C++

**Comment by jasmine1601** [comment]
@Nivedita967 I want to solve this in Java.

**Comment by TechSpiritSS** [comment]
I can do this in C

**Comment by kmryashasvi** [comment]
I will pull the  request after the above pr gets merged

**Comment by JASKAMAL22** [comment]
please assign it to me ,I want to work on this issue in python.

**Comment by Nivedita967** [comment]
@JASKAMAL22 Go for it.

**Comment by Nivedita967** [comment]
@JASKAMAL22 Are you working ?

**Comment by kmryashasvi** [comment]
If he refuses,
I can provide code in Python too
