### ISSUE TITLE
Number of subsequences of the form a^i b^j c^k

### ISSUE THREAD

**Issue by ishikabansal04** [Nivedita967/Data-Structure-and-Algorithms#562]
### Problem Link 
https://www.geeksforgeeks.org/number-subsequences-form-ai-bj-ck/

### Coding platform
GeeksforGeeks

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [x] Python

**Comment by ishikabansal04** [comment]
Please review this issue and assign me in Java.

**Comment by weirdrag08** [comment]
I would like to do this in C++.

**Comment by Amit366** [comment]
Can I implement in python?
