### ISSUE TITLE
Painting Fence Algorithm

### ISSUE THREAD

**Issue by weirdrag08** [Nivedita967/Data-Structure-and-Algorithms#563]
### Problem Link 
https://www.geeksforgeeks.org/painting-fence-algorithm/

### Coding platform
GeeksforGeeks

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [x] Python

**Comment by weirdrag08** [comment]
Please assign me in C++.

**Comment by ishikabansal04** [comment]
I would like to do in Java.

**Comment by Nivedita967** [comment]
@weirdrag08 @ishikabansal04 There is given practice link, try to work on this because that practice problem gives you exact problem name and exact question description.

**Comment by Amit366** [comment]
Can I implement in C++?

**Comment by Nivedita967** [comment]
Yes, @Amit366
