### ISSUE TITLE
Minimum ASCII Delete Sum for Two Strings

### ISSUE THREAD

**Issue by greenblade29** [Nivedita967/Data-Structure-and-Algorithms#568]
### Problem Link 
https://leetcode.com/problems/minimum-ascii-delete-sum-for-two-strings/

### Coding platform
Leetcode

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [ ] Python

### Additional context (OPTIONAL)
I want to solve it in Java

**Comment by kanak22** [comment]
I would like to do this in c++

**Comment by abhinav5481** [comment]
Hi @Nivedita967 
I would like to work on it in Java . Please assign it to me.

**Comment by Nivedita967** [comment]
> Hi @Nivedita967
> I would like to work on it in Java . Please assign it to me.

Sure @abhinav5481
