### ISSUE TITLE
Longest Common Subsequence

### ISSUE THREAD

**Issue by greenblade29** [Nivedita967/Data-Structure-and-Algorithms#569]
### Problem Link 
https://leetcode.com/problems/longest-common-subsequence/

### Coding platform
Leetcode

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [ ] Python

### Additional context (OPTIONAL)
I want to solve it in Java

**Comment by kanak22** [comment]
I would like to do this in c++

**Comment by Nivedita967** [comment]
@abhinav5481 Please tell your language.

**Comment by abhinav5481** [comment]
I can do it in Java & Python. Please tell me in which language do you want me to code.

**Comment by Nivedita967** [comment]
This issue is open for Python and C. So, Go with Python @abhinav5481 .
