### ISSUE TITLE
Minimum Falling Path Sum II

### ISSUE THREAD

**Issue by greenblade29** [Nivedita967/Data-Structure-and-Algorithms#570]
### Problem Link 
https://leetcode.com/problems/minimum-falling-path-sum-ii/

### Coding platform
Leetcode

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [x] Python

### Additional context (OPTIONAL)
I want to solve it in Java

**Comment by kanak22** [comment]
I would like to do this in c++

**Comment by Akash20x** [comment]
I want to solve it in python
Please assign me this issue as a part of Cross Woc
