### ISSUE TITLE
Mini Max sum on Hackerrank

### ISSUE THREAD

**Issue by kmryashasvi** [Nivedita967/Data-Structure-and-Algorithms#573]
### Problem Link 
https://www.hackerrank.com/challenges/mini-max-sum/problem

### Coding platform
Hackerrank

### Programming language

- [x] C
- [x] C++
- [x] Java
- [x] Python

**Comment by kmryashasvi** [comment]
I will provide code for it in python

**Comment by kanak22** [comment]
I would like to solve this in C++

**Comment by jasmine1601** [comment]
@Nivedita967 I want to solve this in Java.

**Comment by TechSpiritSS** [comment]
I can do this in C
