### ISSUE TITLE
Time conversion on hackerrank

### ISSUE THREAD

**Issue by kmryashasvi** [Nivedita967/Data-Structure-and-Algorithms#574]
### Problem Link 
https://www.hackerrank.com/challenges/time-conversion/problem

### Coding platform
Hackerrank

### Programming language

- [x] C
- [x] C++
- [ ] Java
- [x] Python

**Comment by kmryashasvi** [comment]
I will provide solution in python

**Comment by kanak22** [comment]
I would like to solve this in C++

**Comment by TechSpiritSS** [comment]
I can do this in C

**Comment by pri1311** [comment]
Will do it in Java.

**Comment by Nivedita967** [comment]
> Will do it in Java.

Go for it.
