### ISSUE TITLE
Add two numbers

### ISSUE THREAD

**Issue by pri1311** [Nivedita967/Data-Structure-and-Algorithms#576]
### Problem Link 
https://leetcode.com/problems/add-two-numbers/

### Coding platform
Leetcode

### Programming language

- [x] C
- [x] C++
- [x] Java
- [ ] Python

### Additional context (OPTIONAL)
would like to submit the solution for c++

**Comment by pri1311** [comment]
please assign this to me under crosswoc

**Comment by Nivedita967** [comment]
Sure @pri1311 Go for it :)

**Comment by arbazalam01** [comment]
can i do it in C++

**Comment by Nivedita967** [comment]
@arbazalam01 C++ is not  open for this issue.

**Comment by arbazalam01** [comment]
then is it available for Python

**Comment by Nivedita967** [comment]
Yes @arbazalam01, this is open for Python.

**Comment by Nivedita967** [comment]
@abhinav5481 In which language you want to code ?

**Comment by abhinav5481** [comment]
I can do it in Python, Java & Javascript. Please assign it to me in any one of the languages.

**Comment by Nivedita967** [comment]
Go for Java @abhinav5481 :)

**Comment by pri1311** [comment]
Will do it in C

**Comment by Nivedita967** [comment]
> Will do it in C

Sure.

**Comment by Nivedita967** [comment]
@arbazalam01 I have requested you some changes in your PR. Check it ASAP.
