### ISSUE TITLE
Carvans on codechef

### ISSUE THREAD

**Issue by stlyash** [Nivedita967/Data-Structure-and-Algorithms#577]
### Problem Link 
https://www.codechef.com/LRNDSA01/problems/CARVANS

### Coding platform
Codechef

### Programming language

- [x] C
- [x] C++
- [ ] Java
- [x] Python

**Comment by kmryashasvi** [comment]
I will provide code in c++

**Comment by kmryashasvi** [comment]
since there are so much similarities in C and C++,
Please feel free to let me provide code in C too, if no one else proposes to work on c

**Comment by arbazalam01** [comment]
can i do it in python

**Comment by Kpraful** [comment]
I want to do it in C.

**Comment by Nivedita967** [comment]
Sure @arbazalam01 @Kpraful Go for it :)

**Comment by Abhinav0909** [comment]
Hi, @Nivedita967 I want to work on this issue in java

**Comment by Nivedita967** [comment]
> Hi, @Nivedita967 I want to work on this issue in java

Sure @Abhinav0909 Go for it.

**Comment by abhinav5481** [comment]
Hi @Nivedita967
Is this issue still open? Can I solve it in Java?

**Comment by abhinav5481** [comment]
Hi @Nivedita967
Is this issue still open? Can I solve it in Java?

**Comment by Nivedita967** [comment]
> Hi @Nivedita967
> Is this issue still open? Can I solve it in Java?

Go for it @abhinav5481
