### ISSUE TITLE
Lowest Common Ancestor of a Binary Tree

### ISSUE THREAD

**Issue by rahil-1407** [Nivedita967/Data-Structure-and-Algorithms#589]
### Problem Link 
https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/

### Coding platform
LeetCode

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [x] Python

### Additional context (OPTIONAL)
A Tree Problem

**Comment by rahil-1407** [comment]
Assign me in C++.

**Comment by abhinav5481** [comment]
Hi @Nivedita967 
I would like to solve it in Java as part of CrossWoc'21. Please assign it to me.

**Comment by abhinav5481** [comment]
If it is open for Java. Please assign it to me

**Comment by Amit366** [comment]
@Nivedita967 can I work using python??

**Comment by Nivedita967** [comment]
> @Nivedita967 can I work using python??

Sure @Amit366 Go for it.
