### ISSUE TITLE
Median of Two Sorted Arrays

### ISSUE THREAD

**Issue by urvashiramdasani** [Nivedita967/Data-Structure-and-Algorithms#593]
### Problem Link 
https://leetcode.com/problems/median-of-two-sorted-arrays/

### Coding platform
LeetCode

### Programming language

- [x] C
- [ ] C++
- [x] Java
- [x] Python

### Additional context (OPTIONAL)
I want to solve this problem in C++ as a part of crossWoC.

**Comment by kiruba-r11** [comment]
@Nivedita967 Please assign this to me in C

**Comment by Kpraful** [comment]
May I solve this in python ?

**Comment by Nivedita967** [comment]
Sure @kiruba-r11 @Kpraful Go for it :)

**Comment by Amit366** [comment]
@Nivedita967 Can I implement in Java?

**Comment by Nivedita967** [comment]
Yes @Amit366

**Comment by pri1311** [comment]
Is this open for c++?

**Comment by Amit366** [comment]
@Nivedita967 is it open for C??

**Comment by Nivedita967** [comment]
@urvashiramdasani @kiruba-r11 Are you working on it?

**Comment by urvashiramdasani** [comment]
Yes, I am working on it.

**Comment by Amit366** [comment]
@Nivedita967 is this issue open??

**Comment by Nivedita967** [comment]
> @Nivedita967 is this issue open??

Yes @Amit366 This is open for C. Do you want to work on it?

**Comment by Amit366** [comment]
@Nivedita967 yes

**Comment by Nivedita967** [comment]
@urvashiramdasani Are you working on this??

**Comment by abhinav5481** [comment]
Hi @Nivedita967
Is this issue still open? Can I solve it in C++?

**Comment by abhinav5481** [comment]
Hi 
@Nivedita967 
If no one is working on it then can I get assigned to it for C++

**Comment by abhinav5481** [comment]
Hi @Nivedita967
If it is open please assign it to me for C++.

**Comment by Amit366** [comment]
@Nivedita967 if it is open for C++ please assign.

**Comment by Nivedita967** [comment]
> Hi
> @Nivedita967
> If no one is working on it then can I get assigned to it for C++

@abhinav5481 Go for it.
