### ISSUE TITLE
Best Time to Buy and Sell Stock

### ISSUE THREAD

**Issue by jayantjethi** [Nivedita967/Data-Structure-and-Algorithms#598]
### Problem Link 
https://leetcode.com/problems/best-time-to-buy-and-sell-stock/

### Coding platform
LeetCode

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by jayantjethi** [comment]
I would Like to Solve this problem in c++. Kindly Assign Me.

**Comment by rahil-1407** [comment]
This que is already present in the repo.

**Comment by jayantjethi** [comment]
@Nivedita967 mam close the issue if its already present.
