### ISSUE TITLE
Daanish and Problems

### ISSUE THREAD

**Issue by jayantjethi** [Nivedita967/Data-Structure-and-Algorithms#599]
### Problem Link 
https://www.codechef.com/LTIME93C/problems/DIV03

### Coding platform
Codechef

### Programming language

- [x] C
- [x] C++
- [x] Java
- [ ] Python

**Comment by jayantjethi** [comment]
I would Like to Solve this problem in C++. Kindly Assign Me.

**Comment by simonnepinto** [comment]
Can I do this in Java?

**Comment by Nivedita967** [comment]
Sure @simonnepinto Go for it :)

**Comment by pri1311** [comment]
Will do it in python

**Comment by abhinav5481** [comment]
Hi @Nivedita967 
I would like to solve it in C. Please assign it to me.
