### ISSUE TITLE
I will add name and photo of maintainer in the end of readme file of your repo

### ISSUE THREAD

**Issue by kmryashasvi** [Nivedita967/Data-Structure-and-Algorithms#600]
like the one mentioned below
![image](https://user-images.githubusercontent.com/66861659/110196937-01679500-7e6e-11eb-8ac3-40ce278e17c3.png)

**Comment by Nivedita967** [comment]
Is it really required?
Means isn't look of readme is better for now?

**Comment by kmryashasvi** [comment]
Yes, you are right
