### ISSUE TITLE
Filling Bookcase Shelves

### ISSUE THREAD

**Issue by greenblade29** [Nivedita967/Data-Structure-and-Algorithms#611]
### Problem Link 
https://leetcode.com/problems/filling-bookcase-shelves/

### Coding platform
Leetcode

### Programming language

- [x] C
- [x] C++
- [x] Java
- [ ] Python

### Additional context (OPTIONAL)
I want to solve it in Java

**Comment by jayantjethi** [comment]
I would Like to Solve it in C++.Kindly Assign Me.

**Comment by abhinav5481** [comment]
Hi @Nivedita967 
I would like to solve it in Java. please assign it to me

**Comment by Nivedita967** [comment]
> Hi @Nivedita967
> I would like to solve it in Java. please assign it to me

Java is not open for this issue.

**Comment by jayantjethi** [comment]
@Nivedita967 mam Please check my PR.

**Comment by pri1311** [comment]
Will do it in Python.

**Comment by abhinav5481** [comment]
I will do it in c
