### ISSUE TITLE
Number of Submatrices That Sum to Target

### ISSUE THREAD

**Issue by greenblade29** [Nivedita967/Data-Structure-and-Algorithms#612]
### Problem Link 
https://leetcode.com/problems/number-of-submatrices-that-sum-to-target/

### Coding platform
Leetcode

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [ ] Python

### Additional context (OPTIONAL)
I want to solve it in Java

**Comment by kanak22** [comment]
I would like to solve this in C++

**Comment by Amit366** [comment]
@Nivedita967 Can I implement it in python??

**Comment by Nivedita967** [comment]
Sure @Amit366 Go for it.
