### ISSUE TITLE
Minimum Distance to Type a Word Using Two Fingers

### ISSUE THREAD

**Issue by greenblade29** [Nivedita967/Data-Structure-and-Algorithms#613]
### Problem Link 
https://leetcode.com/problems/minimum-distance-to-type-a-word-using-two-fingers/

### Coding platform
Leetcode

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [x] Python

### Additional context (OPTIONAL)
I want to solve it in Java

**Comment by Akash20x** [comment]
I want to solve this in python
Please assign me this issue as a part of Cross Woc

**Comment by kanak22** [comment]
I would like to solve this in C++
