### ISSUE TITLE
Red John is Back

### ISSUE THREAD

**Issue by weirdrag08** [Nivedita967/Data-Structure-and-Algorithms#627]
### Problem Link 
https://www.hackerrank.com/challenges/red-john-is-back/problem

### Coding platform
Hackerrank

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [x] Python

**Comment by weirdrag08** [comment]
Please review this question and assign me in C++ ;-)

**Comment by ishikabansal04** [comment]
I want to do this in Java.

**Comment by abhinav5481** [comment]
Hi @ishikabansal04 
I would like to solve it in Python. Please assign it to me

**Comment by ishikabansal04** [comment]
> Hi @ishikabansal04
> I would like to solve it in Python. Please assign it to me

hey @abhinav5481 . I am not the one who assigns the task. Please tag @Nivedita967 . She is the owner for the project.

**Comment by pri1311** [comment]
will do it in C

**Comment by Nivedita967** [comment]
> will do it in C

@pri1311 You have many pending issues, Complete ASAP.

**Comment by pri1311** [comment]
Yes @Nivedita967

**Comment by pri1311** [comment]
@Nivedita967  Hey sorry for the delay, actually even though I have been assigned issue it wasn't showing up in my assigned section. Will send all PRs today itself.
