### ISSUE TITLE
The Maximum Subarray

### ISSUE THREAD

**Issue by ishikabansal04** [Nivedita967/Data-Structure-and-Algorithms#628]
### Problem Link 
https://www.hackerrank.com/challenges/maxsubarray/problem

### Coding platform
Hackerrank

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [x] Python

**Comment by ishikabansal04** [comment]
Please review this problem & assign me this in Java.

**Comment by weirdrag08** [comment]
Please assign me this in C++ :)

**Comment by Kpraful** [comment]
I would like to try this with python

**Comment by Nivedita967** [comment]
@weirdrag08 Are you working?

**Comment by pri1311** [comment]
will do it in C

**Comment by Nivedita967** [comment]
> will do it in C

Sure @pri1311
