### ISSUE TITLE
Count number of ways to partition a set into k subsets

### ISSUE THREAD

**Issue by ishikabansal04** [Nivedita967/Data-Structure-and-Algorithms#629]
### Problem Link 
https://www.geeksforgeeks.org/count-number-of-ways-to-partition-a-set-into-k-subsets/

### Coding platform
GeeksforGeeks

### Programming language

- [x] C
- [x] C++
- [x] Java
- [x] Python

**Comment by ishikabansal04** [comment]
Please review this problem and assign me in Java.

**Comment by weirdrag08** [comment]
Please assign me in C++.

**Comment by abhinav5481** [comment]
hi @Nivedita967 
I would like to solve it in python. Please assign it to me.

**Comment by Nivedita967** [comment]
@weirdrag08 Are you working?

**Comment by weirdrag08** [comment]
> @weirdrag08 Are you working?

Hey, @Nivedita967 , yes am working on all the issues. Apologies for the delay. I am having my exams and lab assignments. I will definitely put the PR for all the issues very soon. Please give me a little more time. Thankyou :)

**Comment by pri1311** [comment]
will do it in C

**Comment by Nivedita967** [comment]
@pri1311 Complete all your pending issues ASAP. Are you doing?

**Comment by pri1311** [comment]
Hey, yes will send today

**Comment by pri1311** [comment]
Actually my assigned section is not showing all issues, so as soon my current PRs are merged, Ill go through the issues section and create PRs
