### ISSUE TITLE
Printing Tokens

### ISSUE THREAD

**Issue by saimanoharhm** [Nivedita967/Data-Structure-and-Algorithms#632]
### Problem Link 
https://www.hackerrank.com/challenges/printing-tokens-/problem

### Coding platform
Hackerrank

### Programming language

- [x] C
- [x] C++

**Comment by saimanoharhm** [comment]
@Nivedita967 I would like to work on this.  Could you pls assign this for me.

**Comment by kmryashasvi** [comment]
I will be glad to do it in C++
