### ISSUE TITLE
Digit Frequency

### ISSUE THREAD

**Issue by saimanoharhm** [Nivedita967/Data-Structure-and-Algorithms#633]
### Problem Link 
https://www.hackerrank.com/challenges/frequency-of-digits-1/problem

### Coding platform
Hackerrank

### Programming language

- [x] C
- [x] C++
- [ ] Java
- [x] Python

**Comment by saimanoharhm** [comment]
@Nivedita967  I would like to work on this. Could you pls assign this for me.

**Comment by pri1311** [comment]
Assign this to me for c++, please.

**Comment by abhinav5481** [comment]
Hi @Nivedita967 
I would like to do it in Java or Python. Could you please assign it to me in any one of the languages?

**Comment by Nivedita967** [comment]
Sure @abhinav5481 Go for Java.
