### ISSUE TITLE
Boxes through a Tunnel

### ISSUE THREAD

**Issue by saimanoharhm** [Nivedita967/Data-Structure-and-Algorithms#634]
### Problem Link 
https://www.hackerrank.com/challenges/too-high-boxes/problem

### Coding platform
Hackerrank

### Programming language

- [x] C
- [x] C++
- [ ] Java
- [x] Python

**Comment by saimanoharhm** [comment]
@Nivedita967  I would like to work on this. Could you pls assign this for me.

**Comment by jayantjethi** [comment]
I would like to code this in C++.Kindly Assign me.

**Comment by kmryashasvi** [comment]
I will do it in python

**Comment by pri1311** [comment]
will do it in Java.
