### ISSUE TITLE
Improve Readme.

### ISSUE THREAD

**Issue by Nivedita967** [Nivedita967/Data-Structure-and-Algorithms#638]
Anyone can attempt to improve readme of this project, like adding number of closed issues, pull request, stars, fork or adding gif/images or improving fonts or anything.

**Comment by kmryashasvi** [comment]
Please have a look at the contribution that i have done 
![image](https://user-images.githubusercontent.com/66861659/110418296-51886680-80bd-11eb-9f49-3001204126a7.png)

**Comment by kmryashasvi** [comment]
It will be great, if you give me the list of badges to be added, else, I will add them on my own and then we will decide, which one to keep or remove,
Thank you

**Comment by Nivedita967** [comment]
> It will be great, if you give me the list of badges to be added, else, I will add them on my own and then we will decide, which one to keep or remove,
> Thank you

Open issue, closed issue, open pr, closed pr, star, fork, contributors, open source and maintained badges for now.
