### ISSUE TITLE
Subarray Division

### ISSUE THREAD

**Issue by stlyash** [Nivedita967/Data-Structure-and-Algorithms#660]
### Problem Link 
https://www.hackerrank.com/challenges/the-birthday-bar/problem

### Coding platform
Hackerrank

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [ ] Python

**Comment by pri1311** [comment]
will do it in python

**Comment by abhinav5481** [comment]
Hi @Nivedita967 
I would like to solve it in Java. Please assign it to me.
