### ISSUE TITLE
Grading students

### ISSUE THREAD

**Issue by stlyash** [Nivedita967/Data-Structure-and-Algorithms#661]
### Problem Link 
https://www.hackerrank.com/challenges/grading/problem

### Coding platform
Hackerrank

### Programming language

- [x] C
- [x] C++
- [x] Java
- [x] Python

**Comment by kmryashasvi** [comment]
I want to contribute in C++

**Comment by Sriram-bb63** [comment]
I would like to solve this in python @Nivedita967

**Comment by kmryashasvi** [comment]
If anyone fails, I can also provide solution for this in C and Python

**Comment by Nivedita967** [comment]
> If anyone fails, I can also provide solution for this in C and Python

Python is done, you may go for C.

**Comment by pri1311** [comment]
Can I do this in Java?

**Comment by Nivedita967** [comment]
> Can I do this in Java?

Sure @pri1311 Go for it.
