### ISSUE TITLE
Palindrome Partitioning III

### ISSUE THREAD

**Issue by greenblade29** [Nivedita967/Data-Structure-and-Algorithms#663]
### Problem Link 
https://leetcode.com/problems/palindrome-partitioning-iii/

### Coding platform
Leetcode

### Programming language

- [ ] C
- [ ] C++
- [x] Java
- [x] Python

### Additional context (OPTIONAL)
I want to solve it in Java

**Comment by kmryashasvi** [comment]
I will solve it in python

**Comment by kmryashasvi** [comment]
I will provide solution after the above pr gets merged

**Comment by Amit366** [comment]
@Nivedita967 can I do it in C++?

**Comment by Nivedita967** [comment]
Sure @Amit366

**Comment by kmryashasvi** [comment]
Why aren't you merging the PRs?

**Comment by Nivedita967** [comment]
> Why aren't you merging the PRs?

Have Patience, I am going to this.
