### ISSUE TITLE
Number of Ways to Paint N × 3 Grid

### ISSUE THREAD

**Issue by greenblade29** [Nivedita967/Data-Structure-and-Algorithms#664]
### Problem Link 
https://leetcode.com/problems/number-of-ways-to-paint-n-3-grid/

### Coding platform
Leetcode

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [ ] Python

### Additional context (OPTIONAL)
I want to solve it in Java

**Comment by kanak22** [comment]
I would like to solve this in c++. kindly assign it to me

**Comment by kmryashasvi** [comment]
I will solve it in python
