### ISSUE TITLE
Unique Paths

### ISSUE THREAD

**Issue by greenblade29** [Nivedita967/Data-Structure-and-Algorithms#665]
### Problem Link 
https://leetcode.com/problems/unique-paths/

### Coding platform
Leetcode

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [ ] Python

### Additional context (OPTIONAL)
I want to solve it in Java

**Comment by kanak22** [comment]
I would like to solve this in c++. kindly assign it to me

**Comment by cryptus-neoxys** [comment]
Hey, I have solved this problem in C++ without DP. Can you assign this to me.

**Comment by cryptus-neoxys** [comment]
I can also add the DP memoization solution too.

**Comment by Nivedita967** [comment]
Sure @cryptus-neoxys You can add memoization solution too. Just create one addition file in the folder and add your solution to it.

**Comment by pri1311** [comment]
Will do it in Python.
