### ISSUE TITLE
Find Maximum Index Product

### ISSUE THREAD

**Issue by ishikabansal04** [Nivedita967/Data-Structure-and-Algorithms#671]
### Problem Link 
https://www.hackerrank.com/challenges/find-maximum-index-product/problem

### Coding platform
Hackerrank

### Programming language

- [x] C
- [ ] C++
- [x] Java
- [x] Python

**Comment by ishikabansal04** [comment]
I would like to do this issue in Java.

**Comment by weirdrag08** [comment]
Please assign me in C++.

**Comment by Sriram-bb63** [comment]
I would like to do this in python please @Nivedita967

**Comment by pri1311** [comment]
will do it in C

**Comment by abhinav5481** [comment]
Hi @Nivedita967
Is this issue still open? Can I solve it in C++?
