### ISSUE TITLE
The Longest Increasing Subsequence

### ISSUE THREAD

**Issue by weirdrag08** [Nivedita967/Data-Structure-and-Algorithms#673]
### Problem Link 
https://www.hackerrank.com/challenges/longest-increasing-subsequent/problem

### Coding platform
Hackerrank

### Programming language

- [x] C
- [ ] C++
- [x] Java
- [x] Python

**Comment by weirdrag08** [comment]
Please review this problem and assign me in C++.

**Comment by Akash20x** [comment]
I want to solve it in python. Please assign me this issue as a part of Cross Woc

**Comment by kmryashasvi** [comment]
I will provide code in C

**Comment by Akash20x** [comment]
Please check my pull request

**Comment by Amit366** [comment]
@Nivedita967 is it open for Java??

**Comment by Nivedita967** [comment]
> @Nivedita967 is it open for Java??

No.

**Comment by Nivedita967** [comment]
@weirdrag08 Are you working?

**Comment by Amit366** [comment]
@Nivedita967 which language is open??

**Comment by weirdrag08** [comment]
> @weirdrag08 Are you working?

yes
