### ISSUE TITLE
Fibonacci Modified

### ISSUE THREAD

**Issue by ishikabansal04** [Nivedita967/Data-Structure-and-Algorithms#677]
### Problem Link 
https://www.hackerrank.com/challenges/fibonacci-modified/problem

### Coding platform
Hackerrank

### Programming language

- [x] C
- [ ] C++
- [x] Java
- [x] Python

**Comment by ishikabansal04** [comment]
Please review this problem and assign me in Python

**Comment by weirdrag08** [comment]
I would like to solve this in Java.

**Comment by deephunt3r** [comment]
I would like to solve in c++ .could you please assign it to me

**Comment by pri1311** [comment]
will do it in C

**Comment by Amit366** [comment]
@Nivedita967 can I work in Java??

**Comment by Nivedita967** [comment]
> @Nivedita967 can I work in Java??

@Amit366 Java is not open for this issue.

**Comment by Nivedita967** [comment]
> I would like to solve in c++ .could you please assign it to me

@deephunt3r Are you working on this?

**Comment by Amit366** [comment]
@Nivedita967 is this issue open??

**Comment by Nivedita967** [comment]
> @Nivedita967 is this issue open??
> If it is open please assign it to me.

Sure @Amit366 Go for C++
