### ISSUE TITLE
Beautiful Year

### ISSUE THREAD

**Issue by kanak22** [Nivedita967/Data-Structure-and-Algorithms#679]
### Problem Link 
https://codeforces.com/problemset/problem/271/A

### Coding platform
Codeforces

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [x] Python

### Additional context (OPTIONAL)
I want to solve this in C++

**Comment by ArkajyotiChakraborty** [comment]
Good Morning, can I work on this issue.

**Comment by Nivedita967** [comment]
@ArkajyotiChakraborty Please tell your language in which you want to code.

**Comment by ArkajyotiChakraborty** [comment]
I want to work in Java.

**Comment by Nivedita967** [comment]
Go for it @ArkajyotiChakraborty :)

**Comment by pri1311** [comment]
Can I solve it in Python?

**Comment by ArkajyotiChakraborty** [comment]
@Nivedita967 I have done the question will make the PR tomorrow.
