### ISSUE TITLE
Panoramix's Prediction

### ISSUE THREAD

**Issue by kanak22** [Nivedita967/Data-Structure-and-Algorithms#681]
### Problem Link 
https://codeforces.com/problemset/problem/80/A

### Coding platform
Codeforces

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [x] Python

### Additional context (OPTIONAL)
I want to solve this in C++.

**Comment by ArkajyotiChakraborty** [comment]
Ma'am can i work on this issue, I can work in Java.

**Comment by Nivedita967** [comment]
Sure @ArkajyotiChakraborty Go for it :)

**Comment by abhinav5481** [comment]
Hi @Nivedita967 
I would like to solve it in Python. Please assign it to me.

**Comment by Nivedita967** [comment]
> Hi @Nivedita967
> I would like to solve it in Python. Please assign it to me.

Sure @abhinav5481

**Comment by ArkajyotiChakraborty** [comment]
@Nivedita967 i have done the question, will make the PR tomorrow.

**Comment by abhinav5481** [comment]
Hi @Nivedita967 
I would like to solve it in C. Please assign it to me.
