### ISSUE TITLE
Cats and a Mouse

### ISSUE THREAD

**Issue by stlyash** [Nivedita967/Data-Structure-and-Algorithms#683]
### Problem Link 
https://www.hackerrank.com/challenges/cats-and-a-mouse/problem

### Coding platform
Hackerrank

### Programming language

- [x] C
- [x] C++
- [x] Java
- [ ] Python

**Comment by kmryashasvi** [comment]
I will provide code in c++

**Comment by bhardwaj2000** [comment]
I would like to work on this issue in python. Kindly Assign Me.

**Comment by Nivedita967** [comment]
Sure @bhardwaj2000 Go for it :)

**Comment by pri1311** [comment]
Can I do this in Java?

**Comment by Nivedita967** [comment]
@bhardwaj2000 I have requested you changes. Check your PR.

**Comment by abhinav5481** [comment]
Hi  @Nivedita967 
I would like to solve it in C. Please assign it to me.

**Comment by Amit366** [comment]
@Nivedita967 is it open for java??

**Comment by Amit366** [comment]
@Nivedita967 can I do in Java???
