### ISSUE TITLE
Sorting Array of Strings

### ISSUE THREAD

**Issue by saimanoharhm** [Nivedita967/Data-Structure-and-Algorithms#685]
### Problem Link 
https://www.hackerrank.com/challenges/sorting-array-of-strings/problem

### Coding platform
Hackerrank

### Programming language

- [x] C
- [ ] C++
- [x] Java
- [x] Python

**Comment by saimanoharhm** [comment]
@Nivedita967 Could you pls assign this for me.  I will work on c++

**Comment by Akash20x** [comment]
I want to solve it in python. Please assign me this issue as a part of Cross Woc

**Comment by kmryashasvi** [comment]
I will provide code in C

**Comment by abhinav5481** [comment]
Hi @Nivedita967 
I would like to solve it in Java. Please assign it to me.

**Comment by arbazalam01** [comment]
can i do it in c++

**Comment by Nivedita967** [comment]
@abhinav5481 Go for Java.
@arbazalam01 C++ is not open.

**Comment by Nivedita967** [comment]
> @Nivedita967 Is this open??

Every language is already assigned.

**Comment by Nivedita967** [comment]
@saimanoharhm Are you working on this?

**Comment by Amit366** [comment]
@Nivedita967 since only few days are left please assign it to me.

**Comment by Nivedita967** [comment]
> @Nivedita967 since only few days are left, could you please assign it to me.

I can assign you to other issues for sure. In which language you code?

**Comment by saimanoharhm** [comment]
@Nivedita967 I am not working on this. Pls assign this someone else Thank you.

**Comment by Amit366** [comment]
@Nivedita967 can I work in C++??

**Comment by Nivedita967** [comment]
> @Nivedita967 can I work in C++??

Sure @Amit366 Go for it.
