### ISSUE TITLE
Small Triangles, Large Triangles

### ISSUE THREAD

**Issue by saimanoharhm** [Nivedita967/Data-Structure-and-Algorithms#686]
### Problem Link 
https://www.hackerrank.com/challenges/small-triangles-large-triangles/problem

### Coding platform
Hackerrank

### Programming language

- [x] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by saimanoharhm** [comment]
@Nivedita967 Could you pls assign this for me. I will work on c++

**Comment by Sriram-bb63** [comment]
@Nivedita967 I would like to work on this using python

**Comment by saimanoharhm** [comment]
@Nivedita967 I will work on c. Pls change it to c
