### ISSUE TITLE
No Time to wait on codechef

### ISSUE THREAD

**Issue by kmryashasvi** [Nivedita967/Data-Structure-and-Algorithms#687]
### Problem Link 
https://www.codechef.com/MARCH21C/submit/NOTIME
### Coding platform
Codechef

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [ ] Python

**Comment by kmryashasvi** [comment]
I would like to provide code in c++

**Comment by jasmine1601** [comment]
@Nivedita967 I want to solve this in Java.

**Comment by TechSpiritSS** [comment]
I can do this in C
