### ISSUE TITLE
Closest Dessert Cost

### ISSUE THREAD

**Issue by rahil-1407** [Nivedita967/Data-Structure-and-Algorithms#688]
### Problem Link 
https://leetcode.com/problems/closest-dessert-cost/

### Coding platform
LeetCode

### Programming language

- [x] C
- [x] C++
- [x] Java
- [ ] Python

### Additional context (OPTIONAL)
Med Level Problem

**Comment by rahil-1407** [comment]
Assign me in C++.

**Comment by muthuannamalai12** [comment]
I would love to implement in python as a part of Cross-woc. Kindly assign it to me.

**Comment by abhinav5481** [comment]
Hi @Nivedita967 
I would like to solve it  in Java. Please assign it to me.

**Comment by Nivedita967** [comment]
Sure @abhinav5481

**Comment by pri1311** [comment]
will do it in C

**Comment by Nivedita967** [comment]
@muthuannamalai12 I have requested you some changes in your PR. Check it ASAP.

**Comment by abhinav5481** [comment]
Hi @Nivedita967 
Can I solve it in C?

**Comment by Amit366** [comment]
@Nivedita967 is it open??

**Comment by Nivedita967** [comment]
> @Nivedita967 is it open??

No.
