### ISSUE TITLE
The Longest Common Subsequence

### ISSUE THREAD

**Issue by weirdrag08** [Nivedita967/Data-Structure-and-Algorithms#689]
### Problem Link 
https://www.hackerrank.com/challenges/dynamic-programming-classics-the-longest-common-subsequence/problem

### Coding platform
Hackerrank 

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [x] Python

**Comment by weirdrag08** [comment]
Please review this problem and assign me in C++ ;-)

**Comment by ishikabansal04** [comment]
I want to work on this issue in Java.

**Comment by pri1311** [comment]
can i do it in python?

**Comment by JASKAMAL22** [comment]
Hello @Nivedita967  Can I work it in python!!

**Comment by Nivedita967** [comment]
@pri1311 has still so many pending issues. So @JASKAMAL22 Go for Python.
