### ISSUE TITLE
Array reversal

### ISSUE THREAD

**Issue by deephunt3r** [Nivedita967/Data-Structure-and-Algorithms#691]
### Problem Link 
https://www.hackerrank.com/challenges/reverse-array-c/problem

### Coding platform
HackerRank

### Programming language

- [X] C
- [x] C++
- [x] Java
- [x] Python

### Additional context (OPTIONAL)
I would like to solve it using c

**Comment by kmryashasvi** [comment]
I will do it in python

**Comment by muthuannamalai12** [comment]
@Nivedita967 I would love to implement it in java. Kindly assign it to me.

**Comment by pri1311** [comment]
Please assign this to me for C++

**Comment by Nivedita967** [comment]
@pri1311 Go for it.

**Comment by abhinav5481** [comment]
Hi @Nivedita967 
Is this issue still open? Can I get assigned to any language?
