### ISSUE TITLE
sum of elements in the array

### ISSUE THREAD

**Issue by deephunt3r** [Nivedita967/Data-Structure-and-Algorithms#692]
### Problem Link 
https://www.hackerrank.com/challenges/1d-arrays-in-c/problem

### Coding platform
Hackerrank

### Programming language

- [X] C
- [x] C++
- [ ] Java
- [x] Python

### Additional context (OPTIONAL)
I would like to solve in c lang. could you please assign it to me

**Comment by kmryashasvi** [comment]
I would like to do it in python

**Comment by chiragagrawal9200** [comment]
i want to contribute....please let me know if i can?...i am crosswoc participant

**Comment by muthuannamalai12** [comment]
@Nivedita967 Can I implement it in java as a part of Cross-woc. Kindly assign it to me.

**Comment by Nivedita967** [comment]
> i want to contribute....please let me know if i can?...i am crosswoc participant

@chiragagrawal9200 Please tell your language in which you want to code.

**Comment by chiragagrawal9200** [comment]
> > i want to contribute....please let me know if i can?...i am crosswoc participant
> 
> @chiragagrawal9200 Please tell your language in which you want to code.
> This issue is currently open for C++ only

yes ....i can code this in c++.....please let  me know @Nivedita967

**Comment by Nivedita967** [comment]
Sure @chiragagrawal9200 Go for it :)

**Comment by chiragagrawal9200** [comment]
@Nivedita967 where I need to code? like I can see a link upwards...I need to code on that link only or something else?

**Comment by chiragagrawal9200** [comment]
@Nivedita967 and it is showing C lanuage

**Comment by Nivedita967** [comment]
@chiragagrawal9200 You have to code from yourself in C++ language such that it can pass all the test cases. You can use V S code.

**Comment by chiragagrawal9200** [comment]
> @chiragagrawal9200 You have to code from yourself in C++ language such that it can pass all the test cases. You can use V S code.

@Nivedita967 but the test code is in C language. What should I do?

**Comment by Nivedita967** [comment]
Yes, You can use vs code or other editors for writing code.

**Comment by chiragagrawal9200** [comment]
> Yes, You can use vs code or other editors for writing code.

@Nivedita967 You did not get my doubt. This issue is stated to be in C language but you are asking to do it in C++. So in which language should I code?

**Comment by Nivedita967** [comment]
Yes, This question is of C language but if you got the question you can code it in any language, isn't it?

**Comment by chiragagrawal9200** [comment]
> Yes, This question is of C language but if you got the question you can code it in any language, isn't it?

Yes!

**Comment by Nivedita967** [comment]
And C and C++ is almost same. So, Go for it :)

**Comment by chiragagrawal9200** [comment]
> And C and C++ is almost same. So, Go for it :)

I have requested a pull request. Please see @Nivedita967
