### ISSUE TITLE
Fit squares in triangle problem 

### ISSUE THREAD

**Issue by sayantikag98** [Nivedita967/Data-Structure-and-Algorithms#703]
### Problem Link 
https://www.codechef.com/problems/TRISQ

### Coding platform
CodeChef

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by sayantikag98** [comment]
I want to do this in C++. 
Please assign this problem to me.

Thank You.

**Comment by Nivedita967** [comment]
@sayantikag98 Go for it :)

**Comment by sayantikag98** [comment]
Sure

**Comment by sayantikag98** [comment]
#726 Added the solution code for the problem
