### ISSUE TITLE
Number Mirror problem of codechef

### ISSUE THREAD

**Issue by kmryashasvi** [Nivedita967/Data-Structure-and-Algorithms#71]
I would add solutions in C and in C++ both
(Only small differences are there in both the languages, so they can be submitted simultaneously)
Under crosswoc

**Comment by Nivedita967** [comment]
@kmryashasvi Please provide link to the problem you want to work.

**Comment by kmryashasvi** [comment]
sorry, I forgot to mention that
[Number Mirror](https://www.codechef.com/problems/START01)

**Comment by kmryashasvi** [comment]
I have added the files
i have nothing to do more
can we now close this issue?

**Comment by Nivedita967** [comment]
This issue is open for python.

**Comment by kmryashasvi** [comment]
I would like to add its python code,
It will not take much time Just two lines of code is required to execute it

**Comment by kmryashasvi** [comment]
Can i go ahead to app python code @Nivedita967

**Comment by kmryashasvi** [comment]
Done
