### ISSUE TITLE
Minimum Insertion Steps to Make a String Palindrome

### ISSUE THREAD

**Issue by greenblade29** [Nivedita967/Data-Structure-and-Algorithms#722]
### Problem Link 
https://leetcode.com/problems/minimum-insertion-steps-to-make-a-string-palindrome/

### Coding platform
Leetcode

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [x] Python

### Additional context (OPTIONAL)
I want to solve it in Java

**Comment by kanak22** [comment]
I would like to do this in C++.

**Comment by kmryashasvi** [comment]
I will do it in Python

**Comment by Amit366** [comment]
@Nivedita967 can I do in C?

**Comment by abhinav5481** [comment]
Hi @Nivedita967 
I would like to solve it in Java. Please assign it to me.

**Comment by arbazalam01** [comment]
can i do it in python

**Comment by Nivedita967** [comment]
> can i do it in python

python is not open for this issue.

**Comment by Nivedita967** [comment]
> Hi @Nivedita967
> I would like to solve it in Java. Please assign it to me.

Java is not open for this issue.

**Comment by kmryashasvi** [comment]
I will provide solution once the previous prs got merged
