### ISSUE TITLE
Longest Chunked Palindrome Decomposition

### ISSUE THREAD

**Issue by greenblade29** [Nivedita967/Data-Structure-and-Algorithms#723]
### Problem Link 
https://leetcode.com/problems/longest-chunked-palindrome-decomposition/

### Coding platform
Leetcode

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [x] Python

### Additional context (OPTIONAL)
I want to solve it in Java

**Comment by kanak22** [comment]
I would like to do this in C++.

**Comment by kmryashasvi** [comment]
I will do it in python

**Comment by Amit366** [comment]
@Nivedita967 can I work in C??

**Comment by arbazalam01** [comment]
can i do it in python

**Comment by Nivedita967** [comment]
> can i do it in python

Python is not open.
