### ISSUE TITLE
Longest Palindromic Subsequence

### ISSUE THREAD

**Issue by greenblade29** [Nivedita967/Data-Structure-and-Algorithms#724]
### Problem Link 
https://leetcode.com/problems/longest-palindromic-subsequence/

### Coding platform
Leetcode

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [x] Python

### Additional context (OPTIONAL)
I want to solve it in Java

**Comment by kanak22** [comment]
I would like to do this in C++.

**Comment by kmryashasvi** [comment]
I will do it in python

**Comment by abhinav5481** [comment]
Hi @Nivedita967 
I would like to solve it in C. Please assign it to me.

**Comment by Nivedita967** [comment]
> Hi @Nivedita967
> I would like to solve it in C. Please assign it to me.

Sure @abhinav5481
