### ISSUE TITLE
Compare the Strings by frequency of the smallest characters

### ISSUE THREAD

**Issue by abhinav5481** [Nivedita967/Data-Structure-and-Algorithms#728]
### Problem Link 
Compare the Strings by frequency of the smallest characters
https://leetcode.com/problems/compare-strings-by-frequency-of-the-smallest-character/

### Coding platform
Leetcode

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [x] Python

**Comment by abhinav5481** [comment]
Hi @Nivedita967 
I would like to solve this problem in Java. PLease assign it to me.

**Comment by kanak22** [comment]
I would like to do this in C++.

**Comment by kmryashasvi** [comment]
I will do it in python
