### ISSUE TITLE
K-diff Pairs in an Array

### ISSUE THREAD

**Issue by abhinav5481** [Nivedita967/Data-Structure-and-Algorithms#729]
### Problem Link 
https://leetcode.com/problems/k-diff-pairs-in-an-array/

### Coding platform
Leetcode

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [x] Python

**Comment by abhinav5481** [comment]
Hi @Nivedita967 
I would like to work on this problem in Java. Please assign it to me.

**Comment by kanak22** [comment]
I would like to do this in C++.

**Comment by kmryashasvi** [comment]
I will do it in python
