### ISSUE TITLE
House Robber

### ISSUE THREAD

**Issue by greenblade29** [Nivedita967/Data-Structure-and-Algorithms#73]
Problem link : https://leetcode.com/problems/house-robber/ from Leetcode using Dynamic Programming

Programming Language:
- [ ] C
- [x] C++
- [x] Java
- [ ] Python

**Comment by greenblade29** [comment]
@Nivedita967 can you please verify it and assign it to me

**Comment by Nivedita967** [comment]
@greenblade29 Go for it. In which language you are doing ?

**Comment by greenblade29** [comment]
I am doing it int Java

**Comment by Nivedita967** [comment]
Open in C, C++ and Python.

**Comment by greenblade29** [comment]
I will do it in C++ @Nivedita967

**Comment by Nivedita967** [comment]
@greenblade29 Sure.

**Comment by saksham-s1ngh** [comment]
Can I solve this using Python?

**Comment by Nivedita967** [comment]
@saksham-s1ngh are you working on this?

**Comment by saksham-s1ngh** [comment]
> @saksham-s1ngh are you working on this? 

Yes, I'm sorry, the whole thing about my repo being behind, caused me to stop so as to not break the original repo.
I'll do a PR by tomorrow or tonight.

**Comment by Nivedita967** [comment]
@saksham-s1ngh ???

**Comment by kiruba-r11** [comment]
@Nivedita967 I would love to work in C and Python

**Comment by saksham-s1ngh** [comment]
Hey, I'd like to complete this in Python. @Nivedita967

**Comment by Nivedita967** [comment]
@saksham-s1ngh then complete this ASAP.
