### ISSUE TITLE
Decoding Strings

### ISSUE THREAD

**Issue by abhinav5481** [Nivedita967/Data-Structure-and-Algorithms#730]
### Problem Link 
https://leetcode.com/problems/decode-string/

### Coding platform
Leetcode

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [x] Python

**Comment by abhinav5481** [comment]
Hi @Nivedita967 
I would like to work on it using Python. Please assign it to me.

**Comment by kanak22** [comment]
I would like to do this in C++.

**Comment by kmryashasvi** [comment]
I will do it in python

**Comment by Nivedita967** [comment]
> I will do it in python

Python is not open.

**Comment by simonnepinto** [comment]
I want to solve this in Java

**Comment by Nivedita967** [comment]
Go for it @simonnepinto.
