### ISSUE TITLE
Divisible Sum pairs

### ISSUE THREAD

**Issue by stlyash** [Nivedita967/Data-Structure-and-Algorithms#738]
### Problem Link 
https://www.hackerrank.com/challenges/divisible-sum-pairs/problem

### Coding platform
Hackerrank

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [ ] Python

**Comment by kmryashasvi** [comment]
I will provide code in C++

**Comment by TechSpiritSS** [comment]
I can do this in C

**Comment by jasmine1601** [comment]
@Nivedita967 I want to solve this in Java.

**Comment by Nivedita967** [comment]
> @Nivedita967 I want to solve this in Java.

Sure @jasmine1601 Go for it.

**Comment by pri1311** [comment]
will do it in python

**Comment by Nivedita967** [comment]
@TechSpiritSS Are you working??

**Comment by Nivedita967** [comment]
> will do it in python

Go for it @pri1311

**Comment by abhinav5481** [comment]
Hi @Nivedita967
Is this issue still open? Can I solve it in C?

**Comment by TechSpiritSS** [comment]
> @TechSpiritSS Are you working??

I was having my end sems
