### ISSUE TITLE
Migratory birds problem

### ISSUE THREAD

**Issue by kmryashasvi** [Nivedita967/Data-Structure-and-Algorithms#739]
### Problem Link 
https://www.hackerrank.com/challenges/migratory-birds/problem

### Coding platform
Hackerrank

### Programming language

- [x] C
- [x] C++
- [ ] Java
- [x] Python

**Comment by kmryashasvi** [comment]
I will be providing solution in C++

**Comment by Akash20x** [comment]
I will solve it in python

**Comment by TechSpiritSS** [comment]
I  can do this in C

**Comment by Akash20x** [comment]
Please check my pull request

**Comment by simonnepinto** [comment]
Can I solve this in Java?

**Comment by Akash20x** [comment]
Please check my pull request

**Comment by Nivedita967** [comment]
Sure @simonnepinto Go for it.
