### ISSUE TITLE
Students Marks Sum

### ISSUE THREAD

**Issue by saimanoharhm** [Nivedita967/Data-Structure-and-Algorithms#746]
### Problem Link 
Mention the problem on which you want to work on
https://www.hackerrank.com/challenges/students-marks-sum/problem

### Coding platform
Mention the coding platform from where you have picked the problem
Hackerrank
### Programming language

- [x] C
- [x] C++
- [x] Java
- [x] Python

**Comment by saimanoharhm** [comment]
@Nivedita967 I would like work on this problem using c. Pls assign this to me.

**Comment by pri1311** [comment]
please assign this to me for c++ under crosswoc

**Comment by kmryashasvi** [comment]
I will do it in python

**Comment by pri1311** [comment]
Can I do this in Java too?

**Comment by Nivedita967** [comment]
> Can I do this in Java too?

Go for it.

**Comment by Nivedita967** [comment]
@saimanoharhm Are you working on this?

**Comment by saimanoharhm** [comment]
@Nivedita967 Sorry, Becz of my exams I didn't spend much time on it. I will submit the code by today.

**Comment by Nivedita967** [comment]
> @Nivedita967 Sorry, Becz of my exams I didn't spend much time on it. I will submit the code by today.

I can understand. I also have exams :/ 
But try to solve one issue atleast in a day.
