### ISSUE TITLE
Bitwise Operators

### ISSUE THREAD

**Issue by bharth-stack** [Nivedita967/Data-Structure-and-Algorithms#749]
### Problem Link 
Mention the problem on which you want to work on
https://www.hackerrank.com/challenges/bitwise-operators-in-c/problem

### Coding platform
Mention the coding platform from where you have picked the problem
Hackerrank

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [x] Python

**Comment by bharth-stack** [comment]
@Nivedita967 I would like to work on this please permit me to do this

**Comment by bharth-stack** [comment]
I want work on this by using C

**Comment by Nivedita967** [comment]
Sure @bharth-stack Go for it :)

**Comment by pri1311** [comment]
Please assign this to me for C++

**Comment by kmryashasvi** [comment]
I will do it in python

**Comment by Nivedita967** [comment]
@kmryashasvi Do you also have exams?

**Comment by kmryashasvi** [comment]
I have Exams, but I manage to do other things too,
but the main reason is, I am not able to solve the problem, 
Hence, I am unassigning myself now.
I hope you understand

**Comment by pri1311** [comment]
if it is open, will do it in python

**Comment by Nivedita967** [comment]
> if it is open, will do it in python

Go for it.

**Comment by abhinav5481** [comment]
Hi @Nivedita967
Is this issue still open?

**Comment by Nivedita967** [comment]
> Hi @Nivedita967
> Is this issue still open?

Yes @abhinav5481 This is open for Java.

**Comment by Nivedita967** [comment]
@bharth-stack Are you unable to work ?

**Comment by abhinav5481** [comment]
> > Hi @Nivedita967
> > Is this issue still open?
> 
> Yes @abhinav5481 This is open for Java.
Can I go ahead?

**Comment by Nivedita967** [comment]
> > > Hi @Nivedita967
> > > Is this issue still open?
> > 
> > 
> > Yes @abhinav5481 This is open for Java.
> 
> Can I go ahead?

Sure @abhinav5481
