### ISSUE TITLE
All Elements in Two Binary Search Trees

### ISSUE THREAD

**Issue by abhinav5481** [Nivedita967/Data-Structure-and-Algorithms#760]
### Problem Link 
https://leetcode.com/problems/all-elements-in-two-binary-search-trees/

### Coding platform
Leetcode

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [ ] Python

**Comment by abhinav5481** [comment]
Hi @Nivedita967 
I would like to work on it in Java as part of crossWoc'21. Could you please assign it to me?

**Comment by kanak22** [comment]
I would like to do this in C++.

**Comment by kmryashasvi** [comment]
I will do it in python

**Comment by Nivedita967** [comment]
> I will do it in python

Here also check your PR.

**Comment by stlyash** [comment]
> > I will do it in python
> 
> Here also check your PR @stlyash

Done, Please recheck it
