### ISSUE TITLE
Count Number of Teams

### ISSUE THREAD

**Issue by abhinav5481** [Nivedita967/Data-Structure-and-Algorithms#761]
### Problem Link 
https://leetcode.com/problems/count-number-of-teams/

### Coding platform
Leetcode

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [x] Python

**Comment by abhinav5481** [comment]
Hi @Nivedita967 
I would like to work on it in Java. Please assign it to me as part of crosswoc'21

**Comment by kanak22** [comment]
I would like to do this in C++.

**Comment by kmryashasvi** [comment]
Can I do it in python?

**Comment by Amit366** [comment]
@Nivedita967 can I do it in C??

**Comment by Nivedita967** [comment]
> @Nivedita967 can I do it in C??

Sure @Amit366 Go for it.
