### ISSUE TITLE
Minimum Add to Make Parentheses Valid

### ISSUE THREAD

**Issue by abhinav5481** [Nivedita967/Data-Structure-and-Algorithms#762]
### Problem Link 
https://leetcode.com/problems/minimum-add-to-make-parentheses-valid/

### Coding platform
Leetcode

### Programming language

- [x] C
- [x] C++
- [x] Java
- [x] Python

**Comment by abhinav5481** [comment]
Hi @Nivedita967 
I would like to work on it in Java as part of crosswoc'21 challenge. Please assign it to me.

**Comment by kanak22** [comment]
I would like to do this in C++.

**Comment by kmryashasvi** [comment]
I will do it in python

**Comment by Nivedita967** [comment]
@Amit366 Can you solve this problem ?

**Comment by Amit366** [comment]
Yes

**Comment by Amit366** [comment]
@Nivedita967 which language is open?

**Comment by kmryashasvi** [comment]
> @Nivedita967 which language is open?

C

**Comment by Nivedita967** [comment]
> @Nivedita967 which language is open?

Open for C. Do you want to work on this?

**Comment by Amit366** [comment]
@Nivedita967 please assign it to me

**Comment by Amit366** [comment]
@Nivedita967 please assign this to me
