### ISSUE TITLE
Validate Stack Sequences

### ISSUE THREAD

**Issue by abhinav5481** [Nivedita967/Data-Structure-and-Algorithms#763]
### Problem Link 
https://leetcode.com/problems/validate-stack-sequences/

### Coding platform
Leetcode

### Programming language

- [x] C
- [x] C++
- [x] Java
- [ ] Python

**Comment by abhinav5481** [comment]
Hi @Nivedita967 
I would like to work on it in Java as part of crossWoc'21. Please assign it to me.

**Comment by kanak22** [comment]
I would like to do this in C++.

**Comment by kmryashasvi** [comment]
I will provide code in python

**Comment by Amit366** [comment]
@Nivedita967 can I work in C??

**Comment by Nivedita967** [comment]
Sure @Amit366 Go for it.

**Comment by Nivedita967** [comment]
@kmryashasvi I have requested you some changes in your Pull request. Check that ASAP.

**Comment by kmryashasvi** [comment]
> @kmryashasvi I have requested you some changes in your Pull request. Check that ASAP.

Done
@Nivedita967
