### ISSUE TITLE
Sum Of Digits problem on codechef

### ISSUE THREAD

**Issue by kmryashasvi** [Nivedita967/Data-Structure-and-Algorithms#77]
I would like to add C and C++ Solution of  [Sum Of Dogits](https://www.codechef.com/problems/FLOW006) Problem

**Comment by Nivedita967** [comment]
Java is also done .

**Comment by Mahindra-7** [comment]
@Nivedita967  i would like to go with python

**Comment by Nivedita967** [comment]
@Mahindra-7 Go for it.

**Comment by TechSpiritSS** [comment]
Is this code open for C or C++

**Comment by kmryashasvi** [comment]
@TechSpiritSS  I have added solutions in c and c++

**Comment by TechSpiritSS** [comment]
> @TechSpiritSS  I have added solutions in c and c++ 

Well that's great but use one language so that I can also contribute 😂
