### ISSUE TITLE
Sort integers by power value-leetcode

### ISSUE THREAD

**Issue by pri1311** [Nivedita967/Data-Structure-and-Algorithms#773]
### Problem Link 
https://leetcode.com/problems/sort-integers-by-the-power-value  difficulty : medium

### Coding platform
leetcode

### Programming language

- [x] C
- [x] C++
- [x] Java
- [ ] Python

### Additional context (OPTIONAL)
would like to do it in c++ under crosswoc

**Comment by pri1311** [comment]
would like to do it under crosswoc

**Comment by Akash20x** [comment]
I want to solve it in python, please assign me this issue

**Comment by abhinav5481** [comment]
Hi @Nivedita967 
I would like to solve it in Java. Please assign it to me.

**Comment by Amit366** [comment]
@Nivedita967 Can I solve it in C??

**Comment by Amit366** [comment]
@Nivedita967 please review the PRs. Then only I can send this PR.
