### ISSUE TITLE
Binary Tree inorder Traversal

### ISSUE THREAD

**Issue by pri1311** [Nivedita967/Data-Structure-and-Algorithms#774]
### Problem Link 
https://leetcode.com/problems/binary-tree-inorder-traversal

### Coding platform
leetcode

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [x] Python

**Comment by pri1311** [comment]
would like to submit in c++

**Comment by abhinav5481** [comment]
Hi @Nivedita967 
I would like to solve it in Java. Please assign it to me.

**Comment by kmryashasvi** [comment]
I will do it in python

**Comment by pri1311** [comment]
will do it in C
