### ISSUE TITLE
Find peak element

### ISSUE THREAD

**Issue by pri1311** [Nivedita967/Data-Structure-and-Algorithms#775]
### Problem Link 
https://leetcode.com/problems/find-peak-element

### Coding platform
leetcode

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [x] Python

**Comment by pri1311** [comment]
would like to submit in c++ under crosswoc

**Comment by Amit366** [comment]
@Nivedita967 can I work using Java?

**Comment by abhinav5481** [comment]
Hi @Nivedita967 
I would like to solve it in Python. please assign it to me.

**Comment by pri1311** [comment]
would like to provide solution for c as well

**Comment by Nivedita967** [comment]
> would like to provide solution for c as well

Sure @pri1311 Go for it.
