### ISSUE TITLE
rotate list

### ISSUE THREAD

**Issue by pri1311** [Nivedita967/Data-Structure-and-Algorithms#776]
### Problem Link 
https://leetcode.com/problems/rotate-list

### Coding platform
leetcode

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [ ] Python

**Comment by pri1311** [comment]
would like to submit solution in c++ under crosswoc

**Comment by Amit366** [comment]
@Nivedita967 can I work using Java??

**Comment by Akash20x** [comment]
I want to solve it in python, please assign me this issue as a part of Cross Woc

**Comment by pri1311** [comment]
if it is open, will do it in C
