### ISSUE TITLE
remove-nth-node-from-end-of-list

### ISSUE THREAD

**Issue by pri1311** [Nivedita967/Data-Structure-and-Algorithms#777]
### Problem Link 
https://leetcode.com/problems/remove-nth-node-from-end-of-list

### Coding platform
leetcode

### Programming language

- [x] C
- [x] C++
- [x] Java
- [ ] Python

**Comment by pri1311** [comment]
would like to submit solution in C++ under crosswoc

**Comment by abhinav5481** [comment]
Hi @Nivedita967 
I would like to solve it in Java. please assign it to me.

**Comment by Amit366** [comment]
@Nivedita967 can I solve this in C??

**Comment by pri1311** [comment]
Would like to do it in Python too

**Comment by Amit366** [comment]
@Nivedita967 can I work in python??

**Comment by Kpraful** [comment]
I would like to try it in python.

**Comment by Amit366** [comment]
@Nivedita967 please assign this to me

**Comment by Nivedita967** [comment]
@Amit366 Go for it.
