### ISSUE TITLE
swap nodes in pair

### ISSUE THREAD

**Issue by pri1311** [Nivedita967/Data-Structure-and-Algorithms#778]
### Problem Link 
https://leetcode.com/problems/swap-nodes-in-pairs

### Coding platform
leetcode

### Programming language

- [x] C
- [x] C++
- [x] Java
- [x] Python

**Comment by pri1311** [comment]
would like to submit solution under crosswoc in c++

**Comment by Amit366** [comment]
@Nivedita967 Can I solve it in C??

**Comment by pri1311** [comment]
Would like to do it in Python as well

**Comment by Kpraful** [comment]
I would like to contribute it in python

**Comment by Nivedita967** [comment]
> I would like to contribute it in python

Sure @Kpraful Go for it.
