### ISSUE TITLE
Contributing.md [Enter Your Email]

### ISSUE THREAD

**Issue by kavania2002** [Nivedita967/Data-Structure-and-Algorithms#79]
In contributing.md, there is written [Enter Your Email]. I think you should change it.

**Comment by Nivedita967** [comment]
Hey @kavania2002, Do you want to work on this ?

**Comment by kavania2002** [comment]
How can I work? I mean I don't have your email so I can't add that.

**Comment by Nivedita967** [comment]
My email is available in github profile.

**Comment by kavania2002** [comment]
Yeah ohk, please assign me so I can work upon it.
