### ISSUE TITLE
Rest in Peace (Hacker Rank)

### ISSUE THREAD

**Issue by Mahindra-7** [Nivedita967/Data-Structure-and-Algorithms#80]
https://www.hackerearth.com/practice/algorithms/searching/linear-search/practice-problems/algorithm/rest-in-peace-21-1/
@Nivedita967 i would like to work on  this problem using C++

**Comment by Nivedita967** [comment]
but this problem is from HackerEarth.

**Comment by Mahindra-7** [comment]
@Nivedita967  i have noticed right now , i will close this issue
