### ISSUE TITLE
Interesting XOR! 

### ISSUE THREAD

**Issue by pri1311** [Nivedita967/Data-Structure-and-Algorithms#804]
### Problem Link 
https://www.codechef.com/MARCH21C/problems/IRSTXOR/

### Coding platform
Codechef

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [x] Python

**Comment by pri1311** [comment]
Please assign this to me under crosswoc.

**Comment by abhinav5481** [comment]
@Nivedita967 
I can solve it in Java. Please assign it to me for Java

**Comment by jayantjethi** [comment]
I would Like to Work on this issue in c++.Kindly Assign me.

**Comment by Nivedita967** [comment]
> I would Like to Work on this issue in c++.Kindly Assign me.

C++ is not open.

**Comment by JASKAMAL22** [comment]
Hi @Nivedita967, I would like to work in python. Please assign it to me :)

**Comment by Nivedita967** [comment]
> Hi @Nivedita967, I would like to work in python. Please assign it to me :)

Sure @JASKAMAL22 Go for it.

**Comment by pri1311** [comment]
will do it in C as well

**Comment by Nivedita967** [comment]
> will do it in C as well

Go for it.
