### ISSUE TITLE
minimum-number-of-vertices-to-reach-all-nodes

### ISSUE THREAD

**Issue by pri1311** [Nivedita967/Data-Structure-and-Algorithms#805]
### Problem Link 
https://leetcode.com/problems/minimum-number-of-vertices-to-reach-all-nodes

### Coding platform
Leetcode

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [x] Python

**Comment by pri1311** [comment]
Please assign this to me under crosswoc for c++

**Comment by abhinav5481** [comment]
Hi @Nivedita967 
I would like to work in Java. Please assign it to me.

**Comment by Amit366** [comment]
@Nivedita967 can I solve this in python??
