### ISSUE TITLE
Candies

### ISSUE THREAD

**Issue by pri1311** [Nivedita967/Data-Structure-and-Algorithms#806]
### Problem Link 
https://www.hackerrank.com/challenges/candies/problem

### Coding platform
Hackerrank

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [x] Python

**Comment by pri1311** [comment]
Please assign this to me under crosswoc for c++

**Comment by abhinav5481** [comment]
@Nivedita967 
I would like to solve it in Python. Please assign it to me
In Python

**Comment by pri1311** [comment]
Will do it in C as well

**Comment by Nivedita967** [comment]
> Will do it in C as well

Go for it.
