### ISSUE TITLE
Board Cutting

### ISSUE THREAD

**Issue by pri1311** [Nivedita967/Data-Structure-and-Algorithms#807]
### Problem Link 
https://www.hackerrank.com/challenges/board-cutting/problem

### Coding platform
Hackerrank

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [x] Python

**Comment by pri1311** [comment]
Please assign this to under crosswoc for c++

**Comment by Amit366** [comment]
@Nivedita967 can i work using Java?

**Comment by abhinav5481** [comment]
Hi @Nivedita967 
I would like to solve it in Python. please assign it to me in python

**Comment by Nivedita967** [comment]
> Hi @Nivedita967
> I would like to solve it in Python. please assign it to me in python

Sure @abhinav5481

**Comment by pri1311** [comment]
would like to do it in C too.
