### ISSUE TITLE
Goodland Electricity

### ISSUE THREAD

**Issue by pri1311** [Nivedita967/Data-Structure-and-Algorithms#808]
### Problem Link 
https://www.hackerrank.com/challenges/pylons/problem

### Coding platform
Hackerrank

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [x] Python

**Comment by pri1311** [comment]
Please assign this issue to me under crosswoc for c++

**Comment by Nivedita967** [comment]
Complete all the previous assigned first, then I will assign to these further.

**Comment by Amit366** [comment]
@Nivedita967 my PR isn't reviewed and the issue is closed
