### ISSUE TITLE
Recursive digit sum

### ISSUE THREAD

**Issue by pri1311** [Nivedita967/Data-Structure-and-Algorithms#810]
### Problem Link 
https://www.hackerrank.com/challenges/recursive-digit-sum/problem

### Coding platform
Hackerrank

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [x] Python

**Comment by pri1311** [comment]
Please assign this to me for c++

**Comment by abhinav5481** [comment]
Hi @Nivedita967 
I would like to solve it in Java. Please assign it to me

**Comment by pri1311** [comment]
I can do It in python too. Thank you

**Comment by Amit366** [comment]
@Nivedita967 can I work using python??

**Comment by Nivedita967** [comment]
@pri1311 -> c++
@abhinav5481 -> java
@Amit366 -> python

**Comment by bharth-stack** [comment]
i would like to do it in c

**Comment by Nivedita967** [comment]
> i would like to do it in c

Go for it.

**Comment by Amit366** [comment]
@Nivedita967 can I work in C??

**Comment by Nivedita967** [comment]
> @Nivedita967 can I work in C??

Yes @Amit366

**Comment by Amit366** [comment]
@Nivedita967 please review the PR
