### ISSUE TITLE
top-k-frequent-elements

### ISSUE THREAD

**Issue by pri1311** [Nivedita967/Data-Structure-and-Algorithms#814]
### Problem Link 
https://leetcode.com/problems/top-k-frequent-elements

### Coding platform
Leetcode

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [x] Python

**Comment by pri1311** [comment]
Would like to submit solution for python and c++

**Comment by abhinav5481** [comment]
Hi @Nivedita967 
I would like to solve this in Java. Please assign it to me

**Comment by Amit366** [comment]
@Nivedita967 can I work in C and python??

**Comment by Nivedita967** [comment]
@pri1311      ->c++
@abhinav5481 -> java
@Amit366     ->python.

**Comment by Amit366** [comment]
@Nivedita967 can I work in C??
