### ISSUE TITLE
the-kth-factor-of-n

### ISSUE THREAD

**Issue by pri1311** [Nivedita967/Data-Structure-and-Algorithms#815]
### Problem Link 
https://leetcode.com/problems/the-kth-factor-of-n

### Coding platform
Leetcode

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [x] Python

**Comment by pri1311** [comment]
Would like to provide solutions for python and c++

**Comment by Amit366** [comment]
@Nivedita967 can I work using python??

**Comment by Nivedita967** [comment]
@pri1311 ->c++
@abhinav5481 -> java
@Amit366 -> python

**Comment by bharth-stack** [comment]
i can provide solution in c

**Comment by Nivedita967** [comment]
> i can provide solution in c

Sure @bharth-stack

**Comment by abhinav5481** [comment]
Hi,
Can I try solving it in C?

**Comment by Nivedita967** [comment]
> Hi,
> Can I try solving it in C?

Sure Go for it @abhinav5481
