### ISSUE TITLE
single-number

### ISSUE THREAD

**Issue by pri1311** [Nivedita967/Data-Structure-and-Algorithms#824]
### Problem Link 
https://leetcode.com/problems/single-number

### Coding platform
Leetcode

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [x] Python

**Comment by pri1311** [comment]
Would like to provide solution for python, C++ and Java

**Comment by Nivedita967** [comment]
@pri1311 Go for C++

**Comment by bharth-stack** [comment]
i would like to do it in C

**Comment by Nivedita967** [comment]
> i would like to do it in C

Go for it @bharth-stack

**Comment by JASKAMAL22** [comment]
I would like to work in python . Kindly assign it to me :)

**Comment by abhinav5481** [comment]
Hi @Nivedita967
Is this issue still open? Can I solve it in C?

**Comment by Nivedita967** [comment]
> Hi @Nivedita967
> Is this issue still open? Can I solve it in C?

Go for it @abhinav5481
