### ISSUE TITLE
Red Knight's Shortest Path

### ISSUE THREAD

**Issue by ishikabansal04** [Nivedita967/Data-Structure-and-Algorithms#826]
### Problem Link 
https://www.hackerrank.com/challenges/red-knights-shortest-path/problem

### Coding platform
Hackerrank

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [x] Python

**Comment by ishikabansal04** [comment]
Please review this problem and assign me in Java.

**Comment by weirdrag08** [comment]
I want to work on this in C++.

**Comment by JASKAMAL22** [comment]
I would like to work in python . Kindly assign it to me!!

**Comment by Nivedita967** [comment]
> I would like to work in python . Kindly assign it to me!!

Sure @JASKAMAL22

**Comment by pri1311** [comment]
Can I do it in C?

**Comment by Nivedita967** [comment]
@weirdrag08 Are you working on this?

**Comment by weirdrag08** [comment]
> @weirdrag08 Are you working on this?

Yes, I am working on this .

**Comment by abhinav5481** [comment]
Hi @Nivedita967 
Can I solve it in C?

**Comment by Amit366** [comment]
@Nivedita967 can I work in C??

**Comment by abhinav5481** [comment]
@Nivedita967 
You assigned me this issue 5mins ago. I think it got unassigned by mistake. Please reassign it to me for c

> Hi @Nivedita967
> Can I solve it in C?

@Nivedita967 
You assigned me this issue 5 mins ago, I think it got unassigned by mistake. please reassign it

**Comment by abhinav5481** [comment]
> Hi @Nivedita967
> Can I solve it in C?

@Nivedita967
You assigned me this issue 5 mins ago, I think it got unassigned by mistake. please reassign it

**Comment by Nivedita967** [comment]
> @Nivedita967 can I work in C??

Not open.

**Comment by Nivedita967** [comment]
> > Hi @Nivedita967
> > Can I solve it in C?
> 
> @Nivedita967
> You assigned me this issue 5 mins ago, I think it got unassigned by mistake. please reassign it

Nope, You are still assigned.
