### ISSUE TITLE
Jump Game V

### ISSUE THREAD

**Issue by greenblade29** [Nivedita967/Data-Structure-and-Algorithms#828]
### Problem Link 
https://leetcode.com/problems/jump-game-v/

### Coding platform
Leetcode

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [x] Python

### Additional context (OPTIONAL)
I want to solve it in Java

**Comment by kanak22** [comment]
I would like to work on this in c++

**Comment by abhinav5481** [comment]
Hi @Nivedita967 
I would like to solve this problem in Java. Please assign it to me in Java

**Comment by Nivedita967** [comment]
> Hi @Nivedita967
> I would like to solve this problem in Java. Please assign it to me in Java

Sorry, @abhinav5481 Java is not open.

**Comment by Amit366** [comment]
@Nivedita967 can I work in python??

**Comment by pri1311** [comment]
will do it in C

**Comment by abhinav5481** [comment]
Hi @Nivedita967 
Can I do it in C?

**Comment by Nivedita967** [comment]
@pri1311 Are you working for C?

**Comment by abhinav5481** [comment]
Hi @Nivedita967 
If it is open please assign it to me for C.

**Comment by Amit366** [comment]
@Nivedita967 if it is open please assign it to me.

**Comment by Nivedita967** [comment]
> Hi @Nivedita967
> If it is open please assign it to me for C.

Sure Go for it @abhinav5481
