### ISSUE TITLE
Pascal's Triangle

### ISSUE THREAD

**Issue by rahil-1407** [Nivedita967/Data-Structure-and-Algorithms#839]
### Problem Link 
https://leetcode.com/problems/pascals-triangle/

### Coding platform
LeetCode

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [x] Python

### Additional context (OPTIONAL)
Easy Array Question.

**Comment by rahil-1407** [comment]
Assign me in C++.

**Comment by pri1311** [comment]
will do this in python

**Comment by pri1311** [comment]
can I do it in java now?

**Comment by abhinav5481** [comment]
Hi @Nivedita967 
I would like to solve it in Java or C. please assign it to me in whichever language it is open.

**Comment by Nivedita967** [comment]
> Hi @Nivedita967
> I would like to solve it in Java or C. please assign it to me in whichever language it is open.

Go for Java.
