### ISSUE TITLE
Sort Colors

### ISSUE THREAD

**Issue by rahil-1407** [Nivedita967/Data-Structure-and-Algorithms#840]
### Problem Link 
https://leetcode.com/problems/sort-colors/

### Coding platform
LeetCode

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [x] Python

### Additional context (OPTIONAL)
Tricky to solve in O(n)

**Comment by rahil-1407** [comment]
Assign me in C++

**Comment by bharth-stack** [comment]
i would like to do it on c

**Comment by pri1311** [comment]
Will do it in python

**Comment by pri1311** [comment]
now can I solve in Java now?

**Comment by abhinav5481** [comment]
Hi @Nivedita967 
I would like to solve this problem in Java. Please assign it to me in Java.

**Comment by Nivedita967** [comment]
> now can I solve in Java now?

Why are you in so hurry?

**Comment by Nivedita967** [comment]
> Hi @Nivedita967
> I would like to solve this problem in Java. Please assign it to me in Java.

Go for it @abhinav5481

**Comment by pri1311** [comment]
@Nivedita967  ma'am isnt it supposed to be first come first serve basis?

**Comment by Nivedita967** [comment]
> @Nivedita967 ma'am isnt it supposed to be first come first serve basis?

Yes @pri1311, But you are just collecting all the issues, in all languages. Is it right?
You are here to learn and for contribution ( contribution is collaborating and cooperating with community) but you are not supporting community in any way.

**Comment by pri1311** [comment]
@Nivedita967, ma'am I am creating pull requests on time with properly commented code. I understand your point but my intention is not to collect issues and stop others.

**Comment by pri1311** [comment]
@Nivedita967 Sorry for the trouble :(

**Comment by Nivedita967** [comment]
> @Nivedita967 Sorry for the trouble :(

Just collaborate with the community :)
For other things, you are doing great.

**Comment by cryptus-neoxys** [comment]
Can you reassign C++, no submission has been made by the assignee.

**Comment by abhinav5481** [comment]
Hi @Nivedita967
Is this issue still open? Can I solve it in C?

**Comment by Amit366** [comment]
@Nivedita967 can I solve in C??

**Comment by Nivedita967** [comment]
@abhinav5481 I have assigned you some issues. So @Amit366 You go for C.
