### ISSUE TITLE
Counting Number of Inversions

### ISSUE THREAD

**Issue by pri1311** [Nivedita967/Data-Structure-and-Algorithms#843]
### Problem Link 
https://www.hackerrank.com/challenges/ctci-merge-sort/problem

### Coding platform
Hackerrank

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [ ] Python

### Additional context (OPTIONAL)
Trick to do it in O(nlogn) time using divide and conquer.

**Comment by pri1311** [comment]
Can submit solution for python and c++

**Comment by abhinav5481** [comment]
@Nivedita967 
I would like to solve it in Java. Please assign it to me in Java.

**Comment by abhinav5481** [comment]
@Nivedita967 
Is this issue still open?

**Comment by Nivedita967** [comment]
> @Nivedita967
> Is this issue still open?

Yes, Go for it.

**Comment by JASKAMAL22** [comment]
I would like to work in python. Kindly assign it to me :)

**Comment by pri1311** [comment]
will do it in C++

**Comment by kanak22** [comment]
can i work on this in C++?

**Comment by JASKAMAL22** [comment]
Hello @Nivedita967 , Please review the PR and let me know if any change is required. :)

**Comment by Nivedita967** [comment]
> will do it in C++ if issue still open

I have assigned you issues, please complete them.

**Comment by Nivedita967** [comment]
> can i work on this in C++?

@kanak22 You go ahead for C++

**Comment by Nivedita967** [comment]
@JASKAMAL22 I have requested changes in your pull request. Check it ASAP.

**Comment by Amit366** [comment]
@Nivedita967 can I work in C??
