### ISSUE TITLE
Move Zeroes

### ISSUE THREAD

**Issue by jayantjethi** [Nivedita967/Data-Structure-and-Algorithms#844]
### Problem Link 
https://leetcode.com/problems/move-zeroes/

### Coding platform
Leetcode

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [x] Python

**Comment by jayantjethi** [comment]
@Nivedita967  Mam I would like to solve in c++.Kindly Assign me.

**Comment by pri1311** [comment]
Would like to submit solution for java and python

**Comment by Nivedita967** [comment]
@pri1311 You can work on only one language at a time.

**Comment by pri1311** [comment]
Even if I create different PRs?

**Comment by Nivedita967** [comment]
> Even if I create different PRs?

Yes, At a time, You can work on one language only.

**Comment by JASKAMAL22** [comment]
I would like to work in python. Please assign it to me :)

**Comment by pri1311** [comment]
Done with Python, can I work on Java now?

**Comment by pri1311** [comment]
would like to work on Python

**Comment by Nivedita967** [comment]
> I would like to work in python. Please assign it to me :)

Python is not open for this.

**Comment by pri1311** [comment]
Can I work on Java now?

**Comment by bharth-stack** [comment]
i would like to do it in C

**Comment by Nivedita967** [comment]
> Can I work on Java now?

You have not yet completed all your previous works.

**Comment by abhinav5481** [comment]
Hi @Nivedita967
Is this issue still open? Can I solve it in Java or C?

**Comment by abhinav5481** [comment]
Is this issue still open?

**Comment by Nivedita967** [comment]
> Hi @Nivedita967
> Is this issue still open? Can I solve it in Java or C?

Go for Java @abhinav5481
