### ISSUE TITLE
Water Bottles

### ISSUE THREAD

**Issue by pri1311** [Nivedita967/Data-Structure-and-Algorithms#845]
### Problem Link 
https://leetcode.com/problems/water-bottles/

### Coding platform
Leetcode

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by pri1311** [comment]
Provide solutions in all 4 languages

**Comment by Abhinav0909** [comment]
HI,@Nivedita967 I want to work on this issue in java.
