### ISSUE TITLE
Running sum of 1d array

### ISSUE THREAD

**Issue by pri1311** [Nivedita967/Data-Structure-and-Algorithms#847]
### Problem Link 
https://leetcode.com/problems/running-sum-of-1d-array/

### Coding platform
leetcode

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [x] Python

**Comment by pri1311** [comment]
Would like to submit solutions in all 4 languages.

**Comment by Abhinav0909** [comment]
Hi,@Nivedita967 I want to work on this issue in java

**Comment by Nivedita967** [comment]
@Abhinav0909 Go for it.

**Comment by pri1311** [comment]
@Nivedita967  Ma'am why was I not assigned this?

**Comment by jayantjethi** [comment]
Mam I would like to solve this in c++. kindly assign me

**Comment by pri1311** [comment]
would like to do it in C++

**Comment by Nivedita967** [comment]
> @Nivedita967 Ma'am why was I not assigned this?

Yes @pri1311 You have opened so many issues at the same time, but you can't assigned to so many issues at a time. You should complete all your previous works first to get assigned to further issues.

**Comment by Nivedita967** [comment]
> Mam I would like to solve this in c++. kindly assign me

Sure @jayantjethi Go for c++

**Comment by Nivedita967** [comment]
@jayantjethi Are you working on this?

**Comment by abhinav5481** [comment]
Hi @Nivedita967
Is this issue still open? Can I solve it in C++, Python or C?

**Comment by jayantjethi** [comment]
> @jayantjethi Are you working on this?

Yess Mam.. Check My PR I have Submitted It . Sorry For Getting Late.

**Comment by Nivedita967** [comment]
> Hi @Nivedita967
> Is this issue still open? Can I solve it in C++, Python or C?

Yes @abhinav5481 Go for Python.

**Comment by Amit366** [comment]
@Nivedita967 can I do in Java??
