### ISSUE TITLE
Burst Balloons

### ISSUE THREAD

**Issue by greenblade29** [Nivedita967/Data-Structure-and-Algorithms#85]
Problem link : https://leetcode.com/problems/burst-balloons/ from Leetcode using Dynamic Programming 

Programming Languages:
- [x] C
- [x] C++
- [x] Java 
- [ ] Python

**Comment by greenblade29** [comment]
@Nivedita967 please verify the issue and assign it to me. I will be using Java

**Comment by Nivedita967** [comment]
@greenblade29 go for it.

**Comment by Nivedita967** [comment]
Open for C, C++ and Python.

**Comment by gopichandpuli9** [comment]
I'll implement in C++ and python

**Comment by Nivedita967** [comment]
@gopichandpuli9 Sure, Go for it.

**Comment by Nivedita967** [comment]
@gopichandpuli9 Are you working on this ?

**Comment by gopichandpuli9** [comment]
Yeah I'll do it by tomorrow.

**Comment by Amit366** [comment]
@Nivedita967 can I implement it using C??

**Comment by Nivedita967** [comment]
@Amit366 Sure :)

**Comment by Nivedita967** [comment]
@gopichandpuli9 ???

**Comment by gopichandpuli9** [comment]
I already did it in C++.
JUst check

**Comment by Nivedita967** [comment]
> I already did it in C++.
> JUst check

Are going to implement it in python also or not ?
