### ISSUE TITLE
Edit Distance

### ISSUE THREAD

**Issue by greenblade29** [Nivedita967/Data-Structure-and-Algorithms#856]
### Problem Link 
https://leetcode.com/problems/edit-distance/

### Coding platform
Leetcode

### Programming language

- [x] C
- [ ] C++
- [x] Java
- [x] Python

### Additional context (OPTIONAL)
I want to solve it in Java

**Comment by pri1311** [comment]
Please assign this to me for c++

**Comment by Abhinav0909** [comment]
Hi,@Nivedita967,I want to work on this issues in java.

**Comment by abhinav5481** [comment]
Hi @Nivedita967 
I would like to solve it in Python. Please assign it to me python.

**Comment by Amit366** [comment]
@Nivedita967 can I work in C??

**Comment by Nivedita967** [comment]
> Hi,@Nivedita967,I want to work on this issues in java.

Java is not open for this @Abhinav0909
