### ISSUE TITLE
Final Prices With a Special Discount in a Shop

### ISSUE THREAD

**Issue by abhinav5481** [Nivedita967/Data-Structure-and-Algorithms#876]
### Problem Link 
https://leetcode.com/problems/final-prices-with-a-special-discount-in-a-shop/

### Coding platform
Leetcode

### Programming language

- [x] C
- [ ] C++
- [x] Java
- [x] Python

**Comment by abhinav5481** [comment]
Hi @Nivedita967 
I would like to solve it in Java. Please assign it to me in Java

**Comment by pri1311** [comment]
would solve it in c++

**Comment by Amit366** [comment]
@Nivedita967 can I work in python and C??

**Comment by Nivedita967** [comment]
@abhinav5481 -> java
@pri1311 -> go for c++
@Amit366 -> go for python first

**Comment by Amit366** [comment]
@Nivedita967 now can i work in C??

**Comment by Nivedita967** [comment]
> @Nivedita967 now can i work in C??

Go for it @Amit366

**Comment by Nivedita967** [comment]
@pri1311 Are you working?
