### ISSUE TITLE
Russian Doll Envelopes

### ISSUE THREAD

**Issue by ishikabansal04** [Nivedita967/Data-Structure-and-Algorithms#882]
### Problem Link 
https://leetcode.com/problems/russian-doll-envelopes/

### Coding platform
Leetcode

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [x] Python

**Comment by ishikabansal04** [comment]
Please assign me in Java.

**Comment by weirdrag08** [comment]
I want to solve this in C++.

**Comment by Akash20x** [comment]
I want to solve this in python. Please assign me this issue as a part of Cross Woc

**Comment by abhinav5481** [comment]
I would like to solve it in c

**Comment by Nivedita967** [comment]
@abhinav5481 Are you working on this?

**Comment by abhinav5481** [comment]
Yeah,
I will create PR soon.
