### ISSUE TITLE
Tiling Problem

### ISSUE THREAD

**Issue by ishikabansal04** [Nivedita967/Data-Structure-and-Algorithms#883]
### Problem Link 
https://www.geeksforgeeks.org/tiling-problem/
Correct link -> https://practice.geeksforgeeks.org/problems/ways-to-tile-a-floor5836/1

### Coding platform
GeeksforGeeks 

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [x] Python

**Comment by ishikabansal04** [comment]
Please assign me in Java.

**Comment by weirdrag08** [comment]
I want to do in C++.

**Comment by abhinav5481** [comment]
Hi @Nivedita967 
I would like to solve it in Python. Please assign it to me.

**Comment by pri1311** [comment]
will do it in C

**Comment by Nivedita967** [comment]
> will do it in C

I have assigned you so many issues, After completing that all I will assign you further.
