### ISSUE TITLE
Count the number of ways to tile the floor of size n x m using 1 x m size tiles

### ISSUE THREAD

**Issue by weirdrag08** [Nivedita967/Data-Structure-and-Algorithms#884]
### Problem Link 
https://www.geeksforgeeks.org/count-number-ways-tile-floor-size-n-x-m-using-1-x-m-size-tiles/
Correct link -> https://practice.geeksforgeeks.org/problems/count-the-number-of-ways-to-tile-the-floor-of-size-n-x-m-using-1-x-m-size-tiles0509/1

### Coding platform
GeeksforGeeks

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [x] Python

**Comment by weirdrag08** [comment]
I want to solve this in C++.

**Comment by ishikabansal04** [comment]
Please assign me in Java.

**Comment by abhinav5481** [comment]
Hi @Nivedita967 
I would like to solve it in Python. Please assign it to me.

**Comment by pri1311** [comment]
will do it in C

**Comment by Amit366** [comment]
@Nivedita967 can I work in C??
