### ISSUE TITLE
Largest Rectangle

### ISSUE THREAD

**Issue by ishikabansal04** [Nivedita967/Data-Structure-and-Algorithms#885]
### Problem Link 
https://www.hackerrank.com/challenges/largest-rectangle/problem

### Coding platform
Hackerrank

### Programming language

- [x] C
- [x] C++
- [x] Java
- [x] Python

**Comment by ishikabansal04** [comment]
Please assign me in Java.

**Comment by weirdrag08** [comment]
I want to do this in C++.

**Comment by abhinav5481** [comment]
Hi @Nivedita967 
I would like to solve it in Python. Please assign it to me.

**Comment by pri1311** [comment]
will do it in C

**Comment by Amit366** [comment]
@Nivedita967 is this issue open??

**Comment by Nivedita967** [comment]
Yes @Amit366 Go for C.
