### ISSUE TITLE
Cycle Detection

### ISSUE THREAD

**Issue by weirdrag08** [Nivedita967/Data-Structure-and-Algorithms#886]
### Problem Link 
https://www.hackerrank.com/challenges/detect-whether-a-linked-list-contains-a-cycle/problem

### Coding platform
Hackerrank

### Programming language

- [ ] C
- [ ] C++
- [x] Java
- [x] Python

**Comment by weirdrag08** [comment]
Please assign me in C++.

**Comment by ishikabansal04** [comment]
Please assign me in Java.

**Comment by abhinav5481** [comment]
Hi @Nivedita967 
I would like to solve it in Python. Please assign it to me.

**Comment by pri1311** [comment]
will do it in C

**Comment by Nivedita967** [comment]
@weirdrag08 Are you working?

**Comment by abhinav5481** [comment]
Hi @Nivedita967 
Can I solve it in C?
