### ISSUE TITLE
Ice Cream Parlor

### ISSUE THREAD

**Issue by ishikabansal04** [Nivedita967/Data-Structure-and-Algorithms#887]
### Problem Link 
https://www.hackerrank.com/challenges/icecream-parlor/problem

### Coding platform
Hackerrank

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [x] Python

**Comment by ishikabansal04** [comment]
I want to do this in Java.

**Comment by weirdrag08** [comment]
Please assign me in C++.

**Comment by abhinav5481** [comment]
Hi @Nivedita967 
I would like to solve it in Python. Please assign it to me.

**Comment by pri1311** [comment]
will do it in C
