### ISSUE TITLE
Compare the Triplets

### ISSUE THREAD

**Issue by weirdrag08** [Nivedita967/Data-Structure-and-Algorithms#888]
### Problem Link 
https://www.hackerrank.com/challenges/compare-the-triplets/problem

### Coding platform
Hackerrank

### Programming language

- [x] C
- [x] C++
- [x] Java
- [x] Python

**Comment by weirdrag08** [comment]
Please assign me in C++.

**Comment by ishikabansal04** [comment]
I want to do this in Java.

**Comment by abhinav5481** [comment]
Hi @Nivedita967 
I would like to solve it in Python. Please assign it to me.

**Comment by pri1311** [comment]
will do it in C
