### ISSUE TITLE
Non-overlapping Intervals

### ISSUE THREAD

**Issue by weirdrag08** [Nivedita967/Data-Structure-and-Algorithms#889]
### Problem Link 
https://leetcode.com/problems/non-overlapping-intervals/

### Coding platform
Leetcode

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [x] Python

**Comment by weirdrag08** [comment]
Please assign me in C++.

**Comment by ishikabansal04** [comment]
Please assign me in Java.

**Comment by Akash20x** [comment]
I want to solve this in python

**Comment by pri1311** [comment]
will do it in C

**Comment by Amit366** [comment]
@Nivedita967 is it open??

**Comment by Nivedita967** [comment]
> @Nivedita967 is it open??

Yes, Go for C.
