### ISSUE TITLE
Set Matrix Zeroes

### ISSUE THREAD

**Issue by cryptus-neoxys** [Nivedita967/Data-Structure-and-Algorithms#891]
### Problem Link 
https://leetcode.com/problems/set-matrix-zeroes/

### Coding platform
LeetCode

### Programming language
- [x] C
- [x] C++
- [x] Java
- [x] Python

### Additional context (OPTIONAL)
I want to solve this in C++. Please assign it to me.

**Comment by abhinav5481** [comment]
Hi @Nivedita967 
I would like to solve it in Java. Please assign it to me.

**Comment by pri1311** [comment]
will do it in python

**Comment by Amit366** [comment]
@Nivedita967 can I work in C and C++??

**Comment by Nivedita967** [comment]
@Amit366 Go for C.

**Comment by abhinav5481** [comment]
> Hi @Nivedita967
> I would like to solve it in Java. Please assign it to me.

Can I get assigned?

**Comment by abhinav5481** [comment]
Hi @Nivedita967
Is this issue still open? Can I solve it in Python?

**Comment by Nivedita967** [comment]
> Hi @Nivedita967
> Is this issue still open? Can I solve it in Python?

Sure Go for it @abhinav5481
