### ISSUE TITLE
Divisor Game

### ISSUE THREAD

**Issue by jayantjethi** [Nivedita967/Data-Structure-and-Algorithms#892]
### Problem Link 
https://leetcode.com/problems/divisor-game/

### Coding platform
Leetcode

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by jayantjethi** [comment]
I would Like to solve this issue in C++. Kindly Assign Me.

**Comment by abhinav5481** [comment]
Hi @Nivedita967 
I would like to solve it in Java. Please assign it to me.

**Comment by pri1311** [comment]
will do it in python

**Comment by pri1311** [comment]
hey @Nivedita967 was this issue closed by mistake?
