### ISSUE TITLE
Stock Maximize

### ISSUE THREAD

**Issue by ishikabansal04** [Nivedita967/Data-Structure-and-Algorithms#896]
### Problem Link 
https://www.hackerrank.com/challenges/stockmax/problem

### Coding platform
Hackerrank

### Programming language

- [x] C
- [ ] C++
- [x] Java
- [x] Python

**Comment by ishikabansal04** [comment]
I want to solve this in Java.

**Comment by weirdrag08** [comment]
Please assign me in C++.

**Comment by pri1311** [comment]
will do it in python

**Comment by abhinav5481** [comment]
I will do it in C. Please assign it to me

**Comment by Nivedita967** [comment]
@ishikabansal04 @weirdrag08 Are you working on this?

**Comment by abhinav5481** [comment]
Hi @Nivedita967 
If this issue is open & no one is working on C++ then can I do it in C++?

**Comment by weirdrag08** [comment]
> @ishikabansal04 @weirdrag08 Are you working on this?

Yes , I am working on this.

**Comment by Nivedita967** [comment]
> > @ishikabansal04 @weirdrag08 Are you working on this?
> 
> Yes , I am working on this.

Raise PR ASAP.
