### ISSUE TITLE
Tree: Huffman Decoding

### ISSUE THREAD

**Issue by saimanoharhm** [Nivedita967/Data-Structure-and-Algorithms#921]
### Problem Link 
Mention the problem on which you want to work on
https://www.hackerrank.com/challenges/tree-huffman-decoding/problem

### Coding platform
Mention the coding platform from where you have picked the problem
hackerrank

### Programming language

- [x] C
- [x] C++
- [x] Java
- [ ] Python

**Comment by saimanoharhm** [comment]
@Nivedita967 I will work on c. Pls assign it to me under crosswoc.

**Comment by abhinav5481** [comment]
Hi @Nivedita967 
I would like to solve it in Java. Please assign it to me.

**Comment by Akash20x** [comment]
I want to solve this in python

**Comment by Amit366** [comment]
@Nivedita967 I can do in C

**Comment by Akash20x** [comment]
Please check my pull request

**Comment by Nivedita967** [comment]
@Akash20x I have requested you changes in your PR. Check it ASAP.

**Comment by Akash20x** [comment]
> @Akash20x I have requested you changes in your PR. Check it ASAP.

Done
