### ISSUE TITLE
Pawri Meme

### ISSUE THREAD

**Issue by jayantjethi** [Nivedita967/Data-Structure-and-Algorithms#939]
### Problem Link 
https://www.codechef.com/COOK127C/problems/PAWRI

### Coding platform
Codechef

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [ ] Python

**Comment by ishikabansal04** [comment]
Is c++ available for this ?

**Comment by jayantjethi** [comment]
I will like to solve this problem in c++.Kindly Assign me.

**Comment by abhinav5481** [comment]
Hi @Nivedita967 
I would like to solve it in Java. Please assign it to me.

**Comment by JASKAMAL22** [comment]
I would like to work in python . Kindly assign it to me!!

**Comment by jayantjethi** [comment]
@Nivedita967 Mam Please check my PR
