### ISSUE TITLE
Minimum Difficulty of a Job Schedule

### ISSUE THREAD

**Issue by greenblade29** [Nivedita967/Data-Structure-and-Algorithms#945]
### Problem Link 
https://leetcode.com/problems/minimum-difficulty-of-a-job-schedule/

### Coding platform
Leetcode

### Programming language

- [x] C
- [x] C++
- [ ] Java
- [x] Python

### Additional context (OPTIONAL)
I want to solve it in Java

**Comment by abhinav5481** [comment]
Hi @Nivedita967 
I would like to solve it in Python. Please assign it to me.

**Comment by Amit366** [comment]
@Nivedita967 I can do in C++.

**Comment by Akash20x** [comment]
@Nivedita967 I want to solve it in C
Please assign it to me

**Comment by Akash20x** [comment]
@Nivedita967 Please check my pull request

**Comment by Akash20x** [comment]
Please check my pull request
