### ISSUE TITLE
Scramble String

### ISSUE THREAD

**Issue by greenblade29** [Nivedita967/Data-Structure-and-Algorithms#946]
### Problem Link 
https://leetcode.com/problems/scramble-string/

### Coding platform
Leetcode

### Programming language

- [x] C
- [x] C++
- [ ] Java
- [x] Python

### Additional context (OPTIONAL)
I want to solve it in Java

**Comment by abhinav5481** [comment]
Hi @Nivedita967 
I would like to solve it in Python. Please assign it to me.

**Comment by Akash20x** [comment]
I would like to solve it in c++

**Comment by Amit366** [comment]
@Nivedita967 can I do in C?

**Comment by Amit366** [comment]
@Nivedita967 can I work in Java??
