### ISSUE TITLE
Palindrome Number

### ISSUE THREAD

**Issue by muthuannamalai12** [Nivedita967/Data-Structure-and-Algorithms#95]
Problem Link: https://leetcode.com/problems/palindrome-number/ I would love to solve this in C and Python Language as a part of Cross-Woc. Kindly assign it to me.

**Comment by deeqakkk** [comment]
I would like to solve this in C and C++ ,if u will assign this to me.

**Comment by gopichandpuli9** [comment]
I would love to solve this in python and C++

**Comment by Nivedita967** [comment]
@muthuannamalai12 -> Python.
@deeqakkk -> C
@gopichandpuli9 -> C++

**Comment by gopichandpuli9** [comment]
I've completed and made a pull request @Nivedita967

**Comment by Nivedita967** [comment]
Open for Java.

**Comment by muthuannamalai12** [comment]
> Open for Java.

Can I do it as a part of Cross-Woc.

**Comment by muthuannamalai12** [comment]
> Open for Java.

@Nivedita967 Can I do it as a part of Cross-Woc? Kindly assign it to me

**Comment by Nivedita967** [comment]
@muthuannamalai12 Sure.
