### ISSUE TITLE
Xenia and Divisors

### ISSUE THREAD

**Issue by kanak22** [Nivedita967/Data-Structure-and-Algorithms#959]
### Problem Link 
https://codeforces.com/problemset/problem/342/A

### Coding platform
Codeforces

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [ ] Python

### Additional context (OPTIONAL)
I would like to work on this in c++.

**Comment by JASKAMAL22** [comment]
I would like to work in python :)

**Comment by abhinav5481** [comment]
Hi @Nivedita967 
I would like to solve it in Python. please assign it to me

**Comment by Nivedita967** [comment]
> Hi @Nivedita967
> I would like to solve it in Python. please assign it to me

Python is not open.

**Comment by pri1311** [comment]
Can I do it in Java?

**Comment by abhinav5481** [comment]
> > Hi @Nivedita967
> > I would like to solve it in Python. please assign it to me
> 
> Python is not open.

Okay. Can I solve it in Java or C?

**Comment by Nivedita967** [comment]
> Can I do it in Java?

I have assigned you many issues. Complete them first.

**Comment by Nivedita967** [comment]
> > > Hi @Nivedita967
> > > I would like to solve it in Python. please assign it to me
> > 
> > 
> > Python is not open.
> 
> Okay. Can I solve it in Java or C?

Go for Java.

**Comment by Nivedita967** [comment]
@JASKAMAL22 Are you working on this?
