### ISSUE TITLE
Add two numbers problem on codechef

### ISSUE THREAD

**Issue by kmryashasvi** [Nivedita967/Data-Structure-and-Algorithms#96]
Please be kind enough to let me work on [AddTwoNumbers](https://www.codechef.com/problems/FLOW001),
I will be adding its source code in C as well as in C++
(They have a very slight difference, hence they can be done simultaneously)

Thank you

**Comment by kmryashasvi** [comment]
for this problem:

- [ ] C

- [ ] C++

- [ ] Java

- [ ] Python

**Comment by kmryashasvi** [comment]
I can add its python code too, if you allow

**Comment by kmryashasvi** [comment]
> I can add its python code too, if you allow

Can I go forward?

**Comment by Nivedita967** [comment]
> > I can add its python code too, if you allow
> 
> Can I go forward?

Let others try.

**Comment by Abhichal18** [comment]
@Nivedita967  Yeah, i would like to contribute
