### ISSUE TITLE
Letter

### ISSUE THREAD

**Issue by kanak22** [Nivedita967/Data-Structure-and-Algorithms#960]
### Problem Link 
https://codeforces.com/problemset/problem/43/B

### Coding platform
Codeforces

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [ ] Python

### Additional context (OPTIONAL)
I would like to work on this in C++.

**Comment by abhinav5481** [comment]
I would like to solve it in Java. Please assign it to me

**Comment by JASKAMAL22** [comment]
I would like to do in python. Kindly assign it to me!

**Comment by pri1311** [comment]
@Nivedita967 can I do it in C?

**Comment by Nivedita967** [comment]
> @Nivedita967 can I do it in C?

Complete your all pending issues first @pri1311

**Comment by Amit366** [comment]
@Nivedita967 is it open for C??

**Comment by Nivedita967** [comment]
> @Nivedita967 is it open for C??

yes

**Comment by abhinav5481** [comment]
Hi @Nivedita967 
Can I solve it in C?

**Comment by Amit366** [comment]
> > @Nivedita967 is it open for C??
> 
> yes

@Nivedita967 please assign me

**Comment by Nivedita967** [comment]
> > > @Nivedita967 is it open for C??
> > 
> > 
> > yes
> 
> @Nivedita967 please assign me

Sure @Amit366 Go for it.

**Comment by Nivedita967** [comment]
@JASKAMAL22 Are you working?
