### ISSUE TITLE
Little Girl and Game

### ISSUE THREAD

**Issue by kanak22** [Nivedita967/Data-Structure-and-Algorithms#961]
### Problem Link 
https://codeforces.com/problemset/problem/276/B

### Coding platform
Codeforces

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [x] Python

### Additional context (OPTIONAL)
I would like to work on this in C++.

**Comment by Kpraful** [comment]
May I, In python?

**Comment by abhinav5481** [comment]
Hi @Nivedita967 
I would like to solve it in Java. Please assign it to me

**Comment by JASKAMAL22** [comment]
I would like to do it in python. Kindly assign it to me :)

**Comment by Nivedita967** [comment]
> I would like to do it in python. Kindly assign it to me :)

Python is not open.

**Comment by pri1311** [comment]
will do it in C
