### ISSUE TITLE
Count Vowels Permutation

### ISSUE THREAD

**Issue by Akash20x** [Nivedita967/Data-Structure-and-Algorithms#967]
### Problem Link 
https://leetcode.com/problems/count-vowels-permutation/description/

### Coding platform
Leetcode 

### Programming language

- [x] C
- [x] C++
- [x] Java
- [x] Python

### Additional context (OPTIONAL)
I want to solve this in python 
This is leetcode (Hard) problem

**Comment by Akash20x** [comment]
Please consider this and assign me this issue to solve in python

**Comment by abhinav5481** [comment]
Hi @Nivedita967 
I would like to solve it in Java. Please assign it to me.

**Comment by kanak22** [comment]
I would like to solve this in C++

**Comment by pri1311** [comment]
will do it in C

**Comment by Akash20x** [comment]
Please check my pull request

**Comment by Akash20x** [comment]
@Nivedita967 Please now check my pull request

**Comment by Akash20x** [comment]
@Nivedita967 Please check my pull request

**Comment by Akash20x** [comment]
@Nivedita967 Please check my pull request

**Comment by abhinav5481** [comment]
Hi @Nivedita967
Is this issue still open? Can I solve it in C?
