### ISSUE TITLE
Day of the Programmer

### ISSUE THREAD

**Issue by kavania2002** [Nivedita967/Data-Structure-and-Algorithms#99]
Day of the Programmer : Hackerrank - https://www.hackerrank.com/challenges/day-of-the-programmer/problem

I will do it in Python3

**Comment by Nivedita967** [comment]
@kavania2002 Go for it :)

**Comment by Nivedita967** [comment]
@TechSpiritSS This issue is open for C and C++ both.

**Comment by TechSpiritSS** [comment]
I am not familiar with string manipulation to solve this one

**Comment by kanak22** [comment]
can i do this in c++?

**Comment by Nivedita967** [comment]
@kanak22 Sure, Go for it. Also join Gitter channel.

**Comment by Nivedita967** [comment]
Open for C and Java.

**Comment by kanak22** [comment]
from where i can join the gitter channel?

**Comment by kavania2002** [comment]
https://gitter.im/Data-Structure-and-Algorithms-Nivedita/community?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge
You can join from this link.
